ji-devs/ji-cloud

backend/pages/Cargo.lock
backend/pages/handlebars/404.hbs
backend/pages/handlebars/home.hbs
backend/pages/handlebars/info.hbs
backend/pages/handlebars/no-auth.hbs
backend/pages/handlebars/spa.hbs
backend/pages/src/reject.rs
backend/pages/src/templates/spa.rs
backend/pages/src/user/auth.rs
frontend/_devfiles/index.html

include firebase for user routes

---

backend/api/Cargo.lock
backend/api/crates/actions/Cargo.toml
backend/api/crates/server/Cargo.toml
backend/api/migrations/20200730195239_extensions.sql
backend/api/migrations/20200730195601_add_user.sql
backend/api/migrations/20200730202320_add_user-scope.sql
backend/api/migrations/20200730202659_add_category.sql

 feat: add a schema 

---

frontend/_core/templates/_buttons/button-macros.html
frontend/admin/css/package.json
frontend/admin/storybook/src/css/search.css
frontend/admin/storybook/src/stories/imagelabel.stories.js
frontend/admin/templates/categories/categories-macros.html
frontend/admin/templates/categories/categories-page.html
frontend/admin/templates/imagelabel.html

Adding category fixes and image labelling

Adding category fixes

---

backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs
backend/pages/templates/spa.html

* template loads CSS per SPA
* routes support admin/*

pages template

---

frontend/admin/storybook/src/stories/jig.stories.js
frontend/user/css/src/signup.css
frontend/user/storybook/src/stories/register.stories.js
frontend/user/templates/forgot-password.html
frontend/user/templates/register/register-1.html
frontend/user/templates/register/register-2.html
frontend/user/templates/register/register-google.html

adding changes for sign up and login

login changes

---

backend/api/src/http/endpoints/image.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/domain/image.rs

fix: return a url to replace an image on image update

---

backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
shared/rust/src/api/endpoints/user.rs
shared/rust/src/domain/user.rs

(returns 200 with the ID if the user does exist, and 404s if it doesn't)

feat: add `/v1/user/{name}` route to get user by username

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/integration-testing/test.js
backend/api/migrations/20200928232141_last_synced_at_for_images.sql
backend/api/src/algolia.rs
backend/api/src/http/endpoints/category.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/main.rs
shared/rust/Cargo.toml
shared/rust/src/domain.rs
shared/rust/src/domain/category.rs
shared/rust/src/domain/image.rs
shared/rust/src/domain/meta.rs
shared/rust/src/domain/ser.rs

Sorry this took so long (and still needs the thing for updating algolia indecies now that they've changed), I figured I would want to put this up to give a bit of a status report.
relevant algolia-rs changes made to get this working: https://gitlab.com/izik1/algolia-rs/-/compare/551b896ad4235d674a8ec38f0c00dfc6e52c5a08...61911d09cbf0c4361c73afe64fdbd881cdbb0f95

feat: algolia pagation & filtering

---

backend/api/sqlx-data.json

run sqlx prepare (missed in a prior commit)

fix: run `cargo sqlx prepare`

---

frontend/admin/templates/jig/jig-add-module.html

Adding progress to JIG. Missing hovering and right menu.

Adding to JIG

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/fixtures/5_image.sql
backend/api/integration-testing/test.js
backend/api/migrations/20201001211308_image_kind.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/image.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/image_ops.rs
backend/api/src/lib.rs
backend/api/src/s3.rs
config/rust/src/lib.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/domain/image.rs
shared/rust/src/error/image.rs

(note: this requires truncating the image-metadata table due to an implementation choice, that was signed off on by @dakom)

feat: add resized image and thumbnail generation

---

backend/api/integration-testing/yarn.lock
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
shared/rust/src/api/endpoints/user.rs
shared/rust/src/domain/user.rs

feat: replace user-by-name route with a more general "lookup user" route

---

backend/api/src/http/endpoints/user.rs

fix: return `NoSuchUserError` on user lookup 404

---

backend/api/migrations/20201102182349_geocode_to_location.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
shared/rust/src/domain/auth.rs
shared/rust/src/domain/user.rs

fix!: Use `json` for location instead of a geocode string

---

backend/api/migrations/20201109184759_add_user-web-image-library-tables.sql
backend/api/src/http/endpoints/image.rs
backend/api/src/s3.rs

(working on the actual implementations)

feat: add sql for image libraries

---

shared/rust/src/domain/jig/module.rs

feat: add str conversions for ModuleKind

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db.rs
backend/api/src/db/category.rs
backend/api/src/db/image.rs
backend/api/src/http.rs
backend/api/src/http/cors.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/jwkkeys.rs
backend/api/src/jwt.rs
backend/api/src/s3.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/api/method.rs
shared/rust/src/domain/image.rs

Hopefully it works, it's a bit late on a Monday and I haven't had time to do so, I figured I should post it in case I missed something, closes #196, based off of #325

User image library

---

backend/pages/Cargo.lock
backend/pages/Cargo.toml
backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs

feat(pages): add module route

---

backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs

feat(pages): make jig route only accept edit/play

---

frontend/apps/crates/utils/src/routes.rs
shared/rust/src/domain/jig/module.rs

also use builtin ModuleKind From/ToStr

"memory-game" should be "memory"

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/sqlx-data.json
backend/api/src/algolia.rs

feat: Add search by categories and add priority to the searching order

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/src/algolia.rs
backend/api/src/main.rs

An algolia API method was borked

fix: make the server actually run again

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
shared/rust/src/media.rs

fix: properly filter category names on algolia

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/http/endpoints/image.rs

fix: properly allow filtering

---

frontend/templates/module/memory/edit/_common/main/card-pairs/macros.html
frontend/templates/module/memory/edit/_common/main/card-pairs/text-image-edit.html
frontend/templates/module/memory/edit/_common/main/card-pairs/text-image-preview.html
frontend/templates/module/memory/edit/_common/sidebar/step2.html

UI fixes memory game

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs

Closes #503, hopefully does the same for #467 and doesn't cause a similar thing

Algolia extra searchable attributes

---

backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs

feat(pages): add /dev/* pages

---

backend/api/src/image_ops.rs

fix: image resizing was using incorrect algorithms

---

backend/pages/src/templates/spa.rs
backend/pages/templates/spa.html

feat(pages): add custom elements to spa pages

---

backend/api/src/http/endpoints/image.rs
backend/api/src/image_search.rs
backend/api/src/lib.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/domain/image.rs

Closes #452
Currently missing pagation and such, but those can be added later

feat: add web image searching

---

shared/rust/src/domain.rs
shared/rust/src/domain/animation.rs
shared/rust/src/media.rs

added animation enum

---

.env.sample

It's better to read this as a rewrite of the file, rather than via a diff

refactor: make .env.sample clearer

---

.env.sample
backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/src/algolia.rs
backend/api/src/error.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/http/endpoints/search.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/api/endpoints.rs
shared/rust/src/api/endpoints/search.rs
shared/rust/src/domain.rs
shared/rust/src/domain/search.rs

feat: add generation of frontend keys for algolia

---

.env.sample
backend/api/migrations/20210111220544_drop-index-name.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/main.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
config/rust/src/lib.rs
shared/rust/src/media.rs

Media collation

---

backend/pages/Cargo.lock
backend/pages/Cargo.toml
backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs

Add legacy spa routes to page

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/migrations/20210115193324_web-media-library.sql
backend/api/sqlx-data.json
backend/api/src/error.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/media.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/http/endpoints/search.rs
backend/api/src/image_ops.rs
backend/api/src/image_search.rs
backend/api/src/s3.rs
shared/rust/Cargo.toml
shared/rust/src/api/endpoints.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/api/endpoints/media.rs
shared/rust/src/api/endpoints/search.rs
shared/rust/src/domain.rs
shared/rust/src/domain/image.rs
shared/rust/src/domain/media.rs
shared/rust/src/domain/search.rs
shared/rust/src/domain/ser.rs
shared/rust/src/media.rs

Close #195
~Only missing a List route (need more definition for it)~

Web media library

---

frontend/elements/src/entry/jig/publish/dropdown-list-object.ts
frontend/elements/src/entry/jig/publish/page-2.ts
frontend/elements/src/entry/jig/publish/page.ts
frontend/elements/src/entry/jig/publish/publish-dropdown.ts
frontend/elements/src/entry/jig/publish/publish-embed.ts
frontend/elements/src/entry/jig/publish/sharing-caring.ts

Adding publish elements and fixes from QA

Publish elements 

---

backend/api/src/extractor.rs

This... Seems like a decent baseline

fix: make passwords harder to crack (more iterations on the hash alg)

---

backend/api/src/google.rs

fix: oauth should use `pages_url` not `frontend_url`

---

.env.sample
backend/api/integration-testing/test.js
backend/api/src/algolia.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/admin.rs
backend/api/src/http/endpoints/animation.rs
backend/api/src/http/endpoints/audio.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/media.rs
backend/api/src/http/endpoints/search.rs
backend/api/src/jwk.rs
backend/api/src/lib.rs
backend/api/src/main.rs
backend/api/src/s3.rs
backend/api/src/service.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs

also makes some secrets "optional" (as in, not required for the server to "run" still required for whatever they're used for)

refactor(backend): Finally make various api requests 501 instead of giving default results

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/image.rs
backend/api/src/http/endpoints/image.rs
shared/rust/src/api/endpoints/image.rs
shared/rust/src/domain/image.rs

feat(backend/api): browse images route

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs

fix(backend/api): properly handle non-published images

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/db/image.rs
backend/api/src/http/endpoints/image.rs
backend/api/tests/integration/snapshots/integration__image__get_metadata.snap
backend/api/tests/integration/snapshots/integration__image__update_empty.snap
backend/api/tests/integration/snapshots/integration__image__update_is_premium.snap
backend/api/tests/integration/snapshots/integration__image__update_styles.snap
shared/rust/src/domain/image.rs

feat(backend/api): make image kind searchable/gettable

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/animation.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/domain/jig.rs

feat(backend/api): add browse route for jigs

---

frontend/elements/src/core/inputs/checkbox.ts
frontend/elements/src/core/inputs/file.ts
frontend/elements/src/core/inputs/inc-dec.ts
frontend/elements/src/core/progress-bar/progress-bar.ts
frontend/elements/src/module/_common/widgets/audio-input/audio-input.ts
frontend/elements/src/module/_common/widgets/image-select/image-select-filters.ts
frontend/elements/src/module/_common/widgets/image-select/image-select-style-option.ts
frontend/elements/src/module/_common/widgets/image-select/image-select-upload.ts
frontend/elements/src/module/_common/widgets/image-select/image-select.ts
frontend/storybook/src/components/core/progress-bar/progress-bar.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/audio-input/audio-input-full.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/audio-input/audio-input-recording.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/audio-input/audio-input.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/image-select/image-select-filters.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/image-select/image-select-style-option.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/image-select/image-select-upload.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/image-select/image-select.ts

Updates are mainly for audio-input and image-select

Poster and cover elements additions

---

frontend/apps/Cargo.lock
frontend/apps/crates/components/Cargo.toml
frontend/apps/crates/components/src/audio_input/actions.rs
frontend/apps/crates/components/src/audio_input/components/add_method.rs
frontend/apps/crates/components/src/audio_input/components/delete.rs
frontend/apps/crates/components/src/audio_input/components/main_action.rs
frontend/apps/crates/components/src/audio_input/components/main_content.rs
frontend/apps/crates/components/src/audio_input/components/mod.rs
frontend/apps/crates/components/src/audio_input/components/play_progress.rs
frontend/apps/crates/components/src/audio_input/dom.rs
frontend/apps/crates/components/src/audio_input/mod.rs
frontend/apps/crates/components/src/audio_input/recorder.rs
frontend/apps/crates/components/src/audio_input/state.rs
frontend/apps/crates/components/src/lib.rs
frontend/apps/crates/entry/dev/scratch/001/src/page.rs
frontend/apps/package-lock.json
frontend/apps/package.json
frontend/apps/rollup.local.js
frontend/elements/src/_bundles/dev/scratch/001/imports.ts
frontend/elements/src/core/inputs/file.ts
frontend/elements/src/core/progress-bar/progress-bar.ts
frontend/elements/src/module/_common/widgets/audio-input/audio-input-delete.ts
frontend/elements/src/module/_common/widgets/audio-input/audio-input.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/audio-input/audio-input-delete.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/audio-input/audio-input-full.ts

Features still missing
- Delete not deleting from server (not sure that this is what ideation wants)
- Cancel upload not working yet, first wanna hear how we deal with deleting and maybe combine them somehow

Added Rust side of audio input

---

backend/api/src/db/module.rs
backend/api/tests/integration/jig/module.rs
backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap

closes #899 
cc: #897 (is this still the case after this fix)

fix(backend/api): resolve deadlock that occurs on module update

---

backend/api/migrations/20210402201545_jig-parents.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/auth/forbidden.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/snapshots/integration__jig__clone.snap
shared/rust/src/api/endpoints/jig.rs

feat(backend/api): add jig duplication api

---

frontend/apps/Cargo.lock
frontend/apps/crates/components/Cargo.toml
frontend/apps/crates/components/src/color_select/actions.rs
frontend/apps/crates/components/src/color_select/dom.rs
frontend/apps/crates/components/src/color_select/state.rs
frontend/apps/crates/entry/dev/scratch/001/src/page.rs
frontend/apps/crates/utils/Cargo.toml
frontend/apps/crates/utils/src/lib.rs
frontend/apps/crates/utils/src/themes.rs
frontend/config/themes.json
frontend/elements/src/_bundles/dev/scratch/001/imports.ts
frontend/elements/src/module/_common/widgets/color-select/color-select-item.ts
frontend/elements/src/module/_common/widgets/color-select/color-select-section.ts
frontend/elements/src/module/_common/widgets/color-select/color-select.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/color-select/color-select-item.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/color-select/color-select-section.ts
frontend/storybook/src/components/module/_common/widgets/sidebar/color-select/color-select.ts

Updated color select according to new design

---

frontend/apps/crates/components/src/audio_input/actions.rs
frontend/apps/crates/components/src/audio_input/components/add_method.rs
frontend/apps/crates/components/src/audio_input/components/delete.rs
frontend/apps/crates/components/src/audio_input/components/main_action.rs
frontend/apps/crates/components/src/audio_input/components/main_content.rs
frontend/apps/crates/components/src/audio_input/components/player/actions.rs
frontend/apps/crates/components/src/audio_input/components/player/dom.rs
frontend/apps/crates/components/src/audio_input/dom.rs
frontend/apps/crates/components/src/audio_input/options.rs
frontend/apps/crates/components/src/audio_input/state.rs
frontend/apps/crates/entry/dev/scratch/001/src/page.rs

State refactoring in audio input

---

frontend/elements/src/module/_common/sidebar-body.ts
frontend/elements/src/module/_common/sidebar.ts
frontend/elements/src/module/memory/edit/steps/sections/sidebar/step1/empty.ts

Vertical center the "Edit words on cards"

---

backend/api/src/db/module.rs
backend/api/src/http/endpoints/module.rs
backend/api/tests/integration/jig/module.rs
backend/api/tests/integration/jig/snapshots/integration__jig__module__update_empty.snap
backend/api/tests/integration/jig/snapshots/integration__jig__module__update_kind.snap
shared/rust/src/domain/jig/module.rs
shared/rust/src/domain/jig/module/body.rs

feat(backend/api): add initial ModuleBody impl

---

frontend/elements/src/core/page-header/page-header-link.ts
frontend/elements/src/core/page-header/page-header.ts
frontend/elements/src/module/_common/jig-gallery/jig-gallery-create.ts
frontend/elements/src/module/_common/jig-gallery/jig-gallery-recent.ts
frontend/elements/src/module/_common/jig-gallery/jig-gallery-template.ts
frontend/elements/src/module/_common/jig-gallery/jig-gallery.ts
frontend/elements/src/module/_common/jig-gallery/styles.ts
frontend/storybook/src/components/core/page-header/page-header-link.ts
frontend/storybook/src/components/core/page-header/page-header.ts
frontend/storybook/src/components/module/_common/jig-gallery/jig-gallery-create.ts
frontend/storybook/src/components/module/_common/jig-gallery/jig-gallery-recent.ts
frontend/storybook/src/components/module/_common/jig-gallery/jig-gallery-template.ts
frontend/storybook/src/components/module/_common/jig-gallery/jig-gallery.ts

Jig gallery elements

---

backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap
shared/rust/src/domain/jig/module.rs
shared/rust/src/domain/jig/module/body.rs
shared/rust/src/domain/jig/module/body/memory.rs
shared/rust/src/domain/jig/module/body/poster.rs

@dakom, @dani-ji I noticed that formatting was failing on sandbox, so I went and fixed that... I also noticed that the struct for memory modules changed, which broke a test on the backend...

Fix formatting and tests

---

backend/api/fixtures/2_meta_kinds.sql
backend/api/migrations/20210427174953_content-type-goal.sql
backend/api/sqlx-data.json
backend/api/src/db.rs
backend/api/src/db/jig.rs
backend/api/src/db/meta.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/meta.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__meta__get.snap
shared/rust/src/domain/jig.rs
shared/rust/src/domain/meta.rs

refactor!(api): rename "ContentType" to "Goal"

---

backend/api/fixtures/12_user_font.sql
backend/api/migrations/20210426153720_user-font-table.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/http/endpoints/user/font.rs
backend/api/tests/integration/fixture.rs
backend/api/tests/integration/user.rs
backend/api/tests/integration/user/font.rs
backend/api/tests/integration/user/snapshots/integration__user__font__create.snap
backend/api/tests/integration/user/snapshots/integration__user__font__delete.snap
backend/api/tests/integration/user/snapshots/integration__user__font__get_all.snap
backend/api/tests/integration/user/snapshots/integration__user__font__update.snap
shared/rust/src/api/endpoints/user.rs
shared/rust/src/api/endpoints/user/fonts.rs
shared/rust/src/domain/user.rs

feat: add user fonts list

---

backend/api/fixtures/13_user_default_perms.sql
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/fixture.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
shared/rust/src/domain/jig.rs

feat(backend): allow users to list jigs they created

---

shared/rust/src/domain/jig/module/body.rs
shared/rust/src/domain/jig/module/body/poster.rs

cc @dakom, @MendyBerger
note: I noticed `Transformation` seems to be *Affine* Transformations in particular, if this is the case, I'd recommend calling it that, or documenting it somewhere, and `new` seems to be the identity transform, in which case, I'd recommend making it a `const IDENTITY: Transformation = <expr>`, or calling the function `identity`

style(shared): run `cargo fmt`

---

backend/api/fixtures/12_user_font.sql
backend/api/migrations/20210428184042_user-font-table.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user/font.rs
backend/api/tests/integration/user/font.rs
backend/api/tests/integration/user/snapshots/integration__user__font__create.snap
backend/api/tests/integration/user/snapshots/integration__user__font__delete.snap
backend/api/tests/integration/user/snapshots/integration__user__font__get_all.snap
backend/api/tests/integration/user/snapshots/integration__user__font__update.snap
shared/rust/src/api/endpoints/user/fonts.rs
shared/rust/src/domain/user.rs

@izik1 
* style:
* Updated `UserFontRequest` field name from `font_name` -> `name`
* Database column name and queries renamed accordingly
* Updated `UserFontResponse` field name from `fonts` -> `names`
* docs:
* Fixed wrong/missing doc comments

chore: follow-up to user fonts PR #995

---

backend/api/migrations/20210505195724_jig-sync-affiliations-age-ranges.sql
backend/api/migrations/20210505195724_jig-synced.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/auth/forbidden.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/domain/jig.rs

Jig search

---

frontend/apps/crates/components/src/text_editor/components/text_editor_controls/color_controls.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/header/dom.rs
frontend/apps/crates/entry/jig/edit/src/publish/components/categories_select.rs
frontend/elements/src/core/inputs/dropdowns/dropdown-select.ts
frontend/elements/src/core/lists/li-check-collection.ts
frontend/elements/src/core/overlays/anchored-overlay.ts
frontend/storybook/src/components/core/inputs/dropdowns/dropdown-select.ts
frontend/storybook/src/components/core/overlay/anchored-overlay.ts

Publish page categories UI

---

frontend/apps/crates/components/Cargo.toml
frontend/apps/crates/components/src/color_select/dom.rs
frontend/apps/crates/components/src/color_select/state.rs
frontend/apps/crates/components/src/image_search/actions.rs
frontend/apps/crates/components/src/image_search/dom.rs
frontend/apps/crates/components/src/image_search/state.rs
frontend/apps/crates/components/src/text_editor/components/text_editor_controls/color_controls.rs
frontend/apps/crates/components/src/text_editor/components/text_editor_controls/text_editor_controls.rs
frontend/apps/crates/components/src/text_editor/state.rs
frontend/apps/crates/entry/admin/src/locale/dom.rs
frontend/apps/crates/entry/dev/scratch/001/src/page.rs
frontend/elements/src/core/wysiwyg/wysiwyg-base.ts

Resolves #1071
Resolves #1073
Resolves #1046

Resolve some issues 

---

frontend/apps/crates/components/src/text_editor/components/wysiwyg.rs
frontend/apps/crates/components/src/text_editor/state.rs
frontend/apps/crates/entry/dev/scratch/001/src/page.rs
frontend/apps/crates/utils/src/events.rs
frontend/elements/src/core/wysiwyg/slate-wysiwyg-react/EditorComponent.ts
frontend/elements/src/core/wysiwyg/styles.ts
frontend/elements/src/core/wysiwyg/wysiwyg-base.ts
frontend/elements/src/module/_common/widgets/text-editor-controls/text-editor-controls.ts

Added blur event to wysiwyg

---

backend/api/fixtures/8_jig.sql
backend/api/migrations/20210522023748_jig-fields-updated-description-public.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/image.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/jig/cover.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
shared/rust/src/domain/jig.rs

feat(api/backend): added jig fields description, last_edited, is_public

---

backend/api/migrations/20210608165328_rename-themeid-none-blank.sql
backend/api/tests/integration/jig/module.rs
backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap

updates database for change to `ThemeId` in https://github.com/ji-devs/ji-cloud/commit/8c96cc512c19a71d8259e0c18720753bce4c793e

refactor: change `ThemeId::None` -> `ThemeId::Blank`

---

backend/api/src/http/endpoints/jig.rs
shared/rust/src/api/endpoints/jig.rs

feat: remove auth for jig search, add docs for jig endpoints

---

backend/api/fixtures/8_jig.sql
backend/api/migrations/20210614190411_jig-module-editorstate-migration.sql
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap

feat: update jig modules database for body changes `EditorState`

---

backend/api/migrations/20210614205917_jig-settings-direction-score-theme.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
shared/rust/src/domain/jig.rs

#1098:
* `direction: TextDirection` enum
* `display_score: bool`
* `theme: Themeid`

feat: add jig settings fields for direction, display_score, theme

---

backend/api/fixtures/8_jig.sql
backend/api/migrations/20210617221637_jig-settings-audio-select.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/jig/cover.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
shared/rust/src/domain/jig.rs
shared/rust/src/domain/jig/module/body.rs

feat: jig settings for audio background, feedback with placeholder enums

---

backend/api/fixtures/8_jig.sql
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__count.snap
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/domain/jig.rs

feat(backend/api): public endpoint to get total jig count

---

backend/api/src/db/module.rs

feat(backend): promote drag and drop modules to be read/write-able

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/src/extractor.rs
backend/api/src/token.rs
backend/api/tests/integration/helpers.rs
shared/rust/src/api/endpoints/session.rs
shared/rust/src/domain/session.rs

resolves #1183 
See [docs](https://docs.sandbox.jicloud.org/crate/shared/domain/session/struct.NewSessionResponse.html)

feat(session/auth): allow passing auth token as query or header

---

backend/api/src/bin/watch-uploads.rs
backend/api/src/service/notifications.rs
backend/api/src/service/uploads.rs
backend/api/tests/integration/image.rs
backend/api/tests/integration/service.rs
backend/core/src/settings.rs
config/rust/src/lib.rs

fix(watch-media): correct event source for auditlog events

---

backend/api/fixtures/5_image.sql
backend/api/fixtures/9_animation.sql
backend/api/migrations/20210726220456_user-image-library-default-uploaded-at.sql
backend/api/sqlx-data.json
backend/api/src/db/animation.rs
backend/api/src/db/image.rs
backend/api/src/db/image/user.rs
backend/api/src/db/jig.rs
backend/api/tests/integration/service.rs

fix(backend): only browse/get processed media files

---

backend/api/src/service/uploads.rs

fix(watch-media): set correct GCS target for user images

---

backend/api/migrations/20210727233537_user-profile-trigger-updated-at.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/error.rs
backend/api/src/error/user.rs
backend/api/src/extractor.rs
backend/api/src/http/endpoints/user.rs
backend/api/tests/integration/snapshots/integration__user__patch_profile.snap
backend/api/tests/integration/user.rs
shared/rust/src/api/endpoints/user.rs
shared/rust/src/api/endpoints/user/profile.rs
shared/rust/src/domain/user.rs

patch profile API

---

backend/api/fixtures/15_meta_kinds_image.sql
backend/api/sqlx-data.json
backend/api/src/db/meta.rs
backend/api/tests/integration/snapshots/integration__meta__get.snap

fix(backend/metadata): remove duplicates when fetching {media}_styles

---

backend/api/src/db/module.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/jig/snapshots/integration__jig__draft__create_draft-2.snap
backend/api/tests/integration/jig/snapshots/integration__jig__draft__get_draft-2.snap
backend/api/tests/integration/jig/snapshots/integration__jig__draft__publish_draft.snap
backend/api/tests/integration/jig/snapshots/integration__jig__player__get.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap

Promote video module, pass CI for `TextDirection` rename

---

backend/api/src/http/endpoints/category.rs
backend/api/src/http/endpoints/module.rs
backend/api/tests/integration/auth/unauthorized.rs
backend/api/tests/integration/jig/player.rs
backend/api/tests/integration/jig/snapshots/integration__jig__draft__publish_draft-2.snap
backend/api/tests/integration/jig/snapshots/integration__jig__player__create-2.snap
shared/rust/src/api/endpoints/category.rs
shared/rust/src/api/endpoints/jig/module.rs

resolves #1248 
resolves #1251

feat(backend/api): make GET category, GET module endpoints public

---

backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/category.rs
backend/api/src/http/endpoints/jig.rs
shared/rust/src/domain/jig.rs

fix!(search/jig): rename response field to `total_jig_count`, remove unused facet

---

backend/api/README.md

fixed the readme to get the backend api running. None of the code was edited.

feat: fixed the readme for backend api

---

backend/api/Cargo.lock
backend/api/Cargo.toml

Fix tokio incompatible dep

---

backend/api/src/algolia.rs
backend/api/src/service.rs
backend/core/src/google.rs

fix(backend/api): fix deadlock when refreshing GCP auth

---

.gitignore
backend/util/cloud-fn-sticker-resize/README.md
backend/util/cloud-fn-sticker-resize/db.py
backend/util/cloud-fn-sticker-resize/image_ops.py
backend/util/cloud-fn-sticker-resize/main.py
backend/util/cloud-fn-sticker-resize/requirements.txt
backend/util/cloud-fn-sticker-resize/storage.py

fix: cloud function util for batch resizing all stickers

---

backend/api/migrations/20210921154513_web_media_upload.sql
backend/api/query/list_media.sql
backend/api/sqlx-data.json
backend/api/src/bin/media-watch.rs
backend/api/src/db.rs
backend/api/src/db/media.rs
backend/api/src/http/endpoints/admin.rs
backend/api/src/http/endpoints/media.rs
backend/api/src/service/upload.rs

Incorporate web media processing 

---

backend/api/migrations/20210927191121_profile-image-api-upload-profile-create.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
backend/api/tests/integration/snapshots/integration__user__patch_profile.snap
backend/api/tests/integration/snapshots/integration__user__post_profile.snap.new
backend/api/tests/integration/user.rs
shared/rust/src/domain/user.rs

fix(backend/api/profile): profile image upload during Create, update with ImageID

---

backend/api/sqlx-data.json
backend/api/src/db/jig/module.rs
backend/api/tests/integration/jig/module.rs

closes issue #1640 
Create module response returns the Unique Id (not stable) which is necessary for other routes

Create Module now returns unique Id

---

backend/pages/src/server/routes.rs

closes issue: #1719 
fixed user path routes in pages

fix(be/pages): correct user path

---

backend/api/sqlx-data.json
backend/api/src/main.rs
shared/rust/src/domain/jig/module/body/_groups/design.rs

fix(be): serialize sticker variants with snake case

---

backend/api/migrations/20211022193302_delete_user_cascade.sql
backend/api/migrations/20211101193302_delete_user_cascade.sql

Fix(be): delete account

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/snapshots/integration__jig__count.snap

fix(be/jig_count): check for published_at for jig count

---

backend/api/sqlx-data.json
shared/rust/src/domain/jig/module/body/_groups/design.rs

fix(be): deserialization for tapping board

---

shared/rust/src/domain/jig/module/body/_groups/design.rs

fix(be): serialization for TraceKind

---

shared/rust/src/domain/jig/module/body/_groups/design.rs

fix(be/pathcommands): deserialization

---

.github/workflows/backend-api-release.yml
.github/workflows/backend-api-sandbox.yml
.github/workflows/backend-fastly-purge-release.yml
.github/workflows/backend-fastly-purge-sandbox.yml
.github/workflows/backend-media-release.yml
.github/workflows/backend-media-sandbox.yml
.github/workflows/backend-pages-release.yml
.github/workflows/backend-pages-sandbox.yml
.github/workflows/backend-screenshot-release.yml
.github/workflows/backend-screenshot-sandbox.yml
backend/api/tests/integration/helpers.rs
backend/api/tests/integration/jig/player.rs
backend/api/tests/integration/service.rs

Updated `.yaml`s in `.github` so tests use the newest version of rust

chore(be): update rust toolchain

---

backend/api/sqlx-data.json
backend/api/src/http/endpoints/search.rs
backend/api/src/image_search.rs
shared/rust/src/domain/search.rs

feat(be/image_type): search web image by type

---

backend/api/src/http/endpoints/search.rs
backend/api/src/image_search.rs
backend/api/src/main.rs
shared/rust/src/domain/search.rs

refactor(be/image_type): type check for image_type

---

backend/api/migrations/20211118215109_jig_liked.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/main.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/domain/jig.rs

feat(be/jig_metrics): add play and like to jigs

---

backend/api/migrations/20211130115524_jig_focus.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/domain/jig.rs

feat(be/jig_focus): add jig_focus field

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/error.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__count.snap
shared/rust/src/domain/jig.rs
shared/rust/src/domain/jig/additional_resource.rs

feat(be/focus): filter focus in search and browse

---

backend/api/Cargo.lock
backend/api/migrations/20211203214519_pdf_upload.sql
backend/api/sqlx-data.json
backend/api/src/bin/media-watch.rs
backend/api/src/db.rs
backend/api/src/db/jig/additional_resource.rs
backend/api/src/db/pdf.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/http/endpoints/pdf.rs
backend/api/src/main.rs
backend/api/src/service/upload.rs
shared/rust/src/api/endpoints.rs
shared/rust/src/api/endpoints/pdf.rs
shared/rust/src/domain.rs
shared/rust/src/domain/jig/additional_resource.rs
shared/rust/src/domain/meta.rs
shared/rust/src/domain/pdf.rs
shared/rust/src/media.rs

closes issue #1935 
`PdfId(PdfId)` has been added as a variant to `ResourceContent`

feat(be): add create and upload for user pdfs

---

backend/api/migrations/20211207232143_jig_focus_sync.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs

fix(be/algolia): sync live jigs with algolia

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs

fix(be/image_sync): query optional translated description

---

frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/actions.rs

Fixes an issue where the placeholder module at the end of the module list in the sidebar wouldn't be available sometimes.
Issue noted in [Slack](https://jewishinteractive.slack.com/archives/C02MDHBQ8EP/p1638870743078500).
To reproduce, add a new module to the list a few times only using the automatically created placeholder module - around the 2nd or 3rd add, it stops appearing.

fix(fe/jig/edit): Ensure a new placeholder module is always available in the sidebar

---

backend/api/migrations/20211208224006_jig_admin_keywords.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/domain/jig.rs

closes issue #1980 
Added `other_keywords`, `locked`, `translated_keywords` (Hebrew)

feat(be/jig_data): add new fields to jig data

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs

fix(be/browse_count): return proper total_count and pages

---

backend/api/migrations/20211213195655_jig_admin_data.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/domain/jig.rs

feat(be/jig_admin): add update and get jig admin data for jig object

---

frontend/apps/crates/entry/user/src/register/pages/step_1/dom.rs
frontend/apps/crates/entry/user/src/strings.rs
frontend/storybook/src/components/entry/user/register/pages/step-1.ts

fix(fe/user): Remove placeholders for user's first and last names

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
shared/rust/src/domain/jig.rs
shared/rust/src/domain/jig/additional_resource.rs

refactor(be/resources): expand additional resource object

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__additional_resource__get_draft.snap
backend/api/tests/integration/jig/snapshots/integration__jig__additional_resource__get_live.snap
shared/rust/src/domain/jig.rs
shared/rust/src/domain/jig/additional_resource.rs

fix(be/resources): change JigAdditionalResource to AdditionalResource

---

frontend/elements/src/entry/jig/edit/sidebar/module/window.ts

fix: change cursor from pointer during empty state

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs

closes #2043 
Syncing jig description to algolia

feat(be/description_sync): index jig description in algolia

---

frontend/apps/crates/components/src/module/_common/edit/entry/state.rs
frontend/apps/crates/components/src/module/_common/play/entry/state.rs
frontend/apps/crates/entry/jig/edit/src/edit/publish/publish_jig.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/debug.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/dom.rs

Updates frontend with work done in #2053

refactor(fe/jig_focus): Move jig_focus out of JigData

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/domain/jig.rs

closes issue #2057 
Deletes all jigs by the user id

feat(be/delete_jigs): add endpoint to delete all jigs by curent user

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap

close issue #2063 
Default cover module is no longer applied on jig create.

refactor(be/rm_default_mod): remove default module on jig create

---

backend/api/src/db/jig/module.rs
shared/rust/src/domain/jig/module/body.rs

feat(be/resource_cover): promote resource_cover in modules

---

frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/mod.rs
frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts

fix(fe/jig/play): Add missing robot feet in sidepanel

---

backend/api/migrations/20211227235714_remove_module_check.sql
backend/api/src/db/jig.rs

fix(be/module_check): remove constraint for jig modules

---

backend/api/migrations/20211228011601_rm_first_cover.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/domain/jig.rs

refactor(be/rm_first_cover): remove first_cover_assigned for jigs

---

frontend/apps/crates/entry/user/src/profile/dom/mod.rs
frontend/apps/crates/entry/user/src/register/pages/step_2/dom.rs
frontend/apps/crates/entry/user/src/strings.rs
frontend/elements/src/core/inputs/primitives/location.ts

Closes #1864 
Register screen:
Profile screen:

feat(user): Add placeholder value for location fields

---

backend/api/src/db/jig.rs
backend/api/src/db/pdf.rs
backend/api/src/service/storage.rs
backend/core/src/config.rs

Added file size limit for pdf documents

fix(be/pdf_size): add pdf file size limit

---

frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_2/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/dom.rs

fix(fe/components): Enable tabs for card games

---

frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs

feat: reword non-cover drag warning text

---

backend/api/migrations/20211229212903_jig_curation.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/db/jig/curation.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/jig/curation.rs
shared/rust/src/api/endpoints/jig.rs
shared/rust/src/api/endpoints/jig/curation.rs
shared/rust/src/domain/jig.rs
shared/rust/src/domain/jig/curation.rs

feat(be/jig_curation): add update and get curation data

---

backend/api/migrations/20220103213156_comment_created_at.sql
backend/api/sqlx-data.json
backend/api/src/db/jig/curation.rs
backend/api/src/http/endpoints/jig/curation.rs
shared/rust/src/api/endpoints/jig/curation.rs
shared/rust/src/domain/jig/curation.rs

feat(be/curation_comment): add get and create comment endpoints

---

frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/common.rs
frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
frontend/apps/crates/entry/module/card-quiz/play/src/base/game/state.rs
frontend/elements/src/module/_groups/cards/helpers.ts
frontend/elements/src/module/_groups/cards/play/card/card.ts

Closes #2060 
- Adds a positive animation to the card quiz when the correct answer is chosen:
https://user-images.githubusercontent.com/4161106/148037033-a6724d2b-9bff-4a06-b2c7-83cba021c431.mp4

feat(fe/module/card-quiz): Positive animation effect when choosing correct answer

---

frontend/apps/crates/entry/user/src/profile/dom/mod.rs
frontend/apps/crates/entry/user/src/profile/state.rs
frontend/apps/crates/entry/user/src/register/pages/step_2/dom.rs
frontend/apps/crates/entry/user/src/register/pages/step_2/state.rs
frontend/apps/crates/entry/user/src/register/state.rs

- Updates the frontend so that personas work with the backend changes in #2168 
**Note** does not update the actual UI.

fix(fe/user): Support multiple personas

---

frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/common.rs
frontend/apps/crates/entry/admin/src/curation/jig/actions.rs
frontend/apps/crates/entry/module/flashcards/edit/src/debug.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/main/dom.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/main/state.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/actions.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/dom.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/state.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/game/actions.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/game/state.rs
frontend/apps/crates/entry/module/flashcards/play/src/debug.rs
shared/rust/src/domain/jig/module/body/flashcards.rs

Closes #2132 
- Adds the card position config option for flashcards game;
- Unused imports cleanup

feat(fe/module/flashcards): Add card position config

---

frontend/elements/src/core/page-footer/page-footer.ts

closes #2079 
Image of editted footer from my local environment below:

feat(fe/elements/page-footer): Add dedication and reword J-STEAM

---

frontend/apps/crates/entry/jig/edit/src/edit/sidebar/debug.rs

- Updates the debug JIG initialization

fix(fe/jig/edit): Fix edit debug sidebar rating

---

frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts

Refactors logic added in #2218

refactor(jig/edit): Update label suffix logic

---

frontend/elements/src/module/_common/edit/widgets/choose-mode/choose-mode.ts

feat: quick text change in choose-mode

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs

closes #2254 
Update `draft_or_live` in db in `jig_data` table when publishing. 
Fixes 500 error

fix(be/browse): assign draft or live flag when publishing

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap

closes #2156 
Improves jig browse response time
closes #2260 
Get rid of duplicate jigs
closes #2244
Correct `total_jig_count`

fix(be/browse): optimize browse response time

---

frontend/elements/src/entry/home/home/search-section/search-section.ts

feat: reword home heading

---

frontend/elements/src/entry/home/home/search-results/search-results.ts

feat(fe/search): Update search results anchor style

---

frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
frontend/elements/src/entry/jig/gallery/gallery.ts

feat: hide templates in gallery

---

frontend/elements/src/entry/jig/play/indicator-base.ts
frontend/elements/src/entry/jig/play/landing.ts

feat: change indicator icons in jig play

---

frontend/apps/crates/entry/home/src/home/dom/iframe.rs
frontend/apps/crates/entry/home/src/home/dom/mod.rs

feat: replace home with iframe of jewishinteractive.org

---

backend/api/src/db/image.rs

feat(be/image/random_search): add random order for image search

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/error.rs
backend/api/src/error/user.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/user.rs
shared/rust/src/domain/jig.rs

feat(be/jig/search): change author_id query type to UserOrMe

---

frontend/apps/crates/components/src/lists/single/state.rs
frontend/apps/crates/components/src/module/_common/edit/entry/state.rs
frontend/apps/crates/components/src/module/_common/play/entry/state.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/debug.rs

- Updates initializations of JigData to set translated_descriptions (#2327)

chore(fe): Update JigData to include translated_description

---

backend/api/fixtures/8_jig.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/translate.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
shared/rust/src/domain/jig.rs

- `translated_description`: changed from `serde_json::Value` to `HashMap<String,String>`
- added `en` to list translated words
- get rid of json null values when creating a jig

fix(be/translation_api): change translated_description to Hashmap

---

frontend/apps/crates/components/src/module/_common/edit/entry/state.rs
frontend/apps/crates/components/src/module/_common/play/entry/state.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/debug.rs

- Updates default values for `translated_description` (Changed in #2336)

chore(fe): Update translated_description defaults

---

shared/rust/src/domain/jig/module/body/poster.rs

feat: update poster use cases

---

frontend/apps/crates/components/src/share_jig/dom.rs
frontend/apps/crates/components/src/share_jig/state.rs
frontend/elements/src/core/share-jig/option.ts
frontend/elements/src/entry/jig/edit/post-publish/post-publish-action.ts

feat: changes to publish text

---

frontend/apps/crates/entry/jig/edit/src/edit/publish/additional_resource/dom.rs
frontend/elements/src/entry/jig/edit/publish/resource.ts
shared/rust/src/domain/jig.rs

feat: enable resource link

---

frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs

Part of #2280 
- Enables the audio clip button on cards which have an audio clip

feat(fe/module/edit): Play recorded audio clip associated with cards

---

frontend/apps/Cargo.lock
frontend/apps/crates/entry/jig/play/src/player/sidebar/actions.rs
frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/report.rs
frontend/apps/crates/entry/jig/play/src/player/sidebar/state.rs
shared/rust/Cargo.toml
shared/rust/src/domain/jig/report.rs

feat: enable report button

---

backend/api/migrations/20220203091753_module_theme_id.sql

#2330 
Table for theme Ids. Once merged to sandbox this will help with assigning display names for themes to the `jig_data_module` theme in `contents`

feat(be/module): add table for theme id

---

backend/pages/templates/spa.html

feat: add hubspot tracking code to spa template

---

frontend/elements/src/module/_common/types.ts

feat: text changes for multiple choice jig

---

frontend/apps/crates/entry/home/src/home/dom/search_section/mod.rs
frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/age.rs

feat: add all ages to publish age range

---

backend/api/migrations/20220204005109_age_short_display_name.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/db/meta.rs
backend/api/tests/integration/snapshots/integration__meta__get.snap
shared/rust/src/domain/meta.rs

Added optional `short_display_name` to `AgeRange` object and added the field to the database.

feat(be/age_range): add short display name to AgeRange

---

shared/rust/src/domain/jig/module/body/cover.rs

- Fixes any cover which which has an editor state with a Step::Four for `step` field or inside `steps_completed` field.

fix(shared): Missing cover step variant workaround

---

frontend/apps/crates/utils/src/ages.rs

feat: change jig card age text

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/admin.rs
shared/rust/src/api/endpoints/admin.rs
shared/rust/src/domain/admin.rs
shared/rust/src/domain/meta.rs
shared/rust/src/domain/user.rs

Part of #2353
- Adds an export endpoint which allows exporting user profiles filtered by date range on created_at or updated_at

feat(be/admin): Add user profile export endpoint

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/admin.rs
shared/rust/src/domain/user.rs

Closes #2353
- Better naming for export files:
- Uses actual display values for subjects, age ranges and affiliations

fix(be/admin): Use better export filename and correct values for profiles export

---

backend/core/src/config.rs

See https://github.com/ji-devs/ji-cloud/issues/2139#issuecomment-1039821738

chore(be): Update max db pool connections

---

backend/core/src/config.rs

See https://github.com/ji-devs/ji-cloud/issues/2139#issuecomment-1039821738

chore(be): Decrease max db pool connections

---

frontend/elements/src/entry/user/profile/landing.ts
frontend/elements/src/entry/user/register/pages/step3.ts

feat: text changes to user profile and registration

---

backend/core/src/config.rs

See https://github.com/ji-devs/ji-cloud/issues/2139#issuecomment-1039821738

chore(be): Decrease max db pool connections to 10

---

frontend/elements/src/entry/jig/play/landing.ts

feat: dont darken pause overlay

---

backend/api/src/algolia.rs
backend/api/src/http/endpoints/image.rs

fix(be/image/search): add search by ImageKind in api and algolia

---

shared/rust/src/domain/jig/module/body/flashcards.rs

chore(fe/module/flashcards): Update default flashcard card display

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap

feat(be/jig/browse): order jigs by recently updated

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/main.rs
backend/core/Cargo.toml
backend/core/src/sentry.rs

Part of #2139 
- Adds tracing to search and get_live endpoints

chore(be/tracing): Implement tracing on get_live and search endpoints

---

backend/core/src/sentry.rs

chore(be/tracing): Reduce trace sample rate to 20% of requests

---

backend/api/Cargo.toml
backend/api/sqlx-data.json
backend/api/src/db/jig.rs

chore(be/tracing): Resolve trace grouping issues

---

frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs

feat: small text change for cards

---

backend/api/src/algolia.rs
backend/api/src/db/jig.rs
backend/api/src/main.rs
backend/core/src/sentry.rs

chore(be/tracing): Instrument search queries

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/image.rs
backend/api/src/db/jig.rs
backend/api/src/error.rs
backend/api/src/error/user.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/user.rs
shared/rust/src/domain/jig.rs

feat(be/jig): add rules for search and browse

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs

feat(be/jig/search): sync blocked status for algolia

---

frontend/elements/src/core/page-footer/page-footer.ts

feat: remove kidsafe logo from footer

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap

fix(be/jig/browse): fix query to fetch jig_data ids

---

frontend/apps/crates/components/src/page_header/state.rs
frontend/elements/src/core/page-header/beta-tooltip-content.ts

feat: update the beta popup text

---

backend/api/Cargo.lock
backend/api/migrations/20220305013320_update_live_jigs.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/image.rs
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/image.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/snapshots/integration__image__browse.snap
shared/rust/src/domain/image.rs
shared/rust/src/domain/jig.rs

closes #2028 
- Added `page_limit` field to jig and image search and browse.

feat(be): add page_limit field to image and jig browse and search

---

frontend/apps/crates/entry/admin/src/images/add/dom.rs
frontend/apps/crates/entry/admin/src/images/meta/dom.rs

- Sets page_limit to `None` in ImageSearchQuery

fix(fe/admin): Include page_limit in ImageSearchQuery

---

backend/api/src/http/endpoints/jig.rs

Revert "debug(be/search): Remove block filter from algolia query"

---

frontend/apps/crates/components/src/share_jig/state.rs

feat: change jig embed dimensions

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap

fix(be/jig/browse): fix inconsistent jig results

---

frontend/elements/src/entry/home/home/search-results/search-result.ts

fix(fe/search): Fix card flips for search results in Safari browser

---

backend/pages/src/templates/spa.rs
backend/pages/templates/spa.html

feat: dont unnecessarily show hubspot cookie

---

backend/api/sqlx-data.json
backend/api/src/db.rs
backend/api/src/db/category.rs
backend/api/src/db/image/user.rs
backend/api/src/db/session.rs
backend/api/src/db/user.rs
backend/api/src/http/endpoints/category.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/service/mail.rs
backend/api/src/service/s3.rs
backend/api/src/token.rs

- Part of #2139;
- Part of prep for performance monitoring during go-live.

chore(be): Add tracing to user endpoints

---

frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/state.rs
frontend/apps/crates/entry/module/matching/play/src/base/game/card/dom.rs
frontend/apps/crates/utils/src/init/user.rs
frontend/build-utils/dev-index.html

Closes #1599 
- Adds a confirmation modal when a teacher clicks on "Create new list"

feat(fe/module/cards): Add confirm modal when attempting to clear a list

---

frontend/apps/crates/components/src/jigzi_help/dom.rs
frontend/apps/crates/entry/jig/edit/src/edit/selection/dom.rs

feat: text changes for jiggling

---

frontend/elements/src/module/_common/edit/post-preview/post-preview.ts

Resolves #2286 
- Fixes convert-action layout

fix(fe/jig/edit): Resolve convert action layouts

---

frontend/elements/src/module/_common/edit/post-preview/post-preview-action.ts
frontend/elements/src/module/_common/edit/post-preview/post-preview.ts

Part of #2385
- Attempts to improve alignment and scale of elements for smaller screen sizes

fix(fe/jig/edit): Update resolution/sizes of module completion screen

---

.env.sample
backend/api/src/http.rs
backend/api/src/main.rs

- Only enable trace logs when `ENABLE_TRACING_LOGS="true"`

chore(be): Enable stdout traces with env var

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
build-utils/batch-user-jigs/src/context.rs
build-utils/batch-user-jigs/src/main.rs

fix(be/jig/browse): correct duplicate jigs

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
shared/rust/src/domain/jig.rs

closes #2029 
- filter jigs based off an array of ResourceTypeIds

feat(be/jig/browse): add resource type id filter

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs

closes https://github.com/ji-devs/ji-cloud/issues/1301
- set `updated_at` to now() for fields missing this in the `update jig_data` queries.

fix(be/jig/update_draft): set updated_at = now() for all fields

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/jig/player.rs

closes https://github.com/ji-devs/ji-cloud/issues/2591
- All registered users including basic and admin can create a player session

feat(be/jig/player): allow all logged in users to create a player session

---

.github/workflows/frontend-entry-app-release.yml
.github/workflows/frontend-entry-app-sandbox.yml
frontend/apps/rust-toolchain.toml

- Restores rust nightly to latest version.

chore(fe): Restore rust nightly version

---

frontend/apps/crates/entry/module/card-quiz/edit/src/router.rs
frontend/apps/crates/entry/module/card-quiz/play/src/router.rs
frontend/apps/crates/entry/module/cover/edit/src/router.rs
frontend/apps/crates/entry/module/cover/play/src/router.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/router.rs
frontend/apps/crates/entry/module/drag-drop/play/src/router.rs
frontend/apps/crates/entry/module/flashcards/edit/src/router.rs
frontend/apps/crates/entry/module/flashcards/play/src/router.rs
frontend/apps/crates/entry/module/legacy/play/src/router.rs
frontend/apps/crates/entry/module/matching/edit/src/router.rs
frontend/apps/crates/entry/module/matching/play/src/router.rs
frontend/apps/crates/entry/module/memory/edit/src/router.rs
frontend/apps/crates/entry/module/memory/play/src/router.rs
frontend/apps/crates/entry/module/poster/edit/src/router.rs
frontend/apps/crates/entry/module/poster/play/src/router.rs
frontend/apps/crates/entry/module/resource-cover/edit/src/router.rs
frontend/apps/crates/entry/module/resource-cover/play/src/router.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/router.rs
frontend/apps/crates/entry/module/tapping-board/play/src/router.rs
frontend/apps/crates/entry/module/video/edit/src/router.rs
frontend/apps/crates/entry/module/video/play/src/router.rs

@MendyBerger and @johnnynotsolucky , while working in the module area, I've noticed that the routing logic used seems a bit verbose. I wanted to ask your opinion on these changes

feat: refactor module routers

---

frontend/apps/crates/components/src/traces/svg/styles.rs

feat: reduce thickness of blue selection border

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/service/mail.rs
backend/core/src/settings.rs

closes #2625 
- name included in reset email as well

feat(be/user_emails): add first name to template field

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/tests/integration/snapshots/integration__user__get_profile.snap
backend/api/tests/integration/snapshots/integration__user__patch_profile.snap
shared/rust/src/domain/user.rs

https://github.com/ji-devs/ji-cloud/issues/2623
`UserProfile`
- `is_oauth` - field returns true if user is signed in with an Oauth email, false if not an Oauth email

feat(be/user/profile): add flag for oauth users

---

frontend/apps/crates/components/src/share_jig/state.rs

closes #2561 
---------------------------------------

feat: set student to true for embed code

---

backend/api/sqlx-data.json
backend/api/src/http/endpoints/user.rs
backend/api/src/service/mail.rs
shared/rust/src/domain/session.rs

closes https://github.com/ji-devs/ji-cloud/issues/2624

feat(be/user/password): send email for OAuth user when attempting to reset password

---

backend/api/sqlx-data.json
backend/api/src/http/endpoints/user.rs

closes https://github.com/ji-devs/ji-cloud/issues/2644
- edited reset queries to compare and insert lower case emails

feat(be/reset/email): omit email address case sensitivity

---

backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap

fix(be/tests): Update browse endpoint snapshot

---

backend/api/sqlx-data.json
backend/api/src/translate.rs

Add-on to PR: https://github.com/ji-devs/ji-cloud/pull/2670

feat(be/translations): remove updated_at condition from query

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/translate.rs

closes https://github.com/ji-devs/ji-cloud/issues/2671
- translate descriptions with google api

feat(be/translations): translate learning path description cron job

---

frontend/apps/crates/components/src/share_jig/dom.rs
frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
frontend/apps/crates/entry/home/src/home/search_results/search_results_section/state.rs
frontend/elements/src/_bundles/home/imports.ts
frontend/elements/src/core/buttons/icon-label.ts
frontend/elements/src/core/buttons/icon.ts
frontend/elements/src/entry/home/home/search-results/search-result.ts

Closes #2651 
- Adds share and edit buttons to search results
- Edit button is only added if the current user is the author of the JIG

feat(fe/jig/search): Add share and edit buttons to search results

---

frontend/apps/crates/components/src/share_jig/dom.rs
frontend/elements/src/core/share-jig/option.ts

Closes #2650
- Adds the "Share to Google Classroom" share option

feat(fe/jig/share): Add Share to Google Classroom share option

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/migrations/20220512003209_algolia-index-setting-hash.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs

closes https://github.com/ji-devs/ji-cloud/issues/2718
Algolia index settings will reset when the index_hash (derived from `hashfn` and stored in db) changes from the current hash of the index setting functions.

feat(be/algolia): update algolia migrations

---

shared/rust/src/domain/jig/module.rs

Part of #2658 
- Adds `ModuleKind::FindAnswer`

feat(shared): Add find-answer ModuleKind

---

backend/api/src/db/jig/module.rs
shared/rust/src/domain/jig/module/body.rs
shared/rust/src/domain/jig/module/body/find_answer.rs
shared/rust/src/domain/jig/module/body/find_answer/play_settings.rs

Part of #2658
- Updates to backend so that it can work with the `ModuleKind::FindAnswer` variant

feat(be/api): Implement FindAnswer so that backend can work with the new module kind

---

backend/pages/src/server/routes.rs
backend/pages/src/templates/spa.rs
frontend/apps/crates/utils/src/routes.rs

- Fixes incorrect routing for JIG play;
- Fixes links generate from share modal.

fix(routes): Fix JIG play routes including share links

---

backend/api/migrations/20220520214249_file-name-translations.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/translate.rs

closes https://github.com/ji-devs/ji-cloud/issues/2425
Helps with Algolia Search results if users are searching for JIGs, Courses, or Media in a different language.

feat(be/algolia/translations): translate display_names for assets

---

backend/api/migrations/20220523181545_badges.sql
backend/api/sqlx-data.json
backend/api/src/db.rs
backend/api/src/db/badge.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/badge.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/image_search.rs
shared/rust/src/api/endpoints.rs
shared/rust/src/api/endpoints/badge.rs
shared/rust/src/domain.rs
shared/rust/src/domain/badge.rs

https://github.com/ji-devs/ji-cloud/issues/2726
- Create
- Update
- Delete
- Get_one
- Join Badge
- Leave Badge
- Browse
- Search 
> Algolia index will be added
- Browse Members

feat(be/badge): add badges to api

---

backend/api/migrations/20220523235708_add-is-public-user.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/tests/integration/snapshots/integration__user__get_profile.snap
backend/api/tests/integration/snapshots/integration__user__patch_profile.snap
backend/api/tests/integration/user.rs
shared/rust/src/domain/user.rs

(1/2) https://github.com/ji-devs/ji-cloud/issues/2727
User's can update new bool fields for their user profile
1. bio
2. organization_public
3. language_public
4. location_public
5. persona_public

feat(be/user/profile): add update-able public flags for profiles

---

frontend/elements/src/core/player-popup/player-popup.ts

fix(fe/jig/play): Fix distorted close button on safari mobile

---

frontend/elements/src/core/page-header/beta-tooltip-content.ts

fix(fe/home): Fix typo in beta popup copy

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
shared/rust/src/domain/asset.rs
shared/rust/src/domain/jig.rs

References https://github.com/ji-devs/ji-cloud/pull/2795
@MendyBerger

refactor(be): Removed jig cover

---

backend/api/src/bin/media-watch.rs
backend/api/src/error.rs
backend/api/src/http.rs
backend/api/tests/integration/jig/module.rs
shared/rust/src/domain/asset.rs

- Adds improved error responses for actix config-related errors;
- Renames the `AssetType` variants to lowercase so that the existing URLs work correctly
- Adds a `strum_macros::Display` implementation so that tests pass.

fix(be): Use lowercase for parsing AssetType; Improve actix config error responses

---

backend/api/sqlx-data.json
backend/api/src/http/endpoints/badge.rs

Logged in users:
UserOrMe::Me => current user id badges
UserOrMe::User => checks if user exists. If so, view user badges
None => browse all badges
Non-token:
UserOrMe::Me => Forbidden
UserOrMe::User => checks if user exists. If so, view user badges
None => browse all badges

feat(be/badge/browse): add optional auth to browse

---

shared/rust/src/domain/module/body/find_answer.rs
shared/rust/src/domain/module/body/find_answer/play_settings.rs

Part of #2658 
- Set up data model for the Find the Answer activity

feat(shared/find-answer): Set up Find the Answer data model

---

backend/api/migrations/20220604010018_add-badge-user-indices.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/db/badge.rs
backend/api/src/db/user.rs
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/badge.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/src/main.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/api/endpoints/badge.rs
shared/rust/src/api/endpoints/user.rs
shared/rust/src/api/endpoints/user/public_user.rs
shared/rust/src/domain/badge.rs
shared/rust/src/domain/user/public_user.rs

closes https://github.com/ji-devs/ji-cloud/issues/2726 
closes https://github.com/ji-devs/ji-cloud/issues/2727

feat(be/search): add update and search functionality for public user and badge

---

backend/api/sqlx-data.json
backend/api/src/db/badge.rs

closes https://github.com/ji-devs/ji-cloud/issues/2838

fix(be/badge/browse): correct page limit parameter in query

---

backend/api/sqlx-data.json
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/user/public_user.rs

@MendyBerger 
- optional auth for browsing following and followers
- Include creator's badges in badge list

feat(be/user/browse): add optional auth to followers and following

---

backend/api/sqlx-data.json
backend/api/src/db/user/public_user.rs

Corrected all deserlization of badges for public users

fix(be/user/public): correctly deserialize vec of Badges

---

backend/api/fixtures/18_badge.sql
backend/api/sqlx-data.json
backend/api/src/db/badge.rs
backend/api/tests/integration/badge.rs
backend/api/tests/integration/fixture.rs
backend/api/tests/integration/main.rs
backend/api/tests/integration/snapshots/integration__badge__browse_badges.snap
backend/api/tests/integration/snapshots/integration__badge__create-2.snap
backend/api/tests/integration/snapshots/integration__badge__create.snap
backend/api/tests/integration/snapshots/integration__badge__join-2.snap
backend/api/tests/integration/snapshots/integration__badge__join.snap
backend/api/tests/integration/snapshots/integration__badge__join_badge-2.snap
backend/api/tests/integration/snapshots/integration__badge__join_badge.snap
backend/api/tests/integration/snapshots/integration__badge__leave-2.snap
backend/api/tests/integration/snapshots/integration__badge__leave.snap
backend/api/tests/integration/snapshots/integration__badge__leave_badge-2.snap
backend/api/tests/integration/snapshots/integration__badge__leave_badge.snap
backend/api/tests/integration/snapshots/integration__badge__update_badge-2.snap
backend/api/tests/integration/snapshots/integration__badge__update_badge.snap
shared/rust/src/domain/badge.rs

https://github.com/ji-devs/ji-cloud/issues/2854
Tests:
- Create badge
- Browse badge
- Update badge
- Join badge
- Leave badge
Fixes: 
- Commit transaction update

chore(be/badge/test): add badge integration tests

---

.github/workflows/frontend-module-elements-sandbox.yml

Part of #2658 
- Includes the elements build for find-answer module in CI

chore(fe/find-answer-ci): Include find-answer in elements CI build

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/db/user/public_user.rs
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_public_user.snap

closes https://github.com/ji-devs/ji-cloud/issues/2875

feat(be/browse): order browse results by newest created at

---

backend/api/fixtures/18_circle.sql
backend/api/sqlx-data.json
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/tests/integration/snapshots/integration__circle__browse_circles.snap
backend/api/tests/integration/snapshots/integration__circle__join_circle-2.snap
backend/api/tests/integration/snapshots/integration__circle__join_circle.snap
backend/api/tests/integration/snapshots/integration__circle__update_circle-2.snap
backend/api/tests/integration/snapshots/integration__circle__update_circle.snap
backend/api/tests/integration/user/public_user.rs
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_public_user.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_users_with_circles.snap
shared/rust/src/domain/circle.rs
shared/rust/src/domain/ser.rs
shared/rust/src/domain/user/public_user.rs

resolves https://github.com/ji-devs/ji-cloud/issues/2891

feat(be/user/browse): add circle filter

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/circle.rs
backend/api/src/db/course.rs
backend/api/src/db/jig.rs
backend/api/src/db/user.rs
backend/api/src/extractor.rs
backend/api/src/http/endpoints/additional_resource.rs
backend/api/src/http/endpoints/circle.rs
backend/api/src/http/endpoints/course.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/jig/curation.rs
backend/api/src/http/endpoints/jig/player.rs
backend/api/src/http/endpoints/module.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/http/endpoints/user/public_user.rs
shared/rust/src/domain/asset.rs
shared/rust/src/domain/circle.rs
shared/rust/src/domain/jig.rs
shared/rust/src/domain/user.rs

closes https://github.com/ji-devs/ji-cloud/issues/1758

refactor(be/user): change to Uuid to UserId

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/db/image/user.rs
backend/api/src/db/session.rs
backend/api/src/db/user.rs
backend/api/src/db/user/public_user.rs
backend/api/src/extractor.rs
backend/api/src/http/endpoints/admin.rs
backend/api/src/http/endpoints/circle.rs
backend/api/src/http/endpoints/image/user.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/session/oauth.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/http/endpoints/user/color.rs
backend/api/src/http/endpoints/user/font.rs
backend/api/src/http/endpoints/user/public_user.rs
shared/rust/src/domain/user.rs
shared/rust/src/domain/user/public_user.rs

resolves https://github.com/ji-devs/ji-cloud/issues/1758
@MendyBerger

refactor(be/user): change Uuid to UserId type

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/http/endpoints/circle.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/tests/integration/circle.rs
backend/api/tests/integration/snapshots/integration__circle__browse_circles.snap
backend/api/tests/integration/snapshots/integration__circle__browse_circles_with_users.snap
shared/rust/src/domain/circle.rs

resolves https://github.com/ji-devs/ji-cloud/issues/2916

feat(be/circle/browse): add users filter

---

frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs

fix(fe/find-answer): Ensure that the cursor is always a pointer while playing

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

fix(fe/find-answer): Ensure continue button works on all steps

---

backend/api/sqlx-data.json
backend/api/src/db/user/public_user.rs
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_following_and_unfollow.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_public_user.snap
shared/rust/src/domain/user/public_user.rs

- Deserialization of persona in sql query
- Pagination with `array_agg`

fix(be/public_user): deser personas and new pagination

---

frontend/apps/crates/entry/admin/src/curation/actions.rs
frontend/apps/crates/entry/admin/src/curation/state.rs
frontend/apps/crates/entry/admin/src/curation/table/dom.rs
frontend/elements/src/_bundles/admin/imports.ts
frontend/elements/src/entry/admin/curation/order-by.ts
frontend/elements/src/entry/admin/curation/pagination.ts
frontend/elements/src/entry/admin/curation/table.ts
shared/rust/src/domain/asset.rs

Part of #2850 
- Renames "Date" column to "Last published";
- Updates the pagination controls so that they use existing app elements and fa icons;
- Adds a "Sort by" control to sort JIGs by created_at or published_at;
- Neatens up the curation controls a bit.

feat(fe/admin): Include sorting and neaten up the table controls a bit

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/tests/integration/jig.rs
backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
backend/api/tests/integration/snapshots/integration__jig__browse_order_by-2.snap
backend/api/tests/integration/snapshots/integration__jig__browse_order_by-3.snap
backend/api/tests/integration/snapshots/integration__jig__browse_order_by.snap
backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
backend/api/tests/integration/snapshots/integration__jig__clone.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
backend/api/tests/integration/snapshots/integration__jig__get-2.snap
backend/api/tests/integration/snapshots/integration__jig__get.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_user_jigs.snap
shared/rust/src/domain/jig.rs

Part of #2852
- Adds the `created_at` field to `JigData`

feat(be): Add created_at to JigResponse

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/tests/integration/course.rs
backend/api/tests/integration/snapshots/integration__circle__browse_circles.snap
backend/api/tests/integration/snapshots/integration__circle__browse_circles_with_users.snap

- sql query for circle browse uses `array_agg` instead of `array` to remove duplicate circle responses

fix(be/circle): rm duplicate circles in browse

---

frontend/apps/crates/entry/module/find-answer/play/src/base/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs

Part of #2947
- Plays the activity instructions before starting the activity's first question.

fix(fe/find-answer): Play instructions before starting to play the activity

---

backend/api/migrations/20220720182634_add-index-course-jigs.sql
backend/api/sqlx-data.json
backend/api/src/db/course.rs
backend/api/tests/integration/course.rs
backend/api/tests/integration/snapshots/integration__course__jig_index-2.snap
backend/api/tests/integration/snapshots/integration__course__jig_index-3.snap
backend/api/tests/integration/snapshots/integration__course__jig_index-4.snap
backend/api/tests/integration/snapshots/integration__course__jig_index.snap

https://github.com/ji-devs/ji-cloud/issues/2960
- migration 
> - add indexes to existing jigs associated with courses
> - add procedure and trigger that increment jig indexes
- `order by "index"` in Course browse query

fix(be/course): add indexes to courses' jigs

---

backend/api/sqlx-data.json
backend/api/src/db/course.rs
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/http/endpoints/user/public_user.rs

- move `get` public user route in configure list (actix web rules)
- refactor `get` public user sqlx query to user `sqlx::query!()` instead of `sqlx::query_as!( PublicUser, ...)`

fix(be/public_user): displace get_user route in configure list and change sqlx macro

---

backend/api/fixtures/19_public_user.sql
backend/api/fixtures/1_user.sql
backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/tests/integration/snapshots/integration__user__get_profile.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_public_user.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_users_with_circles.snap

fix(be/public_user): fix browse public user and count

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

- Adds support for Jiggling text

feat(fe/find-answer): Enable Jiggling text

---

backend/api/sqlx-data.json
backend/api/src/db/course.rs
backend/api/src/http/endpoints/user/public_user.rs

- items deserialized to `Vec<(JigId,)>` instead of `Vec<JigId>`

fix(be/course): tuple JigId in query

---

backend/api/sqlx-data.json
backend/api/src/db/course.rs
shared/rust/src/domain/course.rs

resolves https://github.com/ji-devs/ji-cloud/issues/2988

chore(be/course): Uuid to UserId

---

frontend/elements/src/module/_common/types.ts
shared/rust/src/domain/module.rs
shared/rust/src/domain/module/body.rs
shared/rust/src/domain/module/body/find_answer.rs

chore(fe/find-answer): Rename 'Find the Answer' to 'Answer This'

---

backend/api/sqlx-data.json
backend/api/src/db/user/public_user.rs
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow.snap

@MendyBerger 
- omit array function, for persona, when fetching persona

fix(be/public_user): user persona in query

---

frontend/apps/Cargo.lock
frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/find-answer/play/Cargo.toml
frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
frontend/elements/src/module/_common/edit/widgets/settings/button.ts

feat(fe/find-answer): Implement activity settings

---

backend/api/migrations/20220801205937_existing-course-jigs-index.sql
backend/api/sqlx-data.json
backend/api/src/db.rs
backend/api/src/db/course.rs
backend/api/tests/integration/course.rs
backend/api/tests/integration/snapshots/integration__course__course_jig_index-2.snap
backend/api/tests/integration/snapshots/integration__course__course_jig_index-4.snap

- Redo trigger and function from `migrations/20220720182634_add-index-course-jigs.sql`

fix(be/course): replace trigger and function for Course Jigs 

---

frontend/apps/crates/components/src/stickers/actions.rs
frontend/apps/crates/components/src/stickers/callbacks.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs

fix(fe/find-answer): Fix invalidated sticker index

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/dom.rs

fix(fe/find-answer): Ensure that instructions player content is visible

---

frontend/elements/src/module/tapping-board/edit/interaction-label.ts

Resolves https://github.com/ji-devs/ji-cloud/issues/2976#issuecomment-1211723353
- Removes unnecessary styling around the textarea which caused an alignment issue in Chrome

fix(fe/tapping-board): Fix interaction label field alignment in Chrome-based browsers

---

backend/api/sqlx-data.json
backend/api/src/db/course.rs

Resolves #3051
- Adds the `ORDER BY ord` statement so that IDs and data can be zipped correctly.

fix(be/courses): Add order statement to search SQL

---

frontend/elements/src/module/_common/edit/sidebar-body.ts

fix(fe/module/edit): Remove extra padding for larger screen sizes in the module edit sidebar

---

backend/api/src/http/endpoints/jig/report.rs
backend/api/src/service/mail.rs
backend/api/tests/integration/service.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/config.rs

- email for Jigzi info has been moved to secrets

chore(be): mv info email to secrets

---

shared/rust/src/config.rs

Removes unused function from https://github.com/ji-devs/ji-cloud/pull/3075

chore(be): remove unused info_email

---

frontend/elements/src/module/_common/edit/widgets/lists/dual/dual-list.ts
frontend/elements/src/module/_common/edit/widgets/lists/single/single-list.ts

chore(fe/card-games): Remove word limit copy from word lists

---

backend/api/sqlx-data.json
backend/api/src/error.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/tests/integration/user/public_user.rs
shared/rust/src/domain/jig.rs

resolves https://github.com/ji-devs/ji-cloud/issues/3080
Changed 500 error to 400 error.

fix(be/public_user): 400 error when user follows self

---

frontend/apps/crates/entry/module/cover/edit/src/debug.rs
frontend/apps/crates/entry/module/cover/play/src/debug.rs
frontend/apps/crates/entry/module/find-answer/play/src/debug.rs
frontend/apps/crates/entry/module/poster/edit/src/debug.rs
frontend/apps/crates/entry/module/poster/play/src/debug.rs
frontend/apps/crates/entry/module/resource-cover/edit/src/debug.rs
frontend/apps/crates/entry/module/resource-cover/play/src/debug.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/debug.rs
frontend/apps/crates/entry/module/tapping-board/play/src/debug.rs
frontend/apps/crates/entry/module/video/edit/src/debug.rs
frontend/apps/crates/entry/module/video/play/src/debug.rs

Part of https://github.com/ji-devs/ji-cloud/issues/2924
- Fixes broken CI caused by #3086

chore(fe): Add default feedback to debug activity debug settings

---

frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs

Part of #2924 
- Adds feedback when playing the Answer This activity

feat(fe/find-answer): Add feedback to Answer This player

---

backend/api/migrations/20220826000458_circle-image-option.sql
backend/api/sqlx-data.json

https://github.com/ji-devs/ji-cloud/pull/3106
migration to set image to not null

fix(be/circle): set image to not null in db

---

backend/api/sqlx-data.json
backend/api/src/db/jig.rs
backend/api/src/db/resource.rs

https://github.com/ji-devs/ji-cloud/issues/3114
- Add `order by ord asc` in `get_by_ids` sql resource queries.

fix(be/resource): sync resource with data in search

---

frontend/apps/crates/components/src/stickers/sprite/dom.rs
frontend/apps/crates/components/src/stickers/text/dom.rs

fix(fe/drag-drop): Ensure that all stickers can not be selected when students attempt to drag them

---

frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs

feat(fe/find-answer): Play positive feedback effect for every correct trace selected

---

shared/rust/src/domain/module/body/find_answer.rs

Closes #3128
- Removes the requirement for question text/audio.

feat(fe/find-answer): Only require answer traces for questions

---

frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_2/custom_background/state.rs

fix(fe/card-games): Ensure background color is set correctly

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
shared/rust/src/domain/module/body/find_answer.rs

chore(fe/find-answer): Rename Answer This use cases

---

frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_3/dom.rs

chore(fe/drag-drop): Update Interaction step Select tab graphic

---

shared/rust/src/domain/user.rs

- Fixes an issue preventing exports from admin panel.

fix(shared): Fix serialization of language lists for users when exporting

---

frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
shared/rust/src/domain/module/body/drag_drop/play_settings.rs

Part of https://github.com/ji-devs/ji-cloud/issues/3142
- Includes `cargo fmt` changes

chore(fe/drag-drop): Change hint default to not highlight traces

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/http/endpoints/circle.rs

closes https://github.com/ji-devs/ji-cloud/issues/3149
- replaces `authz()` with `is_author()`, which checks if signed in user is author of circle.

feat(be/circle): restrict update and delete to author

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/admin.rs
frontend/apps/crates/entry/admin/src/export/dom.rs
frontend/apps/crates/entry/admin/src/export/state.rs
shared/rust/src/domain/admin.rs

Part of #3006
- Adds new option for filter by new records, updated records or both

feat(admin): Add date filter type option to admin export functionality

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
shared/rust/src/domain/user.rs

Closes #3006
- Adds user opt-in field to the csv export

feat(admin/export): Add opt-in field to user export

---

frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs

fix(fe/settings): Ensure bubble works for always-enabled settings

---

backend/api/migrations/20220914090552_move-youtube-url.sql
frontend/apps/crates/components/src/stickers/video/dom.rs
frontend/apps/crates/entry/module/legacy/play/src/base/activities/video/dom.rs
frontend/apps/crates/entry/module/video/edit/src/base/sidebar/step_2/video/dom.rs
frontend/apps/crates/entry/module/video/play/src/debug.rs
shared/rust/src/domain/module/body/_groups/design.rs
shared/rust/src/domain/module/body/legacy/activity.rs

@johnnynotsolucky ready for migrations

refactor(shared): Moved Video YouTube to separate struct

---

frontend/apps/crates/components/src/audio/input/components/main_content.rs
frontend/apps/crates/components/src/file_input/config.rs
frontend/apps/crates/components/src/file_input/dom.rs
frontend/apps/crates/components/src/page_header/dom.rs
frontend/apps/crates/entry/home/src/home/actions.rs
frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
frontend/apps/crates/utils/src/component.rs

feat(fe/mixpanel): Add mixpanel events to home entry crate

---

frontend/apps/crates/entry/community/src/dom.rs

feat(fe/mixpanel): Add mixpanel events to community entry crate

---

frontend/apps/crates/entry/community/src/dom.rs
frontend/apps/crates/entry/jig/play/src/jig/dom.rs
frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/info.rs
frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/like.rs
frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/mod.rs
frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/share.rs

feat(fe/mixpanel): Add mixpanel events to jig/play entry crate

---

frontend/apps/crates/components/src/module/_common/edit/post_preview/dom.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/spot/dom.rs
frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs

feat(fe/mixpanel): Add mixpanel events to jig/edit entry crate

---

frontend/apps/crates/components/src/module/_common/edit/post_preview/dom.rs
frontend/apps/crates/components/src/page_header/dom.rs
frontend/apps/crates/entry/community/src/dom.rs
frontend/apps/crates/entry/home/src/home/actions.rs
frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/mod.rs
frontend/apps/crates/entry/jig/edit/src/edit/sidebar/spot/dom.rs
frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
frontend/apps/crates/entry/jig/play/src/jig/dom.rs
frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/mod.rs
frontend/apps/crates/utils/src/init.rs
frontend/apps/crates/utils/src/init/analytics/mixpanel.rs
frontend/apps/crates/utils/src/init/analytics/mod.rs

chore(fe/analytics): Update mixpanel so that it uses a common analytics api

---

frontend/elements/src/module/_groups/cards/helpers.ts

fix(fe/matching): Prevent background colour from changing when dragging a card

---

frontend/apps/crates/components/src/instructions/editor/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/dom.rs
frontend/apps/crates/entry/asset/play/src/jig/dom.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/dom.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/dom.rs
frontend/apps/crates/entry/module/video/edit/src/base/sidebar/step_3/dom.rs
frontend/elements/src/core/overlays/tooltip/container.ts
frontend/elements/src/core/overlays/tooltip/info.ts
frontend/elements/src/entry/asset/play/jig/landing.ts

Closes #2482 
- Adds instruction/feedback button icons;
- Increases font size;
- Changes font colour;
- Increases size of popup;
- Adds Hebrew keyboard to the instructions/feedback input fields.

feat(fe/instructions): Improve instructions/feedback popup layout and styling

---

frontend/apps/crates/components/src/stickers/actions.rs
frontend/apps/crates/components/src/stickers/sprite/menu/dom.rs
frontend/apps/crates/components/src/stickers/text/menu/dom.rs
frontend/apps/crates/components/src/stickers/video/menu/dom.rs
frontend/elements/src/core/menu/menu-line.ts

feat(fe/stickers): Add move to front and move to back menu options for stickers

---

frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/preview.rs
frontend/elements/src/module/_common/edit/preview-body.ts

chore(fe/edit): Update preview screen copy

---

shared/macros/src/lib.rs

RE https://github.com/ji-devs/ji-cloud/pull/3300#issuecomment-1293504579

chore(shared/macros): Document test_service argument macro

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

feat(fe/find-answer): Add Hebrew keyboard to the question text field

---

frontend/apps/crates/components/src/instructions/editor/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/publish/pre_publish/dom/mod.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_3/dom.rs
frontend/elements/src/core/overlays/tooltip/info.ts
frontend/elements/src/module/find-answer/question-banner.ts

fix(fe): Make some inputs and display elements detect correct text direction

---

frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_2/dom.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_2/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/actions.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/state.rs
frontend/apps/crates/entry/module/poster/play/src/base/dom.rs
frontend/apps/crates/entry/module/poster/play/src/base/state.rs
shared/rust/src/domain/module/body/poster.rs

feat(fe/poster): Update steps; include audio content

---

frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_2/actions.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_2/mod.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_2/state.rs

fix(fe/poster): Ensure poster audio is actually set when editing

---

frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/dom.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/mod.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_2/actions.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_2/state.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/actions.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/mod.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/cover/edit/src/base/state.rs
frontend/apps/crates/entry/module/cover/play/src/base/dom.rs
frontend/apps/crates/entry/module/cover/play/src/base/state.rs
shared/rust/src/domain/module/body/cover.rs

feat(fe/cover): Add instructions tab; Add audio field

---

frontend/elements/src/module/_common/edit/widgets/settings/button.ts

fix(fe/widgets/settings): Use correct font-size and active color for settings label

---

frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/dom.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/elements/src/module/_common/edit/widgets/settings/button.ts
frontend/elements/src/module/_common/edit/widgets/settings/line.ts

- also updates "Student finishes this activity by..." to "Student views this page until…" and "clicking on continue" to "clicking next"

chore(fe/module/edit): Ensure default module settings are always on the left

---

frontend/elements/src/module/_groups/cards/_common/main-empty.ts

chore(fe/module/edit): Update empty content warning

---

frontend/elements/src/entry/user/profile/landing.ts

resolves https://github.com/ji-devs/ji-cloud/issues/3398
- In `landing.rs`, changed `STR_MY_PROFILE = "My Profile"` to `STR_MY_SETTINGS = "My Settings"`.

fix(fe/user/settings): change 'My Profile' to 'My Settings'

---

frontend/apps/crates/components/src/page_header/dom.rs

https://github.com/ji-devs/ji-cloud/issues/3368
1. Hyperlink to community profile of current user
2. User icon: `fa-light fa-user`

feat(fe/components): add hyperlink to my profile to user dropdown menu

---

backend/api/migrations/20221201072318_timer-minutes-to-seconds.sql
frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
frontend/apps/crates/components/src/module/_common/play/entry/state.rs
frontend/apps/crates/entry/module/card-quiz/edit/src/config.rs
frontend/apps/crates/entry/module/card-quiz/play/src/base/state.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/config.rs
frontend/apps/crates/entry/module/drag-drop/play/src/base/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
frontend/apps/crates/entry/module/matching/edit/src/config.rs
frontend/apps/crates/entry/module/matching/play/src/base/state.rs
frontend/apps/crates/entry/module/memory/edit/src/config.rs
frontend/apps/crates/entry/module/memory/play/src/base/state.rs
frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts
frontend/elements/src/module/_common/edit/widgets/settings/button.ts

feat(fe/timer): Convert timer setting minutes to seconds

---

frontend/apps/crates/components/src/module/_groups/cards/edit/main/dom.rs
frontend/apps/crates/entry/asset/play/src/jig/dom.rs
frontend/elements/src/module/_groups/cards/_common/main-empty.ts

fix(fe/cards): Use correct message when editing an empty card activity

---

frontend/apps/crates/components/src/stickers/dom.rs
frontend/apps/crates/utils/src/keyboard.rs

fix(fe/stickers): Enable sticker deletion on OSX

---

frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
frontend/apps/crates/entry/module/flashcards/edit/src/debug.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/actions.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/dom.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/state.rs
frontend/apps/crates/entry/module/flashcards/edit/src/state.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/dom.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/game/actions.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/game/state.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/state.rs
frontend/apps/crates/entry/module/flashcards/play/src/debug.rs
frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts
frontend/elements/src/module/_common/edit/widgets/settings/button.ts
shared/rust/src/domain/module/body/flashcards.rs

feat(fe/flashcards): Add ending settings to flashcards module

---

frontend/elements/src/module/_groups/cards/edit/print/double.ts
frontend/elements/src/module/_groups/cards/edit/print/single.ts

https://github.com/ji-devs/ji-cloud/issues/3304

fix(fe/edit/print): remove extra Jigzi text from print

---

frontend/apps/crates/components/src/module/_common/edit/jig/post_preview/print/screenshot.rs

resolves https://github.com/ji-devs/ji-cloud/issues/3304

fix(fe/print): add new logo to covers

---

frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
frontend/apps/crates/components/src/module/_common/play/entry/ending/dom.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/play_settings/actions.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/play_settings/dom.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/play_settings/mod.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/play_settings/state.rs
frontend/apps/crates/entry/module/cover/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/cover/edit/src/base/state.rs
frontend/apps/crates/entry/module/cover/play/src/base/dom.rs
frontend/apps/crates/entry/module/cover/play/src/base/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/mod.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/play_settings/actions.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/play_settings/dom.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/play_settings/mod.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/play_settings/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/state.rs
frontend/apps/crates/entry/module/poster/play/src/base/dom.rs
frontend/apps/crates/entry/module/poster/play/src/base/state.rs
frontend/elements/src/core/overlays/tooltip/info.ts
frontend/elements/src/module/_common/edit/widgets/settings/button.ts
shared/rust/src/domain/module/body/cover.rs
shared/rust/src/domain/module/body/poster.rs

Closes #3284
Closes #3285
- Resolves issue where card games were not moving on to the next activity correctly.

feat(fe/cover|poster): Adding 'next' play setting

---

frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
frontend/apps/crates/entry/module/poster/play/src/base/dom.rs
frontend/apps/crates/entry/module/poster/play/src/base/state.rs
frontend/apps/crates/entry/module/video/edit/src/base/sidebar/step_3/play_settings/dom.rs
frontend/elements/src/module/_common/edit/widgets/settings/button.ts
shared/rust/src/domain/module/body/video.rs

feat(fe/video): Switch autoplay to default to true; Change button to disable autoplay instead

---

frontend/apps/crates/entry/module/card-quiz/edit/src/config.rs
frontend/apps/crates/entry/module/card-quiz/edit/src/settings/sidebar/actions.rs
frontend/apps/crates/entry/module/card-quiz/edit/src/settings/sidebar/dom.rs
frontend/apps/crates/entry/module/card-quiz/edit/src/settings/state.rs
frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts
shared/rust/src/domain/module/body/card_quiz.rs

chore(fe/card-quiz): Remove attempts settings; Update copy

---

frontend/elements/src/entry/user/login/pages/landing.ts
frontend/elements/src/entry/user/register/pages/start.ts

https://github.com/ji-devs/ji-cloud/issues/3446

feat(fe/user): add jigzi logo to login and register page

---

frontend/apps/crates/entry/module/memory/edit/src/settings/sidebar/actions.rs
frontend/apps/crates/entry/module/memory/edit/src/settings/sidebar/dom.rs
frontend/apps/crates/entry/module/memory/edit/src/settings/state.rs

feat(fe/memory): Update memory activity settings

---

backend/api/migrations/20221220084940_drop_tapping_board_select_some_option.sql
frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/play_settings/actions.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/state.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/config.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/lib.rs
frontend/apps/crates/entry/module/tapping-board/play/src/base/game/playing/actions.rs
shared/rust/src/domain/module/body/tapping_board/play_settings.rs

feat(fe/tapping-board): Remove SelectSome() setting option

---

frontend/apps/crates/components/src/traces/show/dom.rs
frontend/apps/crates/components/src/traces/show/state.rs
frontend/apps/crates/entry/module/tapping-board/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/tapping-board/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/tapping-board/play/src/base/game/playing/state.rs

feat(fe/tapping-board): Only highlight tapped traces while audio is playing

---

frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/play_settings/actions.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/base/state.rs
frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/drag-drop/play/src/base/state.rs
frontend/apps/crates/entry/module/drag-drop/play/src/config.rs
frontend/apps/crates/entry/module/drag-drop/play/src/debug.rs
shared/rust/src/domain/module/body/drag_drop/play_settings.rs

feat(fe/drag-drop): Re-order timer setting; remove continue setting; Decrease hint time

---

frontend/elements/src/entry/home/home/search-results/search-result.ts

resolve https://github.com/ji-devs/ji-cloud/issues/3485

style(fe/home/search): increase margin and change color for scrollbar

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs

feat(fe/find-answer): Add optional hints after a student has clicked an incorrect choice

---

frontend/elements/src/module/_groups/cards/play/card/empty.ts

feat(fe/matching): Empty card content colour should be the same as the current theme's colour

---

frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs

feat(fe/card-quiz): Negative feedback for wrong choices instead of flip sound

---

frontend/elements/src/entry/home/home/search-results/search-result.ts

fix(fe/home): Auto-align copy in search results

---

frontend/apps/crates/entry/module/legacy/play/src/base/actions.rs
frontend/apps/crates/entry/module/legacy/play/src/base/activities/say_something/dom.rs
frontend/apps/crates/entry/module/legacy/play/src/base/design/sticker/animation/actions.rs
frontend/apps/crates/entry/module/legacy/play/src/base/design/sticker/animation/dom.rs
frontend/apps/crates/entry/module/legacy/play/src/base/design/sticker/image/actions.rs
frontend/apps/crates/entry/module/legacy/play/src/base/design/sticker/image/dom.rs
frontend/apps/crates/entry/module/legacy/play/src/base/state.rs
frontend/apps/crates/entry/module/legacy/play/src/base/styles.rs

Fixes:
* https://github.com/ji-devs/ji-cloud/issues/3311
* https://github.com/ji-devs/ji-cloud/issues/3464
* https://github.com/ji-devs/ji-cloud/issues/3469

Legacy player fixes

---

frontend/apps/crates/components/src/share_asset/dom.rs
frontend/elements/src/core/share-jig/option.ts

feat(fe/share): Add 'Share to Microsoft Teams' option to share popup

---

frontend/elements/src/core/page-header/page-header-link.ts

https://github.com/ji-devs/ji-cloud/issues/3031

style(fe/home): restyle page header links

---

frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_2/custom_background/dom.rs
frontend/apps/crates/components/src/module/_groups/design/edit/theme_background/custom_background/dom.rs
frontend/apps/crates/components/src/tabs/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
frontend/elements/src/_bundles/_sub-bundles/module/_groups/cards/edit.ts
frontend/elements/src/_bundles/_sub-bundles/module/_groups/design/edit.ts
frontend/elements/src/core/buttons/rectangle.ts
frontend/elements/src/core/menu/menu-tabs/menu-tab-title.ts
frontend/elements/src/module/_common/edit/widgets/advanced-modal.ts
frontend/elements/src/module/find-answer/sidebar/question.ts
shared/rust/src/domain/module/body/find_answer.rs

feat(fe/find-answer): Add advanced config section to questions

---

frontend/apps/crates/components/src/stickers/dom.rs
frontend/apps/crates/components/src/stickers/text/dom.rs
frontend/apps/crates/components/src/stickers/text/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/main/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
frontend/elements/src/_bundles/_sub-bundles/module/_groups/design/edit.ts
frontend/elements/src/module/_common/edit/widgets/transform/highlight.ts

feat(fe/find-answer): Highlight question sticker with a separate highlight box

---

backend/api/migrations/20230123221703_add-user-hash.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/db/user.rs
backend/api/src/http/endpoints/user.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
shared/rust/src/api/endpoints/user.rs
shared/rust/src/domain/user.rs

https://github.com/ji-devs/ji-cloud/issues/3480
Backend implementation:
The following are only endpoints accessible to admin:
- Browse User 
- Search User

feat(be/user): add browse and search endpoints

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
shared/rust/src/domain/user.rs

references https://github.com/ji-devs/ji-cloud/pull/3580
Frontend requires user id

feat(be/user): add id to search and browse response

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/state.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs

Closes #3562
@corinnewo @GaliShapira :
- The dropdown has a text alignment issue when there is no label present. This is related to the dropdown component itself and should be resolved separately.
- The dropdown also shifts when opening/closing. this is related to the thicker border applied when the dropdown is open. It should also be resolved separately.
- Doesn't include styling updates from #3543
- Excludes the textbox for captions (discussed with @corinnewo)

feat(fe/find-answer): Merged correct/incorrect tabs for advanced feedback

---

backend/api/migrations/20230126232241_remove-raw-location.sql
backend/api/sqlx-data.json
backend/api/src/db/user.rs

references PR https://github.com/ji-devs/ji-cloud/pull/3588
- remove `raw` field in location with migration so city, state, country can being detected
- fix browse response and count

fix(be/user): correct user responses and count

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/elements/src/module/find-answer/sidebar/question.ts

- Resolves #3577
- Resolves #3578

fix(fe/find-answer): Align pencil next to kebab, and both to the top of box

---

frontend/apps/crates/entry/asset/play/src/jig/dom.rs

feat(fe/instructions): Always show popup for instructions assist

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/state.rs

feat(fe/find-answer): Add correct/incorrect tabs for Jigzi help popups

---

backend/api/migrations/20230130210949_clone-course.sql
backend/api/sqlx-data.json
backend/api/src/db/course.rs
backend/api/src/http/endpoints/course.rs
backend/api/tests/integration/snapshots/integration__course__browse_simple.snap
shared/rust/src/api/endpoints/course.rs
shared/rust/src/domain/course.rs

resolves https://github.com/ji-devs/ji-cloud/issues/3599

feat(be/course): add clone

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/main/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/elements/src/module/find-answer/sidebar/questions-empty.ts
shared/rust/src/domain/module/body/find_answer.rs

fix(fe/find-answer): Updates to add question logic; Default stickers

---

backend/api/tests/integration/resource.rs
backend/api/tests/integration/snapshots/integration__resource__update_privacy_level-1.snap
backend/api/tests/integration/snapshots/integration__resource__update_privacy_level-2.snap
backend/api/tests/integration/snapshots/integration__resource__update_privacy_level-3.snap

https://github.com/ji-devs/ji-cloud/issues/3607
- integration to test for updating private to unlisted

chore(be/resource): add test for updating privacy level

---

shared/rust/src/domain/user.rs

- Change `UserLookup` path from `GET v1/user` to `GET v1/user/lookup`

fix(be/user): change UserLookup path

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

fix(fe/find-answer): Limit question title text; Use sticker text when question text is empty

---

frontend/apps/crates/components/src/text_editor/dom/text_editor_controls/text_editor_controls.rs
frontend/apps/crates/components/src/text_editor/dom/wysiwyg.rs
frontend/apps/crates/components/src/text_editor/wysiwyg_types.rs
frontend/elements/src/core/inputs/primitives/textarea-content.ts
frontend/elements/src/core/wysiwyg/slate-wysiwyg-react/EditorBackbone.ts
frontend/elements/src/core/wysiwyg/slate-wysiwyg-react/Element.ts
frontend/elements/src/core/wysiwyg/styles.ts
frontend/elements/src/core/wysiwyg/wysiwyg-output-renderer.ts
frontend/elements/src/core/wysiwyg/wysiwyg-types.ts
frontend/elements/src/module/_common/edit/widgets/lists/dual/dual-list-input.ts
frontend/elements/src/module/_common/edit/widgets/lists/single/single-list-input.ts
frontend/elements/src/module/_common/edit/widgets/text-editor-controls/text-editor-controls.ts
frontend/elements/src/module/_groups/cards/play/card/text.ts

feat(fe/text-editor): Auto dir

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

fix(fe/find-answer): Update advanced section image and copy; Always render in traces mode

---

frontend/apps/crates/components/Cargo.toml
frontend/apps/crates/components/src/lib.rs
frontend/apps/crates/components/src/page_header/dom.rs
frontend/apps/crates/entry/home/src/help_center/dom.rs
frontend/apps/crates/entry/home/src/help_center/mod.rs
frontend/apps/crates/entry/home/src/lib.rs
frontend/apps/crates/entry/home/src/router.rs
frontend/apps/crates/utils/src/routes.rs
frontend/elements/src/_bundles/home/imports.ts
frontend/elements/src/core/buttons/hover-circle.ts
frontend/elements/src/core/buttons/icon.ts
frontend/elements/src/core/page-header/help-button.ts
frontend/elements/src/core/page-header/page-header.ts
frontend/elements/src/entry/home/home/help-center.ts

https://github.com/ji-devs/ji-cloud/issues/3484
- Help Icon on page header
- iframe for JI Help center

feat(fe/home): add help center and iframe

---

frontend/apps/crates/components/src/module/_groups/cards/edit/state.rs
frontend/elements/src/module/_groups/cards/edit/main/card-pair/card.ts

fix(fe/cards): Always allow step change unless from step 1 and invalid; Fix card audio icon position

---

frontend/apps/crates/entry/admin/src/users/actions.rs
frontend/apps/crates/entry/admin/src/users/state.rs
frontend/apps/crates/entry/admin/src/users/table/actions.rs
frontend/apps/crates/entry/admin/src/users/table/dom.rs
frontend/apps/crates/entry/admin/src/users/table/state.rs

https://github.com/ji-devs/ji-cloud/issues/3480
- reveal user count on Search

feat(fe/admin): add user count

---

frontend/apps/crates/components/src/module/_common/edit/entry/base/actions.rs
frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs
frontend/apps/crates/components/src/module/_common/edit/entry/base/state.rs
frontend/apps/crates/components/src/module/_groups/cards/edit/state.rs
frontend/apps/crates/entry/module/cover/edit/src/base/state.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/base/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/state.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
frontend/apps/crates/entry/module/poster/edit/src/base/state.rs
frontend/apps/crates/entry/module/resource-cover/edit/src/base/state.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/base/state.rs
frontend/apps/crates/entry/module/video/edit/src/base/state.rs

feat(fe/find-answer): Add validation and alert when questions are set up correctly

---

backend/api/sqlx-data.json
backend/api/src/db/pro_dev/unit.rs
backend/api/src/http/endpoints/pro_dev/unit.rs
backend/api/tests/integration/pro_dev/unit.rs
shared/rust/src/api/endpoints/pro_dev/unit.rs
shared/rust/src/domain/pro_dev/unit.rs

- Create unit does not take in a json body

fix(be/pro-dev): create pro-dev without fields

---

frontend/apps/crates/components/src/traces/svg/mixins.rs

fix(fe/svg): Prevent trace stroke width from scaling with trace

---

backend/api/src/algolia.rs
backend/api/src/algolia/migration.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/resource.rs
shared/rust/src/domain/jig.rs
shared/rust/src/domain/resource.rs

https://github.com/ji-devs/ji-cloud/issues/3688

feat(be/asset): add rating to JIG and Resource Search

---

shared/rust/src/domain/billing.rs

chore(be/billing): Update payment method model

---

backend/api/src/algolia.rs
shared/rust/src/domain/jig.rs
shared/rust/src/domain/resource.rs

https://github.com/ji-devs/ji-cloud/issues/3688
- Added `IsRated` and `isNotRated` to Algolia based on existence of rating

feat(be/asset): add is_rated tags to JIG and Resource Search

---

frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs

fix(fe/find-answer): Don't set question title when creating first question

---

backend/api/src/algolia/migration.rs

- switch `PUBLIC_USER_HASH` and `PUBLIC_USER_INDEX` to `USER_HASH` and `USER_INDEX`

fix(be/algolia): user_hash

---

backend/api/Cargo.lock
backend/pages/Cargo.lock
frontend/apps/Cargo.lock
frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
frontend/apps/crates/components/src/module/_groups/cards/lookup.rs
frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/common.rs
frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/dom.rs
frontend/apps/crates/entry/module/card-quiz/edit/src/settings/main/dom.rs
frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
frontend/apps/crates/entry/module/flashcards/edit/src/settings/main/dom.rs
frontend/apps/crates/entry/module/flashcards/play/src/base/game/dom.rs
frontend/apps/crates/entry/module/matching/edit/src/settings/main/dom.rs
frontend/apps/crates/entry/module/matching/play/src/base/game/card/dom.rs
frontend/apps/crates/entry/module/matching/play/src/base/game/dom.rs
shared/rust/Cargo.toml
shared/rust/src/domain/module/body/_groups/cards.rs

fix(fe/cards): Make sure that card text sizes match all cards

---

frontend/apps/crates/entry/admin/src/jig_curation/table/dom.rs
frontend/apps/crates/entry/admin/src/users/table/dom.rs

https://github.com/ji-devs/ji-cloud/issues/3753
- gave curation and user pagination width of `150px` in `input-select`

fix(fe/admin): increase pagination dropdown width for curation and user

---

frontend/elements/src/entry/asset/play/course/course-item.ts
frontend/elements/src/entry/asset/play/course/course-main.ts

chore(fe/courses): Auto-align course item name and description

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/migrations/20230315060912_user-profile-billing-info.sql
backend/api/sqlx-data.json
backend/api/src/db/billing.rs
backend/api/src/db/user.rs
backend/api/src/error.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/billing.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/http/endpoints/user.rs
backend/api/tests/integration/helpers.rs
backend/core/src/env/keys.rs
backend/core/src/settings.rs
backend/pages/Cargo.lock
shared/rust/Cargo.toml
shared/rust/src/api/endpoints/admin.rs
shared/rust/src/api/endpoints/billing.rs
shared/rust/src/domain/billing.rs
shared/rust/src/domain/user.rs

feat(be/billing): Create subscription endpoint

---

backend/api/src/http/endpoints/billing.rs
shared/rust/src/api/endpoints/billing.rs
shared/rust/src/domain/billing.rs

feat(be/billing): Add endpoint for creating a Stripe setup intent

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/src/http/endpoints/billing.rs
shared/rust/src/domain/user.rs

feat(be): Include subscription in user profile response

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs

https://github.com/ji-devs/ji-cloud/issues/3752
- In User browse, `order by "user".family_name desc` -> `order by "user".created_at desc`

feat(be/admin/user): sort users by most recent signup dates

---

backend/api/migrations/20230330002137_lowercase_emails.sql
backend/api/sqlx-data.json
backend/api/src/http/endpoints/session/oauth.rs
backend/api/src/http/endpoints/user.rs
backend/api/src/token.rs

https://github.com/ji-devs/ji-cloud/issues/2644
- migration to lowercase all emails in `user_email` and `user_auth_basic` tables
- lowercase user email inputs

fix(be/user): lowercase emails in db & user inputs

---

backend/api/src/extractor.rs

https://github.com/ji-devs/ji-cloud/issues/2644
- EmailBasicUser `from_request()`, converts email characters to lowercase to match those in db

fix(be/session): add non-case-sensitive login 

---

backend/api/sqlx-data.json
backend/api/src/db/pro_dev/unit.rs

- query to get draft id on create

fix(be/unit): correct index on create

---

frontend/apps/crates/components/src/collision/stickers_traces/pixels.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/actions.rs
frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs

feat(fe/drag-drop): Center first sticker inside trace; Snap sticker to correct position

---

frontend/apps/crates/entry/community/src/circle_details/dom.rs
frontend/apps/crates/entry/community/src/circle_details/edit_about/dom.rs
frontend/apps/crates/entry/community/src/circle_details/edit_name/dom.rs
frontend/apps/crates/entry/community/src/circle_list/create_circle/dom.rs
frontend/elements/src/entry/community/circle-details.ts
frontend/elements/src/entry/community/member-details.ts

Closes #3781 
- Auto direction for community circles details, creating a circle and member details

chore(fe/community): Auto direction for community circles and member details

---

frontend/elements/src/core/wysiwyg/styles.ts

fix(fe/stickers): Ensure text sticker rendering renders dir correctly

---

frontend/apps/crates/components/src/lib.rs
frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/add_unit_value/add_link/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/add_unit_value/add_link/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/state.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/pro_dev/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/state.rs
frontend/apps/crates/entry/asset/play/src/pro_dev/actions.rs
frontend/apps/crates/entry/module/cover/edit/src/lib.rs
frontend/apps/crates/entry/module/drag-drop/edit/src/lib.rs
frontend/apps/crates/entry/module/find-answer/edit/src/lib.rs
frontend/apps/crates/entry/module/poster/edit/src/lib.rs
frontend/apps/crates/entry/module/resource-cover/edit/src/lib.rs
frontend/apps/crates/entry/module/tapping-board/edit/src/lib.rs
frontend/apps/crates/entry/module/video/edit/src/lib.rs
frontend/elements/src/entry/asset/_common/sidebar-modules/module.ts
frontend/elements/src/entry/asset/edit/sidebar/module/window.ts

https://github.com/ji-devs/ji-cloud/issues/3610
TODO: 
CHORE: 
- [add impl Type for unstable to crate attributes](https://github.com/ji-devs/ji-cloud/pull/3798/commits/c505efffd4407edbcdd93de21c3fdb8697a93577)

feat(fe/pro-dev/edit): thumbnail icons and update button

---

backend/api/src/db/billing.rs
backend/api/src/http/endpoints/billing.rs
shared/rust/src/api/endpoints/billing.rs
shared/rust/src/domain/billing.rs

feat(be/billing): Add an endpoint to fetch all subscription plans mapped to a display struct

---

frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/state.rs

- On a page reload, an existing unit will be populated.

fix(fe/pro-dev/unit): load unit data on page reload

---

shared/rust/src/domain/billing.rs

fix(be/billing): Better data structure for subscription plans

---

frontend/apps/crates/entry/asset/play/src/pro_dev/actions.rs
frontend/apps/crates/entry/asset/play/src/pro_dev/dom.rs
frontend/apps/crates/entry/asset/play/src/pro_dev/state.rs
frontend/elements/src/entry/asset/play/pro-dev/pro-dev-player.ts

https://github.com/ji-devs/ji-cloud/issues/3611
- functionality for player popup and landing

feat(fe/pro-dev/player): add landing page, overlay player

---

shared/rust/src/domain.rs
shared/rust/src/domain/billing.rs
shared/rust/src/domain/user.rs

Part of https://github.com/ji-devs/ji-cloud/issues/3700;
Part of https://github.com/ji-devs/ji-cloud/issues/3699

chore(be/billing): restructure plans endpoint

---

backend/api/src/http/endpoints/billing.rs

fix(be/billing): Charge automatically

---

backend/api/src/http/endpoints/billing.rs
shared/rust/src/config.rs
shared/rust/src/domain/billing.rs

chore(be/billing): Set new payment method as the default for a customer

---

frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/dom.rs
frontend/apps/crates/entry/asset/play/src/course/actions.rs
frontend/elements/src/entry/asset/edit/pages/unit-edit.ts

https://github.com/ji-devs/ji-cloud/issues/3831
1. Add cell space between text "Build your course..." and the white area.
2. Move Video to be the first radio button
3. Change capitalization of "Add Link" to "Add link"
4. Change capitalization of "Add Description" to "Add description"

style(fe/asset/edit/pro-dev): adjust editor size, position, label

---

shared/rust/src/domain/asset.rs

change AssetType serde to #[serde(rename_all = "kebab-case")]

fix(fe/asset/edit/pro-dev): change to kebab-case using serde

---

frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/dom.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/google_sheet.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/quizlet.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/sutori.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/thinglink.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/vimeo.rs
frontend/apps/crates/components/src/module/_groups/design/edit/embed/select/embeds/youtube.rs
frontend/apps/crates/entry/asset/edit/src/edit/actions/pro_dev_actions.rs
frontend/apps/crates/entry/module/embed/edit/src/base/sidebar/step_2/dom.rs

remove load `get_unit()` use in `get_pro_dev_spots()` for `impl AssetEditState {}`

fix(fe/asset/edit/pro-dev): remove redundant unit loads

---

frontend/apps/crates/entry/asset/edit/src/edit/sidebar/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/state.rs
frontend/elements/src/entry/asset/_common/sidebar-modules/module.ts
frontend/elements/src/entry/asset/edit/sidebar/publish.ts
frontend/elements/src/entry/asset/edit/sidebar/sidebar.ts
frontend/elements/src/module/_common/types.ts

https://github.com/ji-devs/ji-cloud/issues/3832

feat(fe/asset/edit/pro-dev): get rid of jig monster on sidebar

---

frontend/apps/crates/components/src/stickers/embed/dom.rs
frontend/apps/crates/components/src/stickers/embed/types/mod.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/pro_dev/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/pro_dev/menu/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/pro_dev/mod.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/pro_dev/unit_cloner.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/actions.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/pro_dev/actions.rs
frontend/apps/crates/utils/src/location.rs

https://github.com/ji-devs/ji-cloud/issues/3860

feat(fe/asset/edit/pro-dev): kebab menu unit edit, move, duplicate

---

frontend/apps/crates/entry/asset/play/src/course/dom.rs
frontend/apps/crates/entry/asset/play/src/pro_dev/player_main/dom.rs
frontend/apps/crates/utils/src/asset.rs
frontend/elements/src/entry/asset/play/course/course-main.ts

https://github.com/ji-devs/ji-cloud/issues/3864
- Gallery play kebab menu
- changed play text item count from Jigs to Units

fix(fe/asset/edit/pro-dev): gallery play option

---

backend/api/migrations/20230519181335_pro-dev-parent.sql
backend/api/sqlx-data.json
backend/api/src/db/pro_dev.rs
backend/api/src/http/endpoints/pro_dev.rs
backend/api/tests/integration/pro_dev.rs
backend/api/tests/integration/snapshots/integration__pro_dev__clone-1.snap
backend/api/tests/integration/snapshots/integration__pro_dev__clone-2.snap
shared/rust/src/api/endpoints/pro_dev.rs
shared/rust/src/domain/module/body/_groups/design.rs
shared/rust/src/domain/pro_dev.rs

https://github.com/ji-devs/ji-cloud/issues/3864
- clone endpoint

feat(be/pro-dev): create clone endpoint

---

frontend/apps/crates/components/src/unit/thumbnail/dom.rs
frontend/apps/crates/components/src/unit/unit_value/dom.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/dom.rs
frontend/elements/src/_bundles/asset/play/imports.ts
frontend/elements/src/module/video/youtube-thumbnail.ts
shared/rust/src/domain/module/body/embed.rs

- For unit editor and player main, video thumbnails properly display.

fix(fe/asset/pro-dev): render youtube thumbnail

---

frontend/apps/crates/components/src/unit/unit_value/dom.rs
frontend/apps/crates/components/src/unit/unit_value/styles.css
frontend/elements/src/entry/asset/edit/pages/unit-edit.ts

- Unit player window fits the editor

style(fe/asset/edit/pro-dev): adjust unit player window

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/migrations/20230522125812_school-accounts.sql
backend/api/sqlx-data.json
backend/api/src/db.rs
backend/api/src/db/account.rs
backend/api/src/db/billing.rs
backend/api/src/db/user.rs
backend/api/src/error.rs
backend/api/src/http.rs
backend/api/src/http/endpoints/account.rs
backend/api/src/http/endpoints/billing.rs
backend/api/src/http/endpoints/mod.rs
backend/api/src/http/endpoints/user.rs
backend/pages/Cargo.lock
backend/util/Cargo.lock
frontend/apps/crates/components/src/text_editor/dom/mod.rs
frontend/apps/crates/components/src/text_editor/mod.rs
shared/rust/Cargo.toml
shared/rust/src/api/endpoints.rs
shared/rust/src/api/endpoints/account.rs
shared/rust/src/api/endpoints/billing.rs
shared/rust/src/domain/billing.rs
shared/rust/src/domain/user.rs

chore(be/billing): WIP Rework billing to use accounts

---

frontend/apps/crates/entry/asset/edit/src/gallery/actions/mod.rs
frontend/apps/crates/entry/asset/edit/src/gallery/actions/pro_dev_actions.rs

https://github.com/ji-devs/ji-cloud/issues/3864
Pro-Dev duplication

feat(fe/asset/edit/pro-dev): enable duplicate of pro dev

---

backend/api/sqlx-data.json
backend/api/src/db/pro_dev.rs

- update `created_at` and `updated_at` timestamps

fix(be/asset/pro-dev): add new timestamps to duplicates

---

frontend/apps/crates/entry/asset/play/src/course/player_main/dom.rs
frontend/apps/crates/entry/asset/play/src/course/player_main/state.rs
frontend/apps/crates/entry/asset/play/src/course/player_main/styles.css
frontend/apps/crates/entry/asset/play/src/course/player_popup/dom.rs
frontend/apps/crates/entry/asset/play/src/course/player_popup/state.rs
frontend/apps/crates/entry/asset/play/src/course/player_popup/styles.css
frontend/elements/src/entry/asset/play/playlist/playlist-item.ts

https://github.com/ji-devs/ji-cloud/issues/3865

feat(fe/asset/play/course): add Read more for long descriptions

---

frontend/apps/crates/components/src/unit/unit_value/dom.rs
frontend/apps/crates/components/src/unit/unit_value/styles.css
frontend/apps/crates/entry/asset/play/src/course/player_popup/styles.css

https://github.com/ji-devs/ji-cloud/issues/3901
Maintain aspect ratio of 16:9 in editor and player

style(fe/asset/play/course): maintain 16:9 ratio for video

---

frontend/apps/crates/entry/asset/play/src/course/player_main/dom.rs
frontend/apps/crates/entry/asset/play/src/course/player_popup/dom.rs

https://github.com/ji-devs/ji-cloud/issues/3865
Disable close button when iframe is active for previews

fix(fe/asset/play/course): remove double x

---

frontend/apps/crates/entry/asset/play/src/course/player_main/dom.rs
frontend/apps/crates/entry/asset/play/src/course/player_main/styles.css
frontend/apps/crates/entry/asset/play/src/course/player_popup/dom.rs
frontend/apps/crates/entry/asset/play/src/course/player_popup/styles.css
frontend/elements/src/entry/asset/play/playlist/playlist-item.ts

Hover effect for unit description popup

style(fe/asset/play/course): add hover for unit info popup

---

backend/api/sqlx-data.json
backend/api/src/db/course.rs
backend/api/src/db/jig.rs
backend/api/src/db/playlist.rs
backend/api/src/db/resource.rs
backend/api/src/db/user.rs
backend/api/src/http/endpoints/course.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/playlist.rs
backend/api/src/http/endpoints/resource.rs

Remove duplicate logic and add a new `has_scopes` function; replace usages of `*::is_admin` with `db::user::has_scopes(...)` instead.

chore(be): Clean up is_admin logic

---

backend/api/sqlx-data.json
backend/api/src/db/account.rs
backend/api/src/db/user/public_user.rs
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow-1.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_follow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow-1.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_follower_and_unfollow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_following_and_unfollow-1.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_following_and_unfollow-2.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_public_user.snap
backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_users_with_circles.snap
shared/rust/src/domain/user/public_user.rs

https://github.com/ji-devs/ji-cloud/issues/3921
- JIG count
- Playlist count
- Course count
- Resource count
- Total asset count

feat(be/public_user): add asset counts and total asset count to resp

---

backend/api/sqlx-data.json
backend/api/src/db/account.rs
backend/api/src/db/user/public_user.rs
backend/api/src/http/endpoints/user/public_user.rs
shared/rust/src/domain/user/public_user.rs

https://github.com/ji-devs/ji-cloud/issues/3922
- optionally sort users by their total asset count 
- `orderBy=assetCount`

feat(be/public_user): order by number of assets a user has created

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/http/endpoints/circle.rs
backend/api/tests/integration/circle.rs
backend/api/tests/integration/snapshots/integration__circle__browse_circles.snap
backend/api/tests/integration/snapshots/integration__circle__browse_circles_with_users.snap
shared/rust/src/domain/circle.rs
shared/rust/src/domain/user/public_user.rs

https://github.com/ji-devs/ji-cloud/issues/3923
optionally sort circles by their member count
orderBy=memberCount

feat(be/circle): order by member count in browse

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/extractor.rs
backend/api/src/http/endpoints/circle.rs
backend/api/src/http/endpoints/jig.rs
backend/api/src/http/endpoints/playlist.rs
backend/api/src/http/endpoints/resource.rs
backend/api/src/http/endpoints/user/public_user.rs
backend/api/tests/integration/snapshots/integration__circle__browse_circles.snap
backend/api/tests/integration/snapshots/integration__circle__browse_circles_with_users.snap
backend/api/tests/integration/snapshots/integration__circle__create-2.snap
backend/api/tests/integration/snapshots/integration__circle__leave_circle-1.snap
backend/api/tests/integration/snapshots/integration__circle__leave_circle-2.snap
backend/api/tests/integration/snapshots/integration__circle__remove_member-1.snap
backend/api/tests/integration/snapshots/integration__circle__remove_member-2.snap
backend/api/tests/integration/snapshots/integration__circle__update_circle-1.snap
backend/api/tests/integration/snapshots/integration__circle__update_circle-2.snap
shared/rust/src/domain/circle.rs

resolves https://github.com/ji-devs/ji-cloud/issues/3933

feat(be/circle): add joined flag in Circle response

---

backend/api/sqlx-data.json
backend/api/src/db/account.rs
backend/api/src/http/endpoints/account.rs
shared/rust/src/domain/billing.rs

Non-admin users won't see account details when making an api request to get school details.

feat(be/billing): Include actual account details for school account for auth'd users

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs

https://github.com/ji-devs/ji-cloud/issues/3727
- add SQL check for existing user name on profile creation

fix(be/user): warn if username exists when user create

---

frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts

https://github.com/ji-devs/ji-cloud/issues/3949
Long descriptions and teacher resources are contained within the info panel

style(fe/asset/play/jig): text break for jig info panel

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs

https://github.com/ji-devs/ji-cloud/issues/3974
Sync public users in Algolia

fix(be/public_user): sync public_user

---

frontend/apps/crates/entry/asset/play/src/course/player_main/dom.rs

https://github.com/ji-devs/ji-cloud/issues/3982
- Change "Share playlist" to "Share course"

feat(fe/asset/play/course): change Share Playlist to Course

---

backend/api/migrations/20230703141630_import_public_user_trigger.sql
backend/api/sqlx-data.json
backend/api/src/algolia.rs

https://github.com/ji-devs/ji-cloud/issues/3974
- import `user_profile` table to `public_user` table
- triggers to add or subtract from `public_user`

fix(be/public_user): add triggers for new user profiles

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs

https://github.com/ji-devs/ji-cloud/issues/3727

fix(be/user): lowercase username in lookup for register

---

backend/api/sqlx-data.json
backend/api/src/db/circle.rs
backend/api/src/http/endpoints/circle.rs
shared/rust/src/api/endpoints/circle.rs
shared/rust/src/domain/circle.rs

https://github.com/ji-devs/ji-cloud/issues/3925

feat(be/circle): add admin filter

---

frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs

feat(fe/asset/play/jig): add author name to jig info

---

frontend/elements/src/core/popups/popup-body.ts
frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts

style(fe/asset/play/jig): add author name, reposition name and published at

---

frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts

- clicking the author name opens their community page

feat(fe/asset/play/jig): link to community user in info panel

---

backend/api/sqlx-data.json
backend/api/src/db/user.rs
backend/api/tests/integration/snapshots/integration__user__browse_user_badges-1.snap
backend/api/tests/integration/snapshots/integration__user__browse_user_badges-2.snap
frontend/apps/crates/entry/admin/src/users/editable_user.rs
frontend/apps/crates/entry/admin/src/users/table/dom.rs
frontend/elements/src/entry/admin/users/table.ts
shared/rust/src/domain/billing.rs
shared/rust/src/domain/user.rs

feat(fe/admin): Show subscription details for users

---

frontend/apps/crates/components/src/page_header/dom.rs
frontend/elements/src/core/page-header/page-header-profile.ts

https://github.com/ji-devs/ji-cloud/issues/4029
- My JIGs
- My playlists
- My resources
- My courses
- Profile
- Account
-Plans & Billing
- Jigzi school account

feat(fe/home): add new links to profile dropdown

---

backend/api/Cargo.lock
backend/api/Cargo.toml
backend/api/migrations/20230810093406_add-plan-pricing-discounts.sql
backend/api/sqlx-data.json
backend/api/src/db/billing.rs
backend/api/src/http/endpoints/billing.rs
backend/pages/Cargo.lock
frontend/apps/crates/entry/user/src/settings/actions.rs
frontend/apps/crates/entry/user/src/settings/dom/mod.rs
frontend/apps/crates/entry/user/src/settings/dom/plan_info.rs
frontend/apps/crates/entry/user/src/settings/state.rs
frontend/elements/src/core/inputs/composed/switch.ts
frontend/elements/src/entry/user/profile/landing.ts
shared/rust/Cargo.toml
shared/rust/src/domain.rs
shared/rust/src/domain/billing.rs

- Get subscription price info;
- Get coupon applied to subscription;
- Update period end label when in trial;
- Update plan display names;
- Include price information in current plan view;
- Include coupon info if available.

feat: Update user current plan details

---

backend/api/sqlx-data.json
shared/rust/src/api/endpoints/jig/codes.rs

Required
```bash
cargo sqlx prepare -- --lib
cargo sqlx prepare -- --test integration
```
My local db was broken, so this fixed it: 
```bash
sqlx db drop -y && sqlx db create && sqlx migrate run
```

fix: Generate sqlx-data.json file

---

frontend/elements/src/module/flashcards/_common/main/container.ts

fix: Move flashcards next pair button to center of module, below card pair

---

frontend/apps/crates/entry/module/memory/play/src/base/card/animation.rs
frontend/apps/crates/entry/module/memory/play/src/base/sidebar/actions.rs
frontend/apps/crates/entry/module/memory/play/src/base/sidebar/dom.rs
frontend/apps/crates/entry/module/memory/play/src/base/stage/game/actions.rs
frontend/apps/crates/entry/module/memory/play/src/base/state.rs
frontend/elements/src/module/memory/play/sidebar.ts

feat: Stack memory game card pairs in a single column

---

frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/preview.rs

feat: Add info tooltip to the module edit preview steps

---

frontend/apps/crates/components/src/page_header/actions.rs
frontend/apps/crates/components/src/page_header/dom.rs
frontend/apps/crates/entry/user/src/subscribe1/actions.rs
frontend/apps/crates/utils/src/lib.rs
frontend/apps/crates/utils/src/window.rs

- Fixes the first part of #4125 
- Resolves #4126

feat: Logout redirects to login page; Login from plans redirects user back to plans page

---

frontend/apps/crates/entry/user/src/welcome/dom.rs

feat: Add account upgrade button to welcome screen

---

frontend/apps/crates/entry/asset/edit/src/edit/publish/pre_publish/actions/mod.rs
frontend/apps/crates/entry/asset/edit/src/edit/publish/pre_publish/dom/age.rs

feat: Remove default ages from asset publish dropdown

---

frontend/apps/crates/entry/asset/edit/src/gallery/dom.rs
frontend/apps/crates/entry/asset/edit/src/studio/dom.rs
frontend/elements/src/core/buttons/rectangle.ts
frontend/elements/src/entry/asset/studio.ts

feat: Add Jigzi Studio instructions; Fix help button; Update gallery back label

---

frontend/apps/crates/entry/home/src/home/search_results/dom.rs
frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
frontend/elements/src/entry/home/home/search-results/search-results-section.ts
frontend/elements/src/entry/home/home/search-results/search-results.ts

fix: Ensure top rated toggle on search is always visible

---

backend/api/sqlx-data.json
backend/api/src/algolia.rs
backend/pages/Cargo.lock

feat: Make categories searchable by parent categories

---

frontend/apps/crates/entry/asset/edit/src/edit/sidebar/jig/settings/dom/background.rs
frontend/apps/crates/entry/asset/edit/src/edit/sidebar/jig/settings/dom/feedback.rs

fix: Stop feedback audio before playing next audio clip
