- backend/_core/rust/src/google.rs
- backend/_core/rust/src/settings.rs
- backend/api/crates/actions/src/auth.rs
- backend/api/crates/actions/src/lib.rs
- backend/api/crates/actions/src/user.rs
- backend/api/crates/server/src/auth.rs
- backend/api/crates/server/src/cors.rs
- backend/api/crates/server/src/db.rs
- backend/api/crates/server/src/endpoints/user.rs
- backend/api/crates/server/src/lib.rs
- backend/api/crates/server/src/logger.rs
- backend/api/crates/server/src/reject.rs
- backend/api/crates/server/src/reply.rs
- backend/api/crates/server/src/routes.rs
- backend/api/crates/server/src/utils.rs
- backend/api/main/src/logger.rs
- backend/api/main/src/main.rs
- config/rust/src/lib.rs
- shared/rust/src/api/endpoints.rs
- shared/rust/src/api/mod.rs
- shared/rust/src/api/result.rs
- shared/rust/src/auth.rs
- shared/rust/src/lib.rs
- shared/rust/src/user.rs
run `cargo fmt` and clean up warnings, mostly of the backend / shared code
> lint: clear up most warnings and run cargo fmt

- backend/api/src/http/cors.rs
>  fix: add `supports_credentials` to cors config 

- backend/api/Cargo.lock
- backend/api/Cargo.toml
Should fix #197
Algolia will need to be "fixed" so, the following query needs to be run on the db:
```sql
-- the reason why we can get away with only hitting the ones that have been updated is because they were initially uploaded correctly, and the ones that have an `updated_at` are simply out of date.
update image_metadata set last_synced_at = null where updated_at is not null
```
Additionally, the object with `objectID: batch` in the `image` index needs to be removed because it's corrupted and algolia-rs doesn't handle the way it does that attribute properly (yet). There's probably some setting we could use while querying to just not get match information though
> fix: update algolia-rs to fix bug with algolia integration

- backend/_core/rust/src/env/keys.rs
- backend/_core/rust/src/settings.rs
- backend/api/src/algolia.rs
- config/rust/src/lib.rs
Like #202, this requires re-syncing algolia, unlike #202, it needs to do a total re-sync
* the `image` index *should* be removed
the following sql needs to be ran:
```sql
update image_metadata set last_synced_at = null
```
> fix: allow for the algolia image index to be chosen manually if running locally

- backend/_core/rust/Cargo.toml
- backend/_core/rust/src/http.rs
- backend/_core/rust/src/lib.rs
- backend/_core/rust/src/settings.rs
- backend/api/Cargo.toml
- backend/api/Dockerfile
- backend/api/Makefile.toml
- backend/api/src/main.rs
- backend/pages/Cargo.toml
- backend/pages/Dockerfile
- backend/pages/Makefile.toml
- backend/pages/src/main.rs
reasoning:
* easier to maintain
* less binaries to produce (technically `release` and `sandbox` produce the same binary now, just executed with slightly different arguments)
> refactor: replace most of `core`'s features with runtime config

- backend/api/migrations/20201015192354_add_jig_tables.sql
- backend/api/migrations/20201023002445_fix_jig_tables.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
fixes a inconsistency caused by a premature merge of #222, pending on the answer to
> When we return a jig, should we fetch the modules as `Vec<Module>` (plus `cover: Option<Module>` and `end` as the same) or should we just return the IDs
What this PR does:
* gives jigs a "default" (you can create them without them having basically anything)
* this causes fallout in the `GET` route, since more things can be null
* returns `ModuleId` for modules instead of `serde_json::Value` (the above question is in reference to this)
* allows re-ordering of modules by `PATCH`ing a jig and changing around the order
This unfortunately means that it's impossible to create modules again, I figured getting this done right away was more effective, given that I can add modules easily and without breaking …
> fix!: more closely follow what we wanted for the jig api

- backend/api/Cargo.lock
- backend/api/Cargo.toml
- backend/api/migrations/20201030172808_settings_table.sql
- backend/api/sqlx-data.json
- backend/api/src/algolia.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/main.rs
turns out this is caused by the fact that I still didn't mange to fix indexing, so I've done that now and _tested_ it (manually), thanks to being able to use an index without murdering sandbox/prod, I also fixed the symptom (by ignoring the highlight/snippet data, which we don't currently use)
Also fixes a bug where we kept syncing every image.
Requires a re-sync. (and algolia needs to remove the object with the id `batch`)
> fix: make algolia batching work properly (again) and make it *not* 500 on unxpected data

- backend/api/src/http/endpoints/audio.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/s3.rs
- shared/rust/src/domain/audio.rs
- shared/rust/src/domain/image.rs
- shared/rust/src/lib.rs
- shared/rust/src/media.rs
Apparently this also fixes #397 for newly uploaded images (so, PUTing the same content as the raw will fix it), did that without realizing it... Intends to close #396
> feat: allow media urls to be inferred from the media's ID

- backend/api/migrations/20210428184042_user-font-table.sql
cc @rrcwang, not a you problem, but, sqlx can't understand migrations being ran out of order, so I fixed that, and since I had to move the migration anyway, I added the `check` constraint
> fix(backend/api): fix order of migrations

- backend/api/fixtures/8_jig.sql
- backend/api/migrations/20210511104544_jig-module-is-complete.sql
- backend/api/sqlx-data.json
- backend/api/src/db/module.rs
- backend/api/src/http/endpoints/module.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_empty.snap
- shared/rust/src/domain/jig/module.rs
closes #1044
* adds `is_complete: bool` field for jig modules
* defaults to `false` when modules are created
* changes response for `GET /v1/jig/<jig_id>/module/<module_id>`
* changes request and response for `PATCH`
* `LiteModule` is unchanged
> feat: add is_complete field to module get, update

- backend/api/tests/integration/animation.rs
- backend/api/tests/integration/audio/user.rs
- backend/api/tests/integration/category.rs
- backend/api/tests/integration/image.rs
- backend/api/tests/integration/jig/cover.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/locale.rs
- backend/api/tests/integration/locale/entry.rs
- backend/api/tests/integration/main.rs
- backend/api/tests/integration/meta.rs
- backend/api/tests/integration/session.rs
- backend/api/tests/integration/user.rs
- backend/api/tests/integration/user/color.rs
- backend/api/tests/integration/user/font.rs
`cargo test` could sometimes fail a few integration tests by exceeding Postgres's default connection limit. This occurs when running too many tests w/o explicit server stop before reaching end of scope. Has to do with how dropping test threads is handled.
Adding explicit stops after test requests are handled fixes this.
> fix(tests): explicitly stop app at end of each test

- backend/api/migrations/20210520130812_jig-display-name-option.sql
- backend/api/sqlx-data.json
- backend/api/src/algolia.rs
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- shared/rust/src/domain/jig.rs
closes #1045 
* `Jig.display_name` is now `String` 
* `JigCreateRequest.display_name` is now `String` with default `""` empty string
* `JigUpdateRequest.display_name` is unchanged
> fix: unnest Option in display_name for jig & requests

- backend/api/fixtures/5_image.sql
- backend/api/migrations/20210603033228_recent-user-images-list.sql
- backend/api/sqlx-data.json
- backend/api/src/db/image.rs
- backend/api/src/error.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/tests/integration/image.rs
- backend/api/tests/integration/jig/additional_resource.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/snapshots/integration__image__recent__create.snap
- backend/api/tests/integration/snapshots/integration__image__recent__create_conflict.snap
- backend/api/tests/integration/snapshots/integration__image__recent__delete.snap
- backend/api/tests/integration/snapshots/integration__image__recent__list_no_limit.snap
- backend/api/tests/integration/snapshots/integration__image__recent__list_with_limit.snap
- backend/api/tests/integration/snapshots/integration__image__recent__update.snap
- shared/rust/src/api/endpoints/image.rs
- shared/rust/src/domain/image.rs
closes #909 
`GET /v1/user/me/recent/image` with optional limit query field.
`POST /v1/user/me/recent/image` to push image .
`PATCH, DELETE /v1/user/me/recent/image/{id}` on image id to modify/delete.
> feat(backend/api): api for a user recent images list

- backend/api/migrations/20210608032633_jig-description-unnest-option.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/jig.rs
- shared/rust/src/domain/jig.rs
closes #1088
* `Jig.description` is now `String` instead of `Option<String>`
* `JigCreateRequest.description: String` is added
* `JigCreateRequest.is_public: bool` is added
* `JigUpdateRequest.description: String` is added
* `JigUpdateRequest.is_public: bool` is added
> fix: unnest Option for jig description, include field in requests

- backend/pages/src/server/routes.rs
- backend/pages/src/templates/direct.rs
- backend/pages/src/templates/spa.rs
closes #1087 
Points to `spa` template with `/home` path.
> feat(pages): change home route to use `spa` template 

- backend/api/fixtures/8_jig.sql
- backend/api/migrations/20210609215604_module-body-remove-option.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/db/module.rs
- backend/api/src/http/endpoints/module.rs
- backend/api/tests/integration/auth/forbidden.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- shared/rust/src/domain/jig/module.rs
@dakom @MendyBerger 
Breaking changes to `shared`:
* `Module.body`  is now not `Option`
* `LiteModule.kind` is now not `Option`
* `ModuleCreateRequest.body` is now not `Option`, must provide a module kind
* Implements trait `Default` to be `Cover` with `content: None`
Other changes:
* jig post requests populate with only a `Cover` instead of `Cover` and an empty `None` module.
* See [change here](https://github.com/ji-devs/ji-cloud/pull/1103/files#diff-f9eb12329813b38c23953789b64984c8a5872763e6f8d35f31d527d0181f991aL52-L56)
> feat: make Module.body not optional

- shared/rust/src/domain/jig/module.rs
to use `ModuleData::default()`
> fix: correct `impl Default` for `ModuleCreateRequest`, 

- backend/api/src/extractor.rs
- backend/api/src/http/endpoints/animation.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/http/endpoints/image/user.rs
- backend/api/src/service/storage.rs
- backend/api/tests/integration/image.rs
resolves #1193
Optionally include a `Origin: {domain}` header in media upload requests for global images, user images, and animations. If this domain is one of the allowed (specified in `config::CORS_ORIGINS`), it is then passed to GCS during the upload session URI create request.
> fix(gcs): use `Origin` header for CORS w/ resumable uploads

- backend/api/fixtures/8_jig.sql
- backend/api/migrations/20210802182856_jig-default-player-settings.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/auth/unauthorized.rs
- backend/api/tests/integration/jig/draft.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__draft__create_draft-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__draft__get_draft-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__draft__publish_draft-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__draft__publish_draft.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- shared/rust/src/config.rs
- shared/rust/src/domain/jig.rs
- shared/rust/src/domain/jig/player.rs
resolves #1241
resolves #1229
BREAKING CHANGES: 
* Jig create uses `default_player_settings: JigPlayerSettings` instead of `direction: bool` and `display_score: bool`
* Jig update uses `default_player_settings: Option<JigPlayerSettings>` instead of `direction: Option<bool>` and `display_score: Option<bool>`
*  Responses for GET routes (jig, browse, search) changed accordingly
> jig default player settings, make `GET` jig public

- backend/api/Cargo.lock
- backend/api/Cargo.toml
- backend/api/src/extractor.rs
- backend/api/src/http/endpoints/user.rs
- backend/api/src/lib.rs
- shared/rust/src/domain/jig.rs
argon2 interface:
* Old ([0.1.0](https://docs.rs/argon2/0.1.0/argon2/struct.Argon2.html#method.hash_password)): alg version in function signature
* New ([0.2.2](https://docs.rs/argon2/0.2.2/argon2/struct.Argon2.html#method.hash_password)): alg version passed in `params`
> chore: bump dependencies

- backend/api/src/db/jig.rs
- backend/api/src/db/module.rs
- backend/api/src/http/endpoints/module.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__module__create_default-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__module__create_default.snap
resolves #1266
resolves #1257
* The extra most outer scope with the module type name as json key is no longer used as expected, matching the result of module update requests (see #1266 for reference)
* `POST /v1/jig/{id}/module` returns with `201 - CREATED` instead of `200 - NO_CONTENT` as expected of POST resouce requests.
> fix(backend/api): remove extra scope in default and create module

- backend/api/src/http/endpoints/jig/player.rs
> feat(backend/api): make `GET /v1/jig/player/{index}` a public endpoint

- frontend/apps/crates/components/src/module/_common/mod.rs
- frontend/apps/crates/components/src/module/_common/thumbnail/dom.rs
- frontend/apps/crates/components/src/module/_common/thumbnail/mod.rs
- frontend/apps/crates/components/src/module/_common/thumbnail/state.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/components/age.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/components/categories_pills.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/components/categories_select.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/components/goal.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/publish_jig.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/state.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
This changes the jig publish flow from:
1. Create State with placeholders
2. Render it / load it (async race)
3. Inside the render logic, deal with placeholders
To:
1. Load the State
2. Render it
It required changing several lines of code. It was almost entirely about _removing_ the nesting, and it was pretty much a repeatable, smooth process - but I still think it's worth it for @MendyBerger to review before merging, in case I didn't see some original intent somewhere.
Note that I believe we can _also_ remove the `Mutable` wrapper for goals / ages, but I didn't do that here.
> Refactor publish

- backend/api/fixtures/8_jig.sql
- backend/api/migrations/20211005184125_jig_privacy_level_fix.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__count.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
- backend/api/tests/integration/snapshots/integration__jig__get-2.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
- backend/api/tests/integration/snapshots/integration__user__post_profile.snap
- backend/api/tests/integration/snapshots/integration__user__post_profile.snap.new
- shared/rust/src/domain/jig.rs
closes issue #1601 
- `privacy_level` relocated from `JigResponse` to `JigData` 
- moved `privacy_level` from `jig` to `jig_data` table
> privacy level field moved to JigData object

- backend/api/migrations/20211103181137_jig_module_cover.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
- backend/api/tests/integration/snapshots/integration__jig__get-2.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
- shared/rust/src/api/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
closes issue: #1795 
migrated new field to existing jigs, set to true, and defaulted new jigs to false until a cover is set
Added Endpoint: 
`PATCH ../v1/jig/{jigId}/cover` 
- inputs: Jig id in path
> feat(be/cover): add initial cover set in response and patch endpoint

- backend/api/sqlx-data.json
- backend/api/src/algolia.rs
All jigs will now sync with algolia. 
Threshold for number of jigs to be updated was reached in the update jig query. Solved this by getting rid of a case that unnecessarily syncs every jig in the db.
> fix(be/algolia_jigs): omit case for non-private jigs in query

- backend/api/sqlx-data.json
- backend/api/src/http/endpoints/jig/module.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap
- shared/rust/src/api/endpoints/jig/module.rs
- shared/rust/src/domain/jig/module.rs
closes issue #1928 
`GET Module` only requires path inputs
> refactor(be/get_module): omit stable id option and query parameter

- backend/api/sqlx-data.json
- backend/api/src/db/jig/additional_resource.rs
- backend/api/src/error.rs
closes issue #1952 
Additional resource `GET` endpoints have 404 error messages instead of 500.
> refactor(be/resources): add 404 error messages

- frontend/apps/crates/entry/jig/play/src/player/actions.rs
Resolves #1851
This PR resets the done state to `false` whenever `navigate_to_index` is called.
> fix(fe/jig/play): Close done popup on replay

- frontend/apps/crates/entry/home/src/home/dom/mod.rs
- frontend/apps/crates/entry/home/src/home/state/mod.rs
- Possibly related to https://github.com/ji-devs/ji-cloud/issues/1372#issuecomment-905301246
- Implement `From<>` for `PageLinks` so that when navigating to the search page, the Content header is marked as active;
- **Note** I'm assuming that we would want the header to be marked active, but this may not be the case.
> fix(fe/home): Active content header for search mode

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/state.rs
Resolves #1959 
This PR makes a few changes to how the kebab menu and add button are rendered in the edit jig sidebar:
- The kebab button is displayed for all modules _except_ for the last one **if** the last one is a placeholder;
- The add button is displayed for all modules _except_ if the module is a placeholder, or the module immediately after is a placeholder;
- The delete button works for placeholders that appear between other modules (#1856).
> fix(fe/jig/edit): Hide module buttons when they aren't required

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/menu/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/state.rs
Resolves #1961
Other changes included:
- Fixes some syntax noted in #1967;
- Refactors MenuDom so that children are constructed by that component instead;
- Add a render function for rendering the modules "add" button.
> fix(fe/jig/edit): Prevent cover module being edited before having a cover dragged in

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
Related to #1959, fixes regression introduced in 5701eeeb74914dd4d9d82612dd8642689a52e31f
> fix(fe/jig/edit): Fix regression so that final placeholder does not have a menu

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/menu/dom.rs
Resolves #1960
- Duplicate and duplicate as functionality creates a new module which is added before the final placeholder module.
> fix(fe/jig/edit): Duplicate modules are added before the final placeholder module

- .env.sample
Updates the .env.example to include ALGOLIA_JIG_INDEX which is required to enable Algolia indexing.
> chore: Include ALGOLIA_JIG_INDEX in .env.example

- frontend/apps/crates/entry/user/src/login/dom.rs
- frontend/apps/crates/entry/user/src/register/pages/start/dom.rs
- frontend/apps/crates/entry/user/src/strings.rs
- frontend/storybook/src/components/entry/user/register/pages/start.ts
Closes #1919
Includes the same changes for the login screen.
> fix(fe/user): Remove email placeholders on login/register

- frontend/apps/crates/entry/module/flashcards/edit/src/settings/main/dom.rs
> fix(fe/flashcards/edit): Show flashcard pair instead of duplicates

- frontend/apps/crates/entry/jig/play/src/player/dom.rs
- frontend/apps/crates/entry/jig/play/src/player/state.rs
Closes #1668
- Defaults background audio to play;
- ~When there is no background audio, I added a regular title attribute to indicate that there is no audio, @corinnewo is this OK? I felt that hiding it for some jigs, and showing it for others may create an inconsistent experience?~
- When there is no background audio, the music icon is *not* rendered.
> fix(fe/jig/play): Default background audio to play

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- shared/rust/src/api/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
Part of #1505
- Implements `GET /v1/jig/<id>/like` which returns whether the current user has liked the JIG;
- Updates unlike to `DELETE /v1/jig/<id>/like` instead of `/unlike` so that it indicates the endpoints operate on the same resource.
@RickyLB to update sqlx-data.json I ran:
```bash
$ cargo sqlx prepare -- --lib
$ cargo sqlx prepare -- --test integration
```
I'm not 100% sure why it reshuffled a lot of the queries, maybe it's because my editor removed a bunch of whitespace from `db/jig.rs`?
> feat(be/jig): Implement endpoint for returning whether a jig is liked

- frontend/apps/crates/components/src/input/simple_select/dom.rs
- frontend/apps/crates/components/src/input/simple_select/mod.rs
- frontend/apps/crates/components/src/input/simple_select/state.rs
- frontend/apps/crates/entry/user/src/register/pages/step_2/dom.rs
- frontend/apps/crates/entry/user/src/register/pages/step_2/mod.rs
- frontend/apps/crates/entry/user/src/register/pages/step_3/actions.rs
- frontend/apps/crates/entry/user/src/strings.rs
Resolves #2030
- Adds a new trait, `Item` which exposes `value()` and `label()` methods;
- Updates `SimpleSelect` so that it can accept a list of a `Item` instead of types which impl `Display`
- Updates the registration process to send the language code which is expected by the profile page instead of the language string.
- Resolves the location not displaying in profile by sending the correct raw location data to the server.
*Note* that this also updates the the available languages in Step 2 to be English, Hebrew and French which is what is available on the profile page. Whereas originally there was English, Hebrew, Spanish, French and Russian. I wasn't sure which was correct so I used what was in use on the profile page.
> fix(fe/register): Send correct location and language data during registration

- frontend/apps/crates/components/src/input/simple_select/dom.rs
- frontend/apps/crates/entry/jig/play/src/player/actions.rs
- frontend/apps/crates/entry/jig/play/src/player/dom.rs
Properly resolves #1668
- Background audio starts automatically when the user clicks the start button on a jig
> fix(fe/jig/play): Start background audio once the user has started the jig

- frontend/apps/crates/entry/jig/play/src/player/actions.rs
- frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/like.rs
- frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/mod.rs
- frontend/apps/crates/entry/jig/play/src/player/state.rs
- shared/rust/src/domain/jig.rs
> Implement like action in JIG sidebar

- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
Part of #1678
- When the correct card is selected, the incorrect cards are flipped;
- When an incorrect card is selected, that card is flipped (existing behavior).
> feat(fe/module/card-quiz): Flip incorrect answers when correct answer is clicked

- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/state.rs
Closes #1678 
- When an incorrect choice is made, the card is flipped and remains flipped;
- Removes timer between making choices because incorrect cards are no longer re-shown.
> feat(fe/module/card-quiz): Keep incorrect choice card flipped when chosen

- backend/api/src/http/endpoints/jig.rs
- frontend/apps/crates/entry/jig/play/src/player/actions.rs
- frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/info.rs
- shared/rust/src/api/endpoints/jig.rs
Closes #1505
- Updates endpoint so that user auth isn't a requirement (@MendyBerger @RickyLB)
- My assumption with that is that most users who will be playing JIGs will not be logged in. Without this change we wouldn't have a true representation of how many times a JIG is played. 
- It also means that the endpoint can be abused to inflate play counts - not sure to what end though lol.
- Calls the play endpoint from the frontend when a JIG is started
- Renders play count and liked count in the info popup in a JIGs side panel 
Todo
> Show like and play counts in JIG info popup

- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_2/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/dom.rs
- frontend/apps/crates/components/src/tabs/dom.rs
- frontend/apps/crates/components/src/tabs/state.rs
Closes #1847
- When a user completes a list and clicks "Done", they are taken straight to the Images tab;
- Image tab is disabled when there is an empty list;
- Cyclic reference exists for widgets so that they can access step_1 state.
> feat(fe/components): Navigate user to Image tab when word list is created

- frontend/apps/Cargo.lock
- frontend/apps/crates/entry/home/Cargo.toml
- frontend/apps/crates/entry/home/src/home/dom/search_section/advanced_search.rs
- frontend/apps/crates/entry/home/src/home/dom/search_section/mod.rs
- frontend/apps/crates/entry/home/src/home/state/mod.rs
- frontend/elements/src/core/buttons/rectangle.ts
- frontend/elements/src/entry/home/home/search-section/search-bar.ts
- frontend/elements/src/entry/home/home/search-section/search-section.ts
Closes #1372
- Condenses search bar for search results page (Content page);
- Increases font size for select items and search button;
- Fixes formatting of "Advanced Search" button.
> feat(fe/search): Condense search hero on content page

- frontend/apps/crates/components/src/theme_selector/dom.rs
Resolves #2074
- Only renders the "Apply to JIG" modal when switching themes for the JIG cover
> fix(fe/theme-selector): Remove 'Apply to JIG' modal for theme selection in modules

- frontend/apps/crates/components/src/page_header/actions.rs
- frontend/apps/crates/components/src/page_header/state.rs
- frontend/apps/crates/entry/home/src/home/actions.rs
- frontend/apps/crates/utils/src/init/user.rs
- Cleans up the global `USER` so that the type is a no longer a `OnceCell<Mutable<Option<>>>` and is instead a `OnceCell<>`
- Reduces the amount of calls to the profile endpoint by reusing the `get_user()` function.
> refactor(fe): Clean-up profile types; Reduce calls to profile endpoint

- frontend/elements/src/entry/home/home/search-section/search-bar.ts
Restores the border on the search bar removed in #2083
> fix(fe/search): Add back removed border from search bar

- frontend/elements/src/core/inputs/wrapper.ts
Fixes an issue where inputs would leak through an overlay with a higher z-index priority
> fix(fe/core/input): Fix inputs leaking through higher priority z-indexes

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
- frontend/apps/crates/entry/jig/play/src/player/sidebar/dom/mod.rs
- frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts
Resolves #2078 
- Renames `lastBottomDecoration` to `isLastModule`
- Fixes double rendered robot feet for the publish module in the sidebar.
> fix(fe/jig/edit): Remove double robot feet in sidebaer publish module

- frontend/apps/crates/entry/admin/src/images/meta/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/menu/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/state.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/state.rs
- frontend/apps/crates/utils/src/events.rs
- frontend/elements/src/_bundles/jig/edit/imports.ts
- frontend/elements/src/core/buttons/icon.ts
- frontend/elements/src/core/modals/confirm.ts
- frontend/storybook/src/components/core/modals/confirm.ts
Closes #1943 
- Adds an `x-small` variant to `button-icon` so that smaller sized buttons can be rendered without extra css outside of the button;
- Refactors the modal-confirm element so that callers can define properties
- Replaces the `CustomToggle` event with a `CustomCancel` and `CustomConfirm`;
- Removes the visible property so that callers can either render or not render the modal;
- Adds a `dangerous` property so that the modal will switch the primary action to be cancel and change the text colors.
- Implements the confirm modal for deleting JIGs and for deleting activities when editing a JIG;
- Updates the usage of modal-confirm for deleting images from the admin section (**untested**).
> feat(fe/jig/edit): Add confirm modal for deleting JIGs and activities

- frontend/apps/crates/entry/admin/src/categories/actions.rs
- frontend/apps/crates/entry/admin/src/categories/dom.rs
- frontend/apps/crates/entry/admin/src/categories/state.rs
- frontend/elements/src/core/inputs/primitives/text-content.ts
- frontend/elements/src/core/menu/ellipses.ts
Part of #2099
@corinnewo this PR 
- Reorders category context menu - delete last;
- Delete item is red;
- Enables editing of any new category - previously you would need to have added a category and then renamed it;
- When renaming a category, the original text is selected so that it is easier to overwrite it
> fix(fe/admin/categories): Fix context menu alignment; Re-order items

- frontend/apps/crates/entry/admin/src/categories/actions.rs
- frontend/apps/crates/entry/admin/src/categories/dom.rs
- frontend/apps/crates/entry/admin/src/categories/state.rs
Closes #2099
- Adds confirm modal when deleting a category:
> feat(fe/admin/categories): Confirm modal for deleting categories

- frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs
Part of #2110
- Doesn't render a tooltip when the tooltip content is empty - Resolves the empty tooltip issue in Preview Mode.
@MendyBerger I'm not merging this yet because I think you were working with the tooltips recently.
> fix(fe/module/edit): Don't render tooltips with empty content

- frontend/elements/src/core/player-popup/player-popup.ts
- Resolves sizing issue with the popup player with Firefox (Ubuntu 21.04)
> fix(fe/elements): Render popup-player fullscreen on Firefox

- frontend/elements/src/entry/home/home/search-section/search-section-help.ts
- frontend/elements/src/entry/home/home/search-section/search-section.ts
Related to #1372
- Makes the previously hidden search help element visible;
- **Note** that the help element has no functionality tied to it yet.
> feat(home/search): Add back search help element

- frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/plain.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
- frontend/apps/crates/utils/src/events.rs
- frontend/elements/src/module/_groups/cards/play/card/card.ts
Part of #2060
- Add a new properties to the play-card element: `eventOnFlipped`;
- Adds an event to the element which dispatches a new `CustomCardFlipped` event if `eventOnFlipped` is true;
- For the card-quiz game, only plays the flipped sound effect if the player makes an incorrect choice
- Changes in another PR will include a sound effect for making the correct choice.
**Note** doesn't implement flip sound effects for other card games yet.
> feat(fe/components/cards): Implement flip sound effects

- frontend/apps/crates/components/src/audio/mixer/mixer.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/state.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/state.rs
Part of #2060 
- Implements `reset_from_jig` and `set_from_jig` for the `AudioMixer` so that there will always be positive and negative clips available;
- Plays a random success effect for the correct choice - Either from the list of configured effects, or from the complete list of available effects if none are configured for the JIG
> feat(fe/module/card-quiz): Play positive audio effect for the correct choice

- frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts
This PR currently uses the wrong image resource.
@MendyBerger, how can I view the images/media available in the media cloud, `https://media.jicloud.org/`?
As of now though, the logic is in place for expanded and collapsed module image rendering, displaying no image for an expanded sidebar, and showing the image for the module when the sidebar is collapsed only.
Once I know the name of the correct resource in our media cloud, I'll replace it with the correct path and this should be good to go!
Collapsed:
Expanded:
> feat: add icon to empty collapsed module in jig/edit sidebar

- frontend/apps/crates/entry/module/flashcards/play/src/base/game/dom.rs
- frontend/apps/crates/entry/module/matching/play/src/base/game/card/actions.rs
Part of #2060 
- Implements sound effect when player flips a card, but not when the card reverts back to it's state;
- Fixes effect playing for matching game where the player drops a card over empty space (it shouldn't play an effect)
> feat(fe/module/flashcards): Implement flip sound effect for flashcards

- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
- frontend/elements/src/module/_common/edit/widgets/image-search/image-select.ts
Bug fixes for FireFox:
- Fixes images not rendering correctly when editing modules with images;
- Fixes drag drop event redirecting to the image URL instead of placing the image in the drop container.
> fix(fe/elements): Set correct dimensions for img-ji element

- frontend/apps/crates/entry/module/flashcards/play/src/base/game/dom.rs
Part of #2060 
- Ensures the flip sound effect is always played when in the `Gate::Flipping` state
> fix(fe/module/flashcards): Play flip effect whenever in Flipping state

- frontend/elements/src/core/inputs/composed/search.ts
> feat: add transparency to image search input

- frontend/apps/crates/entry/jig/play/src/player/dom.rs
> feat(fe/jig/play): render timer format in min:sec

- frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs
- frontend/apps/crates/components/src/module/_common/edit/entry/base/state.rs
- frontend/elements/src/module/_common/edit/header.ts
- shared/rust/src/domain/jig/module/body.rs
- shared/rust/src/domain/jig/module/body/card_quiz.rs
- shared/rust/src/domain/jig/module/body/cover.rs
- shared/rust/src/domain/jig/module/body/drag_drop.rs
- shared/rust/src/domain/jig/module/body/flashcards.rs
- shared/rust/src/domain/jig/module/body/legacy.rs
- shared/rust/src/domain/jig/module/body/matching.rs
- shared/rust/src/domain/jig/module/body/memory.rs
- shared/rust/src/domain/jig/module/body/poster.rs
- shared/rust/src/domain/jig/module/body/resource_cover.rs
- shared/rust/src/domain/jig/module/body/tapping_board.rs
- shared/rust/src/domain/jig/module/body/video.rs
Closes #1564 
- Adds a subtitle when editing a module which has modes;
- Shifts the spacing when the subtitle is present so that the content doesn't get squashed too much by the addition of the subtitle element:
> feat(fe/module/edit): Add module mode subtitle for modules which set a mode

- frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
- Fixes swapped liked/played counts on search results
> fix(fe/home): Use correct fields for likes/plays

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- shared/rust/src/api/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
closes #2192 
New endpoint to update admin data for jig by `jig_id`.
`PATCH /v1/jig/{id}/admin`
- request body
> - curated 
> - rating
> - blocked
> fix(be/update_admin_data): add new endpoint for admin data update

- frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/preview.rs
closes #1888 
Image showing localhost environment with the fix
> feat(fe/module/cover/edit): remove iframe border

- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/lookup.rs
- frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/common.rs
- frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/dom.rs
- frontend/elements/src/module/_groups/cards/play/card/text.ts
Resolves #2184 
- Implements scaled font sizes determined by the length of text in a card;
- Font size is further scaled by the `Size` used for each card game.
> feat(fe/module): Scale card game font size based on text length

- frontend/apps/crates/entry/admin/src/curation/jig/actions.rs
- frontend/apps/crates/entry/admin/src/curation/jig/state/jig.rs
- Updates the admin creation page to call the new admin data update endpoint implemented in #2194
> fix(admin): Move admin data update into separate request

- frontend/apps/crates/components/src/module/_groups/cards/lookup.rs
- Decreases the font size for memory and matching games from #2188
> fix(fe/module/cards): Make matching and memory game text smaller

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
closes #2209 
`GET /v1/jig`
Jigs with `blocked = true` in `JigAdminData` do not show up in search results.
> refactor(be/jig_blocked): omit blocked jigs from jig search

- shared/rust/src/domain/jig.rs
closes #2212 
`NoRating` option for jig rating have been replaced with `null`.
> fix(be/rating): return null for ratings in jig admin data

- frontend/apps/crates/entry/jig/play/src/player/actions.rs
- frontend/elements/src/entry/home/home/search-results/search-result.ts
- frontend/elements/src/entry/jig/play/sidebar/jig-info.ts
Closes #1505 
- Updates played/liked to plays/likes;
- Moves the call to `/jig/{id}/play` to the end of a JIG.
> fix(fe/jig/play): Track play count once a JIG is played to completion

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/state.rs
> fix(fe/jig/edit): Always show cover placeholder if no cover module exists on a JIG

- frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
- frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts
Closes #2174 
- Sets singular or plural based on whether the value set is more than 1;
- Changes "pairs" to "cards";
- Changes "rounds" to "pages".
> feat(fe/jig/edit): Update JIG edit button settings so that it display plural/singular form

- backend/api/fixtures/8_jig.sql
- backend/api/migrations/20220109080509_jig_data_draft_or_live.sql
- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__cover__update_no_modules_changes.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_own_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_simple.snap
- backend/api/tests/integration/snapshots/integration__jig__clone-2.snap
- backend/api/tests/integration/snapshots/integration__jig__clone.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-2.snap
- backend/api/tests/integration/snapshots/integration__jig__create_default-3.snap
- backend/api/tests/integration/snapshots/integration__jig__get-2.snap
- backend/api/tests/integration/snapshots/integration__jig__get.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-3.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish.snap
- shared/rust/src/domain/jig.rs
#2177 
- Added filter to browse for draft or live jigs in Jig Browse.
- Added migration: 
> - for purging `jig_data_id` not associated with a `jig_id`, 
> - adding `int2` column `draft_or_live` and updated this field with corresponding draft or live value for each entry in jig data.
> feat(be/jig_browse): add draft or live filter for browse

- frontend/apps/crates/components/src/jigzi_help/actions.rs
- frontend/apps/crates/components/src/jigzi_help/dom.rs
- frontend/apps/crates/components/src/jigzi_help/state.rs
- frontend/apps/crates/utils/src/events.rs
- frontend/elements/src/core/overlays/tooltip/info.ts
Resolves #2103 
- Adds back the "Don't show tips again" button
- Moves the buttons logic out of the element and into the JigziHelp component
- For now no other code uses that button. In the future we can create a dedicated tooltip component to handle that logic.
- Converts the button to a  `<button />` instead of a `<div />`
> fix(fe/tooltips): Show the permanently close button in tooltips

- frontend/apps/crates/components/src/module/_common/edit/entry/dom.rs
- frontend/apps/crates/components/src/module/_common/edit/entry/state.rs
- frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
Resolves #2110 
- Calling `set_inner_html` on an `HtmlElement` does not drop references held for that element. This is because the underlying `DomHandle` that dominator knows about still exists. This change forces dominator to release references held by the previous handle whenever a new signal is fired to render a new body for a page.
> fix(fe/components): Force dominator to release previous DomHandles

- shared/rust/src/domain/jig/module/body/tapping_board.rs
closes #2201
Programmatical changes are ready for this PR.
The missing piece for sandbox is the media for the 3 new choice. Here are the routes that the front-end is requesting pictures from.
- https://media.jicloud.org/ui/module/tapping-board/edit/choose/comic.png
- https://media.jicloud.org/ui/module/tapping-board/edit/choose/timeline.png
- https://media.jicloud.org/ui/module/tapping-board/edit/choose/family-tree.png
This is similar to when we added the picture to the empty module on the jig sidebar. I can't yet add pictures to the media server yet. @MendyBerger, is it possible if you could upload those pictures for me? That or we could talk about getting me DropBox credentials so I can do so as well.
Thank you so much 🙏
> feat: change listen & learn choices

- frontend/apps/crates/entry/home/src/home/actions.rs
- frontend/apps/crates/entry/home/src/home/search_results/dom.rs
- frontend/apps/crates/entry/home/src/home/search_results/state.rs
- frontend/elements/src/entry/home/home/search-results/search-results.ts
Part of #2155 
- Hides jigs/resources sections when their totals are 0
- Adds searching text `"So many great JIGs and resources to sift through..."`
- Adds no results found text `"Oh snap! We couldn't find any matches for [query]"`
- Only shows results once both jigs and resources searches have completed
> feat(fe/search): Hide search results when the total is 0

- frontend/apps/crates/entry/home/src/home/search_results/dom.rs
- frontend/elements/src/entry/home/home/search-results/search-results.ts
Closes #2264 
- Adds anchors for JIGs and Resources to scroll to the relevant sections;
- Updates so that the noun for each is either singular or plural if the result count is 1 or more.
> feat(fe/search): Add search section anchors to result text

- frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/mod.rs
> feat(fe/jig/edit): Disable publish button in JIG edit when a JIG is incomplete

- frontend/apps/crates/components/src/lists/dual/dom.rs
- frontend/apps/crates/components/src/lists/dual/state.rs
- frontend/apps/crates/components/src/lists/single/dom.rs
- frontend/apps/crates/components/src/lists/single/state.rs
- frontend/apps/crates/components/src/module/_common/edit/entry/actions.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/config.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/state.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/actions.rs
- frontend/apps/crates/utils/src/iframe.rs
- shared/rust/src/config.rs
- shared/rust/src/domain/jig/module/body/_groups/cards.rs
- shared/rust/src/domain/jig/module/body/card_quiz.rs
- shared/rust/src/domain/jig/module/body/flashcards.rs
- shared/rust/src/domain/jig/module/body/matching.rs
- shared/rust/src/domain/jig/module/body/memory.rs
Part of #2216
- Implements rules for minimum requirements in card games:
- Words and Images: at least 2 pairs (max of 14), text card must not have empty text and images must be set on both pairs;
- All other card types: at least 2 pairs (max of 14) and cards may not have empty text.
- Update so that if a teacher wants to replace the word list, the state of the module is marked as incomplete (previously it would only mark as complete once and never update again);
- Moves MAX_LIST_WORDS to shared config; Adds MIN_LIST_WORDS to shared config (previously it was a magic number `2`).
Extra work included in this PR:
- Fixed dual and single lists so that their validation logic catches mismatched lists, empty text, etc.
> feat(fe/components/cards): Implement minimum requirements for card games

- frontend/apps/crates/components/src/module/_common/edit/entry/actions.rs
- frontend/apps/crates/components/src/module/_common/thumbnail/dom.rs
@corinnewo @GaliShapira This change prevents a screenshot from being requested until the activity has had the minimum required content set. When no screenshot exists, it already defaulted to "thumb-placeholder.svg".
> fix(fe/jig/edit): Only request a screenshot once a modules content has been marked as complete

- frontend/apps/crates/entry/jig/edit/src/gallery/actions.rs
- Updates the values pass to `JigSearchQuery` to use `UserOrMe::Me` (#2318)
> fix(fe/jig/edit): Update JigSearchQuery to use UserOrMe enum

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/actions.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/state.rs
- frontend/elements/src/entry/jig/gallery/gallery.ts
Closes #2252
- Adds "See more" button to the JIG edit gallery page
- Updates /browse so that it returns the correct amount of records and no longer returns the last record from the previous page as the first record in the current page
> feat(fe/jig/edit): Add load more button to the JIG edit gallery page

- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/state.rs
- frontend/apps/crates/components/src/tabs/state.rs
Part of #2280 
- Updates Step 1 of card games so that it uses tabs regardless of use case so that we can add in the new Audio tab for card games.
> feat(fe/cards): Use tabs for all step 1 of all card games

- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/state.rs
- frontend/elements/src/_bundles/_sub-bundles/module/_groups/cards/edit.ts
Part of #2280
- Adds confirm modals for removing images and audio from cards and for deleting card pairs.
> feat(fe/module/edit): Add confirm modal to remove/delete actions on card games

- frontend/apps/crates/components/src/module/_groups/cards/play/card/dom/dom.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/dom.rs
- frontend/apps/crates/entry/module/flashcards/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/flashcards/play/src/base/game/dom.rs
- frontend/apps/crates/entry/module/matching/play/src/base/game/card/actions.rs
- frontend/apps/crates/entry/module/memory/play/src/base/stage/game/actions.rs
- frontend/apps/crates/entry/module/memory/play/src/base/stage/game/dom.rs
- frontend/apps/crates/utils/src/events.rs
- frontend/elements/src/module/_groups/cards/play/card/card.ts
Part of #2280 
- Plays a cards audio based on the following rules:
- **Flashcards** - Play sound for card that appears, when a card is clicked, it plays the feedback sound and then the cards sound;
- **Memory cards** - Plays the flipping card sound and then the cards sound;
- **Matching** - Plays the card sound when the student starts dragging a card;
- **Quiz game** - When choosing a card, plays the feedback sound and then the cards sound.
Extra work included:
- Removes `eventOnFlipped` property introduced in #2134 and instead, each game type plays it's relevant sounds when appropriate.
> feat(fe/module/play): Play card audio for card games

- backend/api/sqlx-data.json
- backend/api/src/db/image.rs
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/src/translate.rs
- backend/api/tests/integration/jig.rs
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-2.snap
- backend/api/tests/integration/snapshots/integration__jig__update_and_publish-4.snap
Remove translations from create and update endpoints in images and jigs. The cron job now translates all descriptions in the background. This
> fix(be/translation_api): allow cron job to translate all descriptions

- frontend/apps/crates/components/src/module/_groups/cards/edit/main/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/actions.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/dom.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/memory/play/src/base/stage/game/actions.rs
- frontend/elements/src/module/_groups/cards/edit/main/card-pair/pair.ts
Closes #2280 
- Prevents selection from other tabs and clears selection when switching tabs;
- Memory game will play the card audio and then the negative/positive feedback sound;
- Card quiz will play the card audio and then the positive feedback sound.
- Flip effect for incorrect choice still plays before the card audio.
> fix(fe/cards): Update card audio to play before positive feedback effects

- frontend/apps/crates/entry/jig/edit/Cargo.toml
- frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/mod.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/module/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/state.rs
- frontend/elements/src/core/overlays/tooltip/container.ts
- frontend/elements/src/core/overlays/tooltip/error.ts
- frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts
- frontend/elements/src/entry/jig/edit/sidebar/module/window.ts
Closes #2216 
- Adds error tooltip to the first incomplete module in a JIG when the teacher clicks publish but has incomplete modules;
- Highlights incomplete modules in red;
- Scrolls to first incomplete module when clicking publish;
- Adds error tooltip to Publish window in the sidebar if the teacher clicks publish without adding any activities or a cover;
- Disables the publish button on the publish screen if the teacher hasn't added any activities or a cover.
Outstanding:
- Currently only the up and down arrows show up when tracking the position of the module in the sidebar.
- I have a draft PR with a POC refactor of tooltips to make them more practical: #2322
> Incomplete error tooltip

- frontend/apps/crates/entry/jig/edit/src/edit/actions.rs
- frontend/apps/crates/entry/jig/edit/src/edit/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/mod.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/state.rs
- frontend/elements/src/_bundles/jig/edit/imports.ts
- frontend/elements/src/core/modals/video.ts
- frontend/elements/src/module/video/youtube-player.ts
Part of #1773
- Adds a new modal-video element;
- Shows a video in a modal in the jig/edit screen. 
- When the video is closed by the teacher, they won't see it again unless they use a different browser.
- The video used is https://www.youtube.com/watch?v=x4FYtTpQAt0
> feat(fe/jig/edit): Show once-off onboarding video

- backend/api/src/algolia.rs
- backend/api/src/http/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
closes #2362 
Fix for mismatch `author_id` algolia  field
> fix(be/jig/search): change author to author_id in algolia

- backend/api/sqlx-data.json
- backend/api/src/extractor.rs
- backend/api/src/http/endpoints/admin.rs
- frontend/apps/Cargo.lock
- frontend/apps/crates/entry/admin/Cargo.toml
- frontend/apps/crates/entry/admin/src/export/actions.rs
- frontend/apps/crates/entry/admin/src/export/dom.rs
- frontend/apps/crates/entry/admin/src/export/mod.rs
- frontend/apps/crates/entry/admin/src/export/state.rs
- frontend/apps/crates/entry/admin/src/lib.rs
- frontend/apps/crates/entry/admin/src/router.rs
- frontend/apps/crates/entry/admin/src/sidebar/state.rs
- frontend/apps/crates/utils/src/routes.rs
- frontend/elements/src/_bundles/admin/imports.ts
- frontend/elements/src/entry/admin/export/export.ts
- frontend/elements/src/entry/admin/sidebar/item.ts
- shared/rust/src/domain/admin.rs
Closes #2353
- Adds a new extractor for claims so that a user can be authenticated with the csrf token - this is useful only for some edge cases like the downloading of a csv 👇 - shouldn't be used for auth on any endpoint which has side-effects;
- Adds a UI to the admin panel to export data as a csv - currently only Profiles can be exported.
> Export data UI

- backend/pages/Cargo.lock
- frontend/apps/crates/components/src/jigzi_help/dom.rs
- frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs
- frontend/apps/crates/entry/jig/edit/src/edit/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/selection/dom.rs
- frontend/apps/crates/utils/src/events.rs
- frontend/elements/src/core/buttons/rectangle.ts
- frontend/elements/src/core/overlays/tooltip/info.ts
Closes #1773
- Adds a "Show onboarding" button to the Jiggling text on the Add an Activity screen:
> feat(fe/jig/edit): Add show onboarding button to jiggling help text

- frontend/apps/crates/components/src/page_header/dom.rs
- frontend/apps/crates/components/src/page_header/state.rs
- frontend/apps/crates/entry/admin/src/router.rs
- frontend/apps/crates/entry/home/src/home/dom/mod.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
- frontend/apps/crates/entry/user/src/profile/dom/mod.rs
- frontend/elements/src/_bundles/_sub-bundles/page/header.ts
- frontend/elements/src/core/overlays/tooltip/container.ts
- frontend/elements/src/core/overlays/tooltip/info.ts
- frontend/elements/src/core/page-header/beta-button.ts
- frontend/elements/src/core/page-header/beta-tooltip-content.ts
- frontend/elements/src/core/page-header/page-header.ts
Closes #2365
- Adds a beta button to the page header;
- Adds a tooltip when the button is clicked.
> feat(fe/page-header): Add beta button and tooltip to page header

- backend/api/src/db/image.rs
> fix(be/image/search): images are ordered by uuid

- backend/api/migrations/20220228083216_add_jig_data_related_indexes.sql
Part of #2139
- Adds indexes to a number of lookup tables so that performance when fetching jig-related data is improved.
- Improves perf at the expense of storage which should be minimal tbh, the data is quite small.
The improvement is substantial, but the response times are still higher than what I feel that should be.
**Note** I struggled way too much trying to get Sentry tracing to work reliably. As a workaround I plugged otel tracing into my local install and shipped to Honeycomb so that I can get pretty reporting.
Based on running 1000 requests with 200 concurrent requests at a time.
> chore(be): Add indexes to improve jig_data lookups

- frontend/apps/crates/components/src/page_header/state.rs
Closes #2488
- Only shows the beta tooltip automatically once (RE https://github.com/ji-devs/ji-cloud/issues/2488#issuecomment-1059973501)
> fix(fe): Only show the tooltip once

- backend/api/src/db/jig.rs
- backend/api/src/db/meta.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/src/http/endpoints/meta.rs
Part of #2139 
- Adds more instrumentation to endpoints and database functions;
- Attempts to optimize metadata endpoint by running all the db queries at the same time instead of consecutively.
- Probably unnecessary at this stage, but I was in the code.
> chore(be): Add instrumentation for browse endpoint

- backend/api/Cargo.lock
- backend/api/Cargo.toml
- backend/api/src/http/endpoints/jig.rs
- backend/core/Cargo.toml
Part of #2139
- Updates Sentry SDK to 0.25.0
- Combines browse and count queries to run concurrently
> optimize(be): Run browse and count queries concurrently

- backend/core/src/sentry.rs
Because nearly nothing gets sampled. We can decrease this once traffic picks up on release.
> chore(be): Increase Sentry tracing sample rate to 0.8

- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs
- frontend/apps/crates/components/src/traces/svg/styles.rs
- frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_3/dom.rs
- frontend/elements/src/_bundles/_sub-bundles/module/_groups/cards/edit.ts
- frontend/elements/src/_bundles/_sub-bundles/module/edit.ts
- frontend/elements/src/module/_common/edit/sidebar-empty.ts
Closes #2363
- Moves the sidebar-empty element into module/_common/edit
- Updates the element so that the image displayed can be changed
- Includes an offset property to adjust positioning of images for more natural centering (see card game activities)
- Adds the sidebar-empty element to the tapping-board activity
> feat(fe/module/tapping-board): Add empty sidebar element when no area has been traced yet

- frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_3/dom.rs
Part of #2363
- Uses the empty-sidebar element on the drag and drop activity's Drop Areas step
> feat(fe/module/drag-drop): Use empty-sidebar element for "Drop Areas" step

- frontend/apps/crates/components/src/lists/dual/dom.rs
- frontend/apps/crates/components/src/lists/dual/state.rs
- frontend/apps/crates/components/src/lists/single/dom.rs
- frontend/apps/crates/components/src/lists/single/state.rs
Closes #1599 
- Adds confirm modal for clearing unsaved single/dual lists
> feat(fe/module/cards): Add confirm modal when clearing an unsaved list

- frontend/elements/src/entry/jig/edit/sidebar/header.ts
Closes #2525 
- Hides the open/close button completely when on the "Add activity" screen so that the sidebar cannot be closed.
> bug(fe/jig/edit): Hide sidebar open/close button when on add activity screen

- frontend/apps/crates/components/src/module/_common/edit/entry/state.rs
- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/debug.rs
- Updates frontend so that `goals` is removed from `JigData` (RE #2535)
> fix(fe): Remove goals property from JigData

- frontend/apps/crates/components/src/module/_common/edit/post_preview/actions.rs
- frontend/apps/crates/components/src/module/_common/edit/post_preview/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/actions.rs
- frontend/apps/crates/utils/src/iframe.rs
- frontend/elements/src/module/_common/edit/post-preview/post-preview-action.ts
- frontend/elements/src/module/_common/edit/post-preview/post-preview.ts
Closes #2286
- Adds the "Publish" action to the complete screen;
- Updates "Continue" to "Add new activity"
- Fixes alignment of actions (see before and after below)
> feat(fe/jig/edit): Add publish action to module complete screen

- frontend/elements/src/module/_common/edit/post-preview/post-preview-action.ts
- frontend/elements/src/module/_common/edit/post-preview/post-preview.ts
Part of #2286
- Adds slot and fixes alignment for non-convert complete screen
> feat(fe/jig/edit): Add publish action to non-convert module complete screen

- frontend/apps/crates/components/src/audio/input/components/main_content.rs
- frontend/elements/src/core/progress-bar/progress-bar.ts
- frontend/storybook/src/components/core/progress-bar/progress-bar.ts
Part of #2485
- Resolves infinite progress bar from overflowing out of the wrapper;
- Resolves missing rounded edges of progress indicator;
- Moves label into a slot so that callers can define the label if required, otherwise usages such as playing audio, would have the "Uploading... please wait." copy;
- Updates storybook to include the slotted label.
> fix(fe/elements/progress-bar): Fix infinite progress animation define it if necessary

- frontend/elements/src/core/page-footer/page-footer.ts
closes #2553 
- Adds `Jigzi Roadmap` link to `Product` list in home footer
- Links to `https://www.jewishinteractive.org/flipbook/index.html?page=1`
- Opens link in a new tab to allow user to keep the Jigzi tab available
> feat(fe/elements): add roadmap link to footer

- frontend/apps/crates/entry/user/src/register/pages/step_3/actions.rs
- frontend/apps/crates/entry/user/src/register/pages/step_3/dom.rs
- frontend/elements/src/entry/user/register/pages/step3.ts
closes #2557 
On registration Step 3:
- Don't preselect ages and affiliations
- Reduce grid gap to 16px
> feat(fe/user): dont preselect registration options, adjust spacing

- backend/api/sqlx-data.json
- backend/api/src/db/category.rs
- backend/api/src/domain.rs
- backend/api/src/http/endpoints/category.rs
- backend/api/src/main.rs
- backend/api/tests/integration/category.rs
- frontend/apps/crates/entry/admin/src/categories/actions.rs
- frontend/apps/crates/entry/admin/src/images/meta/actions.rs
- frontend/apps/crates/entry/home/src/home/state/search_state.rs
- frontend/apps/crates/entry/jig/edit/src/edit/publish/actions.rs
- shared/rust/src/domain/category.rs
- Optimizes the build_tree function so that it is no longer recursive
- Reduces response time (locally) from ~80ms to <20ms for calls to `/v1/categories?scope=Descendants`
- The algorithm is still not as efficient as it could be, but it will suffice.
- Fixes typo in "Descendants"
For reference, current timings on for release on Sentry:
> feat(be/categories): Optimize category tree algorithm

- shared/rust/src/domain/jig/module/body/_groups/cards.rs
- Removes upper limit on the length of lists when creating/editing card game activies.
> fix(fe/jig/edit): Remove upper limit on word/image lists during validation

- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents-2.snap
- frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
- frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
- frontend/apps/crates/entry/module/memory/edit/src/settings/sidebar/actions.rs
- frontend/apps/crates/entry/module/memory/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/memory/edit/src/settings/state.rs
- frontend/apps/crates/entry/module/memory/play/src/base/state.rs
- frontend/elements/src/module/_common/edit/widgets/settings/button.ts
- shared/rust/src/domain/jig/module/body/memory.rs
Closes #2426
- Adds "pairs per game" setting to memory game activity
- Single setting icon which can be disabled for default system defined pairs per game, or enabled and user-set;
- When disabled, uses maximum (14) pairs _or_ total pairs if that total is less than the maximum of 14;
- When enabled, a teacher can set the value to between 2 and 14 pairs, inclusive. Entering a value of less than 2 will reset it to 2. Entering a value of more than 14 will reset it to 14.
- Fixes number circle value
- Removes SVG for rendering the circle + number, uses a regular `<span />` and css.
- The SVG was causing number values > 10 to render to the right, not centered.
- Fixes an issue where clicking inside the setting bubble triggered a click event on the setting icon
- Prevent setting bubble from …
> feat(fe/module/memory): Add pairs per game activity setting

- .github/workflows/backend-api-release.yml
- .github/workflows/backend-api-sandbox.yml
- .github/workflows/backend-fastly-purge-release.yml
- .github/workflows/backend-fastly-purge-sandbox.yml
- .github/workflows/backend-media-release.yml
- .github/workflows/backend-media-sandbox.yml
- .github/workflows/backend-pages-release.yml
- .github/workflows/backend-pages-sandbox.yml
- .github/workflows/backend-screenshot-release.yml
- .github/workflows/backend-screenshot-sandbox.yml
- .github/workflows/frontend-entry-app-release.yml
- .github/workflows/frontend-entry-app-sandbox.yml
- .github/workflows/frontend-entry-elements-release.yml
- .github/workflows/frontend-entry-elements-sandbox.yml
- .github/workflows/frontend-module-app-release.yml
- .github/workflows/frontend-module-app-sandbox.yml
- .github/workflows/frontend-module-elements-release.yml
- .github/workflows/frontend-module-elements-sandbox.yml
Deployment to sandbox was failing due to GCP upcoming update in April.
- All YAML files in `.github/workflows` changed from `uses: 'google-github-actions/setup-gcloud@master'` to `uses: 'google-github-actions/setup-gcloud@v0'`
- Prompted by message: https://github.com/ji-devs/ji-cloud/runs/5636210323?check_suite_focus=true
> chore(be/github_actions): replace pin; master to v0

- frontend/apps/crates/entry/home/Cargo.toml
- frontend/apps/rust-toolchain.toml
Rust nightly 2022-03-23 has a change which has caused ring to stop building: https://github.com/rust-lang/rust/issues/95267
This PR locks the nightly version to nightly-2022-03-22.
> chore: Lock rust nightly version to nightly-2022-03-22

- frontend/apps/crates/components/src/module/_groups/cards/edit/actions.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/config.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/header/actions.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/header/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/header/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/play/config.rs
- frontend/apps/crates/entry/module/card-quiz/edit/src/debug.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/debug.rs
- frontend/apps/crates/entry/module/flashcards/edit/src/debug.rs
- frontend/apps/crates/entry/module/flashcards/play/src/debug.rs
- frontend/apps/crates/entry/module/matching/edit/src/debug.rs
- frontend/apps/crates/entry/module/matching/play/src/debug.rs
- frontend/apps/crates/entry/module/memory/edit/src/debug.rs
- frontend/apps/crates/entry/module/memory/play/src/config.rs
- frontend/apps/crates/entry/module/memory/play/src/debug.rs
- frontend/elements/src/_bundles/_sub-bundles/module/_groups/cards/edit.ts
- frontend/elements/src/core/aria-helpers.ts
- frontend/elements/src/module/_groups/cards/edit/main/add-pair.ts
- frontend/elements/src/module/_groups/cards/edit/main/main.ts
- frontend/elements/src/module/_groups/cards/helpers.ts
- shared/rust/src/domain/jig/module/body/_groups/cards.rs
Closes #2408 
- Adds a new use case for pairs of images;
- Moves the "Add pair" button into the list of cards
- Makes the new add pair button navigable with a keyboard (#2533)
> feat(fe/modules): Add image-image card game mode (use case)

- backend/api/migrations/20220404095051_fix-dragdrop-editor-state.sql
- Fixes the editor_state data for drag drop modules (Caused by the migration added in #2619)
> fix(be): Resolve broken editor state for dragdrop module

- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/user/src/profile/actions.rs
- frontend/apps/crates/entry/user/src/profile/dom/mod.rs
- frontend/apps/crates/entry/user/src/profile/state.rs
- Removes default sound effect when player starts dragging an item (requested by @corinnewo);
- Custom audio on the item still plays, however.
- Ran `cargo fmt`
> fix(fe/module/drag-drop): Remove start drag sound effect

- shared/rust/src/domain/jig/module/body/drag_drop.rs
- Adds default text when creating a new drag-drop activity for a JIG
> feat(fe/module/drag-drop): Add default text when creating a new drag-drop module

- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/state.rs
- When interactive items are configured _without_ targets, ensure that the game shows/plays feedback and ends correctly.
- Minor refactoring.
> fix(fe/module/drag-drop): Ensure game is ended when all items with targets are placed correctly

- backend/api/src/http/endpoints/user.rs
#2624 
- don't create a session token for Oauth user trying to change password
> fix(be/user/password): omit session creation for OAuth

- backend/api/sqlx-data.json
- backend/api/src/http/endpoints/user.rs
https://github.com/ji-devs/ji-cloud/issues/2644
Not all emails providers are non-case sensitive like Google. The email inserts must remain how the user input specified them.
> fix(be/reset/email): allow case sensitive inserts into the database

- frontend/apps/crates/components/src/collision/stickers_traces/pixels.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/actions.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/dom.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/state.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/dom.rs
Part of #2636 
This is initial work to begin enabling multiple drop targets for a sticker. 
- When editing a drag-drop activity:
- Adds logic to check whether a sticker has been placed within a target trace;
- When not within a trace, resets the stickers position, otherwise saves the new position.
- Creates a set of semi-transparent stickers that are visible whenever a sticker is being dragged or dropped on a target area;
Misc. updates
- Removes some unnecessary `async` declarations;
- Changes mouse events to pointer events so that dragging would work on touch devices.
https://user-images.githubusercontent.com/4161106/163121226-307e65a3-29a2-44fa-8da1-52b9940b9321.mov
> feat(fe/module/drag-drop): Reset dragged item position when outside of target area

- frontend/apps/crates/components/src/backgrounds/dom.rs
closes #1964 
------------------------------------------------------
> feat: dont stretch overlay image

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/translate.rs
Originally, draft and live jig descriptions were being translated. Since translated descriptions are only being used for Algolia searching, setting the cron job to translate only live descriptions will reduce the cost and usage of google translate api.
> feat(be/translations): translate live jigs only

- frontend/apps/crates/entry/module/drag-drop/edit/src/base/actions.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/actions.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/state.rs
Resolves #2686 
- Target area data in the Place tab were not being kept up to date with traces added in the Trace tab - This PR updates the logic so that they are synchronized correctly.
> fix(fe/module/drag-drop): Ensure drop targets are kept up to date on the client

- shared/rust/src/domain/jig/module/body/drag_drop.rs
Part of #2636 
- Changes the data structure added in #2691
> feat(shared/drag-drop): Change data type for dragdrop target list

- shared/rust/src/domain/jig/module/body/drag_drop.rs
Part of #2636 
- Improves data structure for easier trace placement detection when playing games
- Also helps for working out whether an item has already been placed in a specific trace when editing
> feat(shared/drag-drop): Change data type for dragdrop target list to include target trace index

- frontend/apps/crates/entry/module/drag-drop/edit/src/base/actions.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/actions.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/dom.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/drag/state.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/state.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/dom.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/state.rs
Closes #2636 
- Implements multiple drag targets for editing and playing
https://user-images.githubusercontent.com/4161106/165936801-50c081b1-c5f7-4ae6-908b-ba43b809ff5d.mov
> feat(module/drag-drop): Enable multiple targets for dragdrop activities

- backend/api/migrations/20220429115134_delete-dragdrop-activities.sql
Part of #2636 
- Off the back of #2700, this adds a migration to clear out existing dragdrop activities, and then fix the ordering of the indexes for each JIG.
It's a bit slow.
> chore(be/migration): Remove dragdrop activities and fix JIG activity indexes

- frontend/elements/src/entry/home/home/search-results/search-result.ts
Part of #2651 
- Adds a Jiggling to the back of JIG search results cards
https://user-images.githubusercontent.com/4161106/167582364-9340639c-e87c-47fc-957a-3fe09460ac05.mov
> feat(fe/jig/search): Add jiggling on back of JIG search results

- frontend/elements/src/entry/home/home/search-results/search-result.ts
- Disables the Jiggling for Safari (temporarily), because I couldn't quickly figure out how to resolve:
https://user-images.githubusercontent.com/4161106/167589174-36262408-9e3a-40dc-aaf6-7cdf31b26d43.mov
- Updates the animation so its a little bit less jarring:
https://user-images.githubusercontent.com/4161106/167589338-75128c78-c156-4e79-bb73-fdad3bfa4ea6.mov
> fix(fe/jig/search): Disable search result jiggling for Safari

- frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
- frontend/elements/src/_bundles/home/imports.ts
- frontend/elements/src/core/buttons/icon-label.ts
- frontend/elements/src/core/buttons/rectangle-icon.ts
- frontend/elements/src/entry/home/home/search-results/search-result.ts
Closes #2651
- Adds yellow play icon to the JIG search result cards;
- Updates the `button-rect-icon` element to allow users to pass in any before/after icon;
- Updates `button-icon-label` components to include `"dark-blue"` colour and adds a hover effect for that colour.
https://user-images.githubusercontent.com/4161106/167596185-3648543b-7b61-4f06-b2fa-208d5166ed62.mov
> feat(fe/jig/search): Add play icon to play button; Include extra action hover effect

- frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
- frontend/elements/src/core/buttons/icon-label.ts
- frontend/elements/src/entry/home/home/search-results/search-result.ts
- Updates spacing for icons and labels on the backs of JIG search result cards
> fix(fe/jig/search): Improve icon/label spacing on the back of JIG search result cards

- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
Resolves #2733
The regression was caused by #2700 when the activity completed check was not updated to work with the new multiple target traces logic.
> fix(fe/module/drag-drop): Resolve regression where a single placement of a drag drop item caused the activity to end

- frontend/apps/crates/components/src/share_jig/actions.rs
- frontend/apps/crates/components/src/share_jig/dom.rs
- frontend/apps/crates/components/src/share_jig/state.rs
Resolves #2735
- Adds copied notification for copying embedded code, student URL and student code:
https://user-images.githubusercontent.com/4161106/168264204-0d4ce940-fd6e-498b-b98e-7214c58b9147.mov
> feat(fe/jig/share): Add clearer notification for copying share data

- frontend/apps/crates/entry/jig/play/src/player/dom.rs
Part of #2731
This is a stop-gap solution so that JIGs which have been configured for LTR/RTL play render correctly regardless of the setting of the `direction` query parameter.
- Once a JIG is loaded, set the direction based on the JIGs config.
> fix(fe/jig/play): Use configured JIG player direction settings from JIG

- frontend/apps/crates/utils/src/routes.rs
- Removes the redirect when jig/edit/*/* is called to asset/edit/*/*
- The redirect was returning a NotFound error for loading the JIG gallery and when attempting to edit JIGs.
> fix(fe/asset/edit): Remove jig/edit redirect logic

- backend/pages/src/server/routes.rs
- Updates the SPA route for jigs from `/jig/**` to `/asset/**`
> fix(be/pages): Update jig route to asset

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/db/jig/module.rs
- backend/api/src/http/endpoints/jig/module.rs
- shared/rust/src/domain/jig/module/body.rs
Resolves #2743
- Checks whether the new modules data is complete and marks the `is_complete` column in the data table.
> fix(be/api): Add is_complete check when create a new JIG module

- backend/api/src/algolia/migration.rs
- Removes the multi attributes config for searchable attributes.
Since last week, the multiple attributes config has caused errors when searching against algolia:
The error is weird, but adding each of those attributes individually as searchable instead of comma separated fixes it.
> fix(be/algolia): Remove multiple attributes for searchable attributes

- backend/pages/src/server/routes.rs
- backend/pages/src/templates/spa.rs
- #2773 fixed routing for playing jigs, but broke it for loading galleries
> fix(be/pages): Fix routes for asset galleries

- backend/core/src/config.rs
Resolves #2766
- Increases the max payload size from 16KB to 256KB
> chore(be): Increase request/response size limit to 256KB

- backend/api/sqlx-data.json
- backend/api/src/db/course.rs
Decoding problem in browse query solved
`Vec<JigId>` -> `Vec<(JigId,)> `
> fix(be/course): correct tuple type for jig array

- backend/api/src/db/image.rs
This will return the same order of images that returns from Algolia instead of order by id.
> fix(be/image/search): correct order of image results from algolia

- shared/rust/src/domain/module/body/find_answer.rs
Part of #2658 
- Adds the question_field field and a new `QuestionField` enum to set either a text sticker or a dynamic label for displaying the question text.
> fix(shared/module/find-answer): Add new QuestionField enum to find-answer data model

- frontend/elements/src/module/matching/_common/main/container.ts
Resolves #2757
- Updates matching activity layout to be similar to card-quiz so that the bottom row should not be behind the navigation bar.
> fix(fe/module/matching): Improve placement of option row during play

- frontend/apps/crates/entry/module/matching/play/src/base/game/card/dom.rs
- Fixes issue when clicking/dragging a matching activity option, the play nav bar becomes temporarily unclickable and the student would have to click it twice to navigate to the next/previous activity.
- I have tested that pointer events still work correctly using the xcode simulator with 9th gen Ipad
> fix(fe/module/matching): Ensure that play navigation bar is always clickable

- .env.sample
- backend/api/migrations/20220419233654_image_user_usage.sql
- backend/api/migrations/20220613233654_image_user_usage.sql
- backend/api/sqlx-data.json
- backend/api/src/algolia.rs
- backend/api/src/algolia/migration.rs
- backend/api/src/db/image.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/jwk.rs
- shared/rust/src/api/endpoints/image.rs
closes https://github.com/ji-devs/ji-cloud/issues/2762
Image metrics to improve Algolia searches with the most used images, yielding the most popular images to appear at the top of the search list. After two weeks, the api will reset the `usage` count for images, and a new rotation of popular images will be displayed first. 
I added a new table, `image_usage`, with columns `image_id` and `usage_reset_at`(holds a timestamp for 14 days). When `PATCH v1/image/{image_id}/use` is called, this will increment an images `usage` field in `image_metadata`. In the Algolia image updater task, the `usage_reset_at` will reset to the current timestamp after two weeks. In Algolia, I set ranking to be a  custom rank attribute.
> feat(be/image): add image metrics functionality

- frontend/apps/crates/components/src/lists/dual/strings.rs
- frontend/apps/crates/components/src/lists/single/strings.rs
- frontend/apps/crates/entry/home/src/home/search_results/search_results_section/dom.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
- frontend/apps/crates/entry/jig/play/src/jig/sidebar/dom/info.rs
- frontend/apps/crates/utils/src/ages.rs
- frontend/elements/src/_bundles/home/imports.ts
- frontend/elements/src/_bundles/jig/edit/imports.ts
- frontend/elements/src/_bundles/jig/play/imports.ts
- frontend/elements/src/core/modals/confirm.ts
- frontend/elements/src/entry/home/home/search-results/search-result.ts
- frontend/elements/src/entry/jig/_common/age-range.ts
- frontend/elements/src/entry/jig/gallery/recent.ts
- frontend/elements/src/entry/jig/play/jig/sidebar/jig-info.ts
- frontend/elements/src/module/_groups/cards/_common/main-empty.ts
Closes #2582, #2503 and #2607
- Adds a `content_html` property;
- Updates the delete JIG modal to include a new warning;
- Updates "Done" to "Generate" for card game lists;
- Updates the copy when a card games content hasn't been generated yet;
- Updates the age range so that it uses a FontAwesome arrow instead of `-`.
> fix(fe): Improved age range rendering; Copy updates

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
closes https://github.com/ji-devs/ji-cloud/issues/2833
`Published_at` data was being cloned as well. Removing this will prevent cloned jig from showing up on published Jigs list.
> fix(be/jig/clone): remove published_at data from original jig

- backend/api/migrations/20220616210310_fix-badge-trigger.sql
- backend/api/sqlx-data.json
- backend/api/src/db/badge.rs
- shared/rust/src/api/endpoints/badge.rs
@MendyBerger 
- corrected routes for join and leaving badges
- corrected `member_count` field in functions for `badge_member` table
- corrected query fetch for `member_count`
- added trigger to set `last_synced_at` to `null` after insert or delete on `badge_member` table
> fix(be/badge): redo triggers for badge_member

- backend/api/src/algolia.rs
- backend/api/src/http/endpoints/badge.rs
- backend/api/src/http/endpoints/course.rs
- backend/api/src/http/endpoints/image.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/src/http/endpoints/user.rs
https://github.com/ji-devs/ji-cloud/issues/2825
Fix for deleting assets and users
Delete functionality was using Algolia `Client` instead of Algolia `Manager` so the api was using the wrong api key to delete.
I relocated the delete functionality into `Manager` from `Client`.
> fix(be/algolia): uses manager instead of client for deleting

- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
- frontend/elements/src/module/_common/edit/widgets/audio-input/audio-input.ts
Part of #2658
- Fixes failure to upload/record audio;
- Improves spacing of items in the audio-input element.
> fix(fe/find-answer): Drop audio lock when saving uploaded audio

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/src/http/endpoints/user/public_user.rs
- backend/api/tests/integration/jig.rs
- backend/api/tests/integration/snapshots/integration__jig__browse_order_by-2.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_order_by-3.snap
- backend/api/tests/integration/snapshots/integration__jig__browse_order_by.snap
- shared/rust/src/domain/asset.rs
- shared/rust/src/domain/jig.rs
closes https://github.com/ji-devs/ji-cloud/issues/2852
Query parameter `order_by` (defaults to `coalesce(updated_at,created_at)` if no input). 
```
struct JigBrowseQuery {
...
order_by: Option<OrderBy>,
}
```
> feat(be/jig/browse): order by created or published timestamp

- frontend/apps/crates/components/src/text_editor/state.rs
> fix(fe/text_editor): Render fonts alphabetically

- shared/rust/src/domain/module/body/find_answer.rs
Part of #2658 
- Makes the Dynamic variant of QuestionField optional.
Note: I need to merge this in separately so that I can use the remote backend.
> fix(shared/find-answer): Make QuestionField Dynamic variants transform optional

- backend/api/sqlx-data.json
- backend/api/src/db/course.rs
- backend/api/src/http/endpoints/scheduler.rs
- backend/api/tests/integration/course.rs
- backend/api/tests/integration/main.rs
- backend/api/tests/integration/snapshots/integration__course__update_and_publish_browse-2.snap
- backend/api/tests/integration/snapshots/integration__course__update_and_publish_browse-3.snap
- backend/api/tests/integration/snapshots/integration__course__update_and_publish_browse-4.snap
- backend/api/tests/integration/snapshots/integration__course__update_and_publish_browse.snap
- backend/api/tests/integration/user/snapshots/integration__user__public_user__browse_user_courses.snap
https://github.com/ji-devs/ji-cloud/issues/2938
- replaced `array()` with `array_agg()` to group all like values together in the SQL query
- unnested an `array_agg(cte.array_agg)` before ordering the `course_data_id`s
> fix(be/course/browse): use aggregate function to ignore duplicates courses

- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
> fix(fe/find-answer): Play correct audio when finishing last question; Empty text when no question text added

- shared/rust/src/domain/module/body/find_answer.rs
Part of #2947 
- Removes the title requirement from the is_complete check - The title is only set if the teacher sets it, or it is set automatically when they enter content into the question text, or select a question sticker. If it's empty, the text defaults to "Question <n>", example, "Question 1".
> fix(fe/find-answer): Remove title requirement from is_complete check

- frontend/apps/crates/entry/admin/src/curation/editable_jig.rs
- frontend/apps/crates/entry/admin/src/curation/state.rs
- frontend/apps/crates/entry/admin/src/curation/table/dom.rs
- frontend/elements/src/entry/admin/curation/table.ts
Closes #2852
- Adds the "Created" date column to the curation tool
> feat(fe/admin): Add Created date column to the curation tool

- frontend/apps/crates/components/src/stickers/text/dom.rs
- frontend/apps/crates/components/src/stickers/text/state.rs
- frontend/apps/crates/components/src/text_editor/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
Resolves #2977
- Moves the `renderer_ref` field out of the `TextEditor` and into the `Text` sticker component
> fix(fe/find-answer): Ensure every text sticker has an associated renderer_ref

- frontend/apps/crates/entry/module/find-answer/play/src/base/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
Part of #2978
- Clears the question sticker when starting an activity;
- Fixes a bug when a question had no text, subsequent questions _with text_ wouldn't render.
> fix(fe/find-answer): Clear the question sticker when starting the activity

- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
Part of #2658 
- Prevents the student from tapping the final trace multiple times and triggering the `evaluate_end` logic multiple times.
> fix(fe/find-answer): Prevent tapping the final answer trace multiple times

- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
Closes #2947
- Detects an incorrect choice (any tap which doesn't select an answer trace) and plays a negative feedback audio clip;
- Hides the attempts play setting for now.
> feat(fe/find-answer): Detect incorrect choice and play negative feedback audio

- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
- frontend/elements/src/_bundles/module/find-answer/edit/imports.ts
- frontend/elements/src/module/find-answer/sidebar/questions-empty.ts
Closes #2923
- The lines around the "or" text have not been added. I left those out because it was taking me too long to figure out how to add them correctly.
- The "Add a question" button which usually shows up at the bottom of the list is hidden if there are no questions present.
> feat(fe/find-answer): Update the empty sidebar UI

- frontend/elements/src/module/_common/edit/widgets/transform/box.ts
Closes #2815
- Repositions the menu button for stickers so that it is above the border box and out of the way
- Note that the menu button does not scale in size like the rotate button, so depending on screen resolution, the alignment and size of the buttons will likely be different.
> fix(fe/transform-widget): Reposition transform box menu button

- frontend/apps/crates/components/src/stickers/text/menu/dom.rs
- frontend/elements/src/core/wysiwyg/wysiwyg-base.ts
Closes #3033
- Adds the "edit" option to text stickers;
- Updates the edit logic so that when going into the edit state, the input field is focused immediately.
> feat(fe/stickers): Add edit menu item to the text stickers menu

- frontend/apps/crates/components/src/stickers/sprite/menu/dom.rs
- frontend/apps/crates/components/src/stickers/text/menu/dom.rs
- frontend/apps/crates/components/src/stickers/video/menu/dom.rs
- frontend/elements/src/core/menu/kebab.ts
- frontend/elements/src/entry/jig/edit/sidebar/module/menu.ts
Closes #2694;
Part of #2769.
- Increases the gap between menu items.
> fix(fe/menus): Increase gap between menu items

- frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_3/dom.rs
- frontend/apps/crates/entry/module/tapping-board/edit/src/strings.rs
- frontend/elements/src/_bundles/module/tapping-board/edit/imports.ts
- frontend/elements/src/module/tapping-board/edit/interaction-delete.ts
- frontend/elements/src/module/tapping-board/edit/interaction-label.ts
- frontend/elements/src/module/tapping-board/edit/interaction-preview.ts
Closes #2976
- Updates the interaction label field so that it has similar feel and functionality to the audio input field:
- Delete and preview button are positioned similarly;
- Both are styled the same.
- The delete button is visible only if there is text present;
- The preview button is enabled only if there is text present;
- Adds the Hebrew text controls to the field.
> feat(fe/tapping-board): Improve interaction label input

- frontend/elements/src/entry/jig/edit/sidebar/module/window.ts
> fix(fe/jig/edit): Set background of sidebar module window to white when active

- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/actions.rs
- Fixes broken CI
- Adds `allow(dead_code)` for the attempt limits functions - they will be used in the future once attempt limit logic is added.
> fix(fe/find-answer): Allow dead code for attempt limits functions

- backend/pages/Cargo.lock
- backend/pages/Cargo.toml
- backend/pages/src/server.rs
Resolves #1685 
- Workaround to redirect from www.jigzi.org to jigzi.org
- Regex only cares about the www part, the rest of the host is used as is. So if for example we had `www.sandbox.jigzi.org` it would return a redirect response with location header to `sandbox.jigzi.org`.
Probably not the greatest solution to this problem, but we aren't using a load balancer on GCP, instead we're using the cloudrun domain management which seems quite limited.
@RickyLB could you give this a once-over before its merged?
> feat(be/pages): Redirect response when request host is prefixed with www

- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__module__update_contents.snap
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/debug.rs
- shared/rust/src/domain/module/body/_groups/cards.rs
- shared/rust/src/domain/module/body/_groups/design.rs
Part of #2924
- Adds the feedback tab for Answer This;
- Adds the feedback tab for all card game activities (including flashcards).
> feat(fe/design): Add feedback field to design content struct

- frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/state.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
- frontend/apps/crates/entry/module/matching/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/matching/play/src/base/state.rs
- frontend/apps/crates/entry/module/memory/play/src/base/stage/dom.rs
- frontend/apps/crates/entry/module/memory/play/src/base/state.rs
Part of #2924
- Updates BaseExt to include a function to fetch an optional instructions player for feedback;
- Updates Answer This to set the instructions player in the base state;
- Adds feedback rendering to the card game activities.
> feat(fe/cards): Add feedback to Answer This card games player

- frontend/apps/crates/components/src/instructions/editor/dom.rs
- frontend/apps/crates/components/src/instructions/editor/state.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_3/state.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/state.rs
- frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/state.rs
- frontend/apps/crates/entry/module/video/edit/src/base/sidebar/step_3/state.rs
Closes #2924
- Change the label and placeholder text in the Feedback tab;
- Updates the Instruction component to allow for multiple `InstructionsType`'s. 
- This component needs to be renamed now that we're reusing it in more places than just the dragdrop activity.
> feat(fe/component/instruction): Add support for multiple instruction types

- backend/api/sqlx-data.json
- backend/api/src/db/circle.rs
- shared/rust/src/domain/circle.rs
@MendyBerger 
- `image` is no longer optional upon circle creation
- omitted `creator_id` from circle update request
> fix(be/circle): require image on create, rm creator_id update

- frontend/elements/src/module/_common/edit/widgets/lists/dual/dual-list.ts
- frontend/elements/src/module/_common/edit/widgets/lists/single/single-list.ts
Part of #2987;
Closes #3103.
- Ensures that the Hebrew text controls and the generate button are always visible when creating card game activities;
- Updates the instruction text for the lists.
> feat(fe/elements/lists): Make list headers and actions sticky so that they're always visible

- frontend/apps/crates/components/src/lists/dual/dom.rs
- frontend/apps/crates/components/src/lists/single/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/main/pair/card/dom.rs
- frontend/apps/crates/components/src/module/_groups/cards/edit/sidebar/step_1/dom.rs
- frontend/apps/crates/entry/admin/src/categories/dom.rs
- frontend/apps/crates/entry/admin/src/images/meta/dom.rs
- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/spot/dom.rs
- frontend/apps/crates/entry/jig/edit/src/gallery/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
- frontend/elements/src/core/buttons/rectangle.ts
- frontend/elements/src/core/modals/confirm.ts
Closes #2830
- Updates "dangerous" button primary colors to `dark-red-2` and `red-alert` for hover;
- Switches buttons so that the primary is always on the right for deletes;
- Updates the secondary button so that it uses the outline styling;
- Adds `confirmIcon` and `cancelIcon` properties to modal-confirm so that icons can be added to buttons;
- Uses the `delete-white.svg` icon for all deletes.
> feat(fe/modal-confirm): Update delete button colors, ordering and layout

- backend/api/sqlx-data.json
- backend/api/src/db/resource.rs
- backend/api/src/http/endpoints/resource.rs
- backend/api/tests/integration/snapshots/integration__resource__update_and_publish-3.snap
@MendyBerger 
- In SQL query where languages or display_name are updated, the `where` conditions should be in parenthesis for both inputs.
> fix(be/resource): group name and language conditions in update

- frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_3/dom.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/strings.rs
- frontend/elements/src/module/_common/edit/widgets/sidebar-drag-prompt.ts
Part of #3119
- Updates the copy on the Select and Trace tabs for Step 3;
- Uses the Trace graphic for now until we have the svg for the select tab's graphic.
> chore(fe/drag-drop): Update interaction select and trace tabs copy

- frontend/apps/crates/entry/jig/edit/src/edit/sidebar/actions.rs
Resolves #3127
- Places the error popup in the correct location and scrolls the sidebar to the incomplete module;
- Opens the sidebar if it was closed so that the teacher can see the highlighted module.
> fix(fe/jig/edit): Show error popup in correct location; Open sidebar when there's an error

- shared/rust/src/domain/module/body/tapping_board/play_settings.rs
> chore(fe/tapping-board): Change hint default to not highlight traces

- frontend/apps/crates/components/src/stickers/sprite/dom.rs
- frontend/apps/crates/components/src/stickers/text/dom.rs
- Fixes an issue that only happens in Chromium-based browsers (Edge, Chrome) on Windows and Linux where attempting to drag an inactive sticker would cause the stickers parent `empty-fragment` to be selected.
> fix(fe/stickers): Prevent user selection on chromium-based browsers in Windows/Linux

- backend/api/sqlx-data.json
- backend/api/src/db/jig/module.rs
- backend/api/tests/integration/jig/module.rs
- backend/api/tests/integration/jig/snapshots/integration__jig__module__drag_up_down_modules-2.snap
- backend/api/tests/integration/jig/snapshots/integration__jig__module__drag_up_down_modules.snap
closes https://github.com/ji-devs/ji-cloud/issues/2948
- pass in `jig_data_id` instead of parent_id (`JigId`) in sql query when `new_index > index`
> fix(be/module): correct module index when updated

- frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
- frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
- frontend/elements/src/module/_common/edit/widgets/settings/bubble.ts
- frontend/elements/src/module/_common/edit/widgets/settings/button.ts
Closes #3165
- Open the settings bubble when the teacher clicks on a setting;
- Bubble stays open until the teacher clicks outside of it or presses the "enter" key
Note that I didn't add the "x" button because couldn't figure out how to make it look neat.
https://user-images.githubusercontent.com/4161106/189634738-e7492e28-cf2e-489b-9a2b-f59726043fc5.mov
> feat(fe/settings): Show settings bubble when clicking a settings button

- frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
- Fixes an issue where closing the settings bubble wouldn't always save the value.
> fix(fe/settings): Save settings value whenever bubble is closed

- frontend/apps/crates/entry/module/legacy/play/src/base/activities/video/dom.rs
- shared/rust/src/domain/module/body/legacy/activity.rs
Resolves #3240
- The legacy player uses JSON files to load data of legacy JIGs. The JSON files were not updated as part of the migration for the Youtube data model changes prevented slides with youtube URLs to break on the frontend when being deserialized.
> fix(fe/legacy): Ensure legacy json slides can correctly deserialize when activity contains a video sticker

- backend/pages/src/server/routes.rs
- backend/pages/src/templates/spa.rs
- Fixes issue where frontend assets for "assets" were being served from `/jig/<page_kind>` instead of `/asset/<page_kind>`
> fix(pages/asset-template): Updates pages to serve assets from correct paths

- backend/api/Cargo.lock
- backend/api/Cargo.toml
- backend/pages/Cargo.lock
- frontend/apps/Cargo.lock
- shared/macros/Cargo.toml
- shared/macros/src/lib.rs
NB: this will only work with a version of sqlx that includes the ::test macro (i.e. this branch I think: https://github.com/RickyLB/ji-cloud/tree/chore/update_actix)
Adds a new proc macro which wraps sqlx::test so that we can test our actix services and shut them down correctly without holding the db pools farmed out by sqlx::test.
- Test fns only have a single argument, `port: u16`, so that requests to the service can use the correct port.
- A service setup function needs to be provided with the following signature: `async fn setup_service(fixtures: &[T], services: &[T], pool_opts: PgPoolOptions, conn_opts: PgConnectOptions) -> (ServerHandle, u16)`
- This setup function replaces the service setup logic that is used in every test.
- Uses catch_unwind to handle a panic so that the service …
> feat(shared/macros): Add proc macro for testing the backend services

- backend/api/sqlx-data.json
- backend/api/src/http/endpoints/scheduler.rs
- backend/api/src/http/endpoints/scheduler/expired_emails.rs
resolves https://github.com/ji-devs/ji-cloud/issues/3295
- api endpoint that checks for unverified sign-up sessions, and deletes the expired `user_id` from the database.
- added endpoint to google cloud scheduler
> feat(be): remove users with expired verification emails

- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/elements/src/core/overlays/tooltip/info.ts
- frontend/elements/src/module/_common/edit/post-preview/post-preview.ts
Closes #3308.
- Instructions popup has centered text, expands wider with more text and respects newlines in copy;
- Post preview screen has conversion actions on a new row.
> chore(fe/play): Update instructions popup to grow with text, respect newlines and center content

- frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/matching/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/memory/play/src/base/stage/dom.rs
- frontend/apps/crates/utils/src/iframe.rs
- shared/rust/src/domain/module/body.rs
Closes #3307
- Fixes issue where activities wouldn't end correctly if no feedback config was set;
- Updates instruction/feedback logic to only show popup if there is a timer or if there is text set.
> fix(fe/module): Ensure activities end correctly when no feedback config is set

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- Fixes issue when an activity has feedback configured with both text and audio, once the audio completed, the JIG would be advanced to the next activity.
> fix(fe/play): Prevent feedback advancing to next activity automatically when there is text and audio

- frontend/apps/crates/components/src/audio/mixer/mixer_top.rs
- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- Fixes issue where clicking "Repeat" in instruction popup multiple times could play the audio multiple times simultaneously.
> fix(fe/instructions): Prevent playing multiple instructions audio simultaneously

- frontend/elements/src/core/menu/menu-line.ts
> fix(fe/stickers): Remove 's' from forward/backward menu items

- frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/state.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/state.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
- frontend/apps/crates/entry/module/matching/play/src/base/state.rs
- frontend/apps/crates/entry/module/memory/play/src/base/state.rs
- frontend/apps/crates/utils/src/iframe.rs
Resolves #3317
- Adds an extra `PreStart` phase so that instructions can be played/shown.
> fix(fe/instructions): Prevent overlapping instructions audio with activity audio

- frontend/apps/crates/components/src/stickers/dom.rs
- frontend/apps/crates/components/src/transform/dom.rs
- frontend/apps/crates/components/src/transform/state.rs
Part of #1837
- Adds arrow keys to move stickers, with Shift key for moving faster;
- Adds delete key for deleting a selected sticker.
> feat(fe/stickers): Implement move keys and delete key on all stickers

- frontend/apps/Cargo.toml
- frontend/apps/crates/components/src/module/_common/edit/header/controller/dom.rs
- frontend/apps/crates/components/src/stickers/dom.rs
- frontend/apps/crates/components/src/transform/dom.rs
- frontend/apps/crates/components/src/transform/state.rs
- frontend/apps/crates/utils/src/keyboard.rs
- frontend/apps/crates/utils/src/lib.rs
Part of #1837
- Adds undo/redo shortcut keys:
- On Mac: Cmd + Z to undo, Cmd + Shift + Z to redo;
- On Linux/Win: Ctrl + Z to undo, Ctrl + Y to redo.
> feat(fe/stickers): Implement undo and redo during activity editing

- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
- Resolves #3095;
- Resolves issue where instructions would show up at the end of an activity.
> fix(fe/instructions): Pause timer to prevent instructions from showing at the end of an activity; Correctly ends the Answer This activity

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
Fix regression caused by #3372 which removed the code to drop the audio handle whenever the popup closes.
> fix(fe/instructions): Drop instructions audio when popup is closed

- frontend/elements/src/module/_groups/cards/play/card/card.ts
- frontend/elements/src/module/_groups/cards/play/card/styles.ts
https://github.com/ji-devs/ji-cloud/issues/3230
Increases the border radius of the frontside of the flipped card
- selected element `.front.content`, and initialized `border-radius: 56px` for attributes `side="left"` and `size="flashcards`
- assigned variable `--border-radius: 16px` in `:host` to `border-radius` in `.content` element
> fix(fe/flashcards): increase card border radius

- frontend/apps/crates/components/src/instructions/editor/dom.rs
- frontend/elements/src/module/_common/edit/widgets/audio-input/audio-input.ts
https://github.com/ji-devs/ji-cloud/issues/3113
- `div` has a styled grid
-  `row-gap` for `div` was increased to `16px`
> fix(fe/instructions): increase gap between instruction and audio/upload texts

- frontend/elements/src/module/_groups/cards/play/card/styles.ts
resolves https://github.com/ji-devs/ji-cloud/issues/3397
- `overflow` property, set to `hidden` to clip borders of oversized images
> fix(fe/play/cards): resize oversized images in flashcards

- frontend/elements/src/module/_common/edit/post-preview/post-preview-action.ts
- frontend/elements/src/module/_common/edit/post-preview/post-preview.ts
https://github.com/ji-devs/ji-cloud/issues/3326
- changed the order of actions
- apply orange background
- adjust grid box dimensions
- decrease font size of top headers
- removed "Its now a part of your JIG"
- make text shorter: "Use this content in:"
- make activity texts single-line
- decrease line height for text, "Add new activity"
> style(fe/edit/post-preview): reformat and remove headers on post preview page

- frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/flashcards/play/src/base/game/actions.rs
Actually part of #3284 - I was working out simplest way to update settings based on content.
- Caps the "view pairs" setting at the total number of cards currently in in the deck;
- Caps the number of rounds at the minimum of view pairs setting or number of cards in deck.
> feat(fe/flashcards): Make view pairs setting dynamic so it's capped at current amount of pairs

- frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
- frontend/apps/crates/entry/module/card-quiz/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/flashcards/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/matching/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/memory/edit/src/settings/sidebar/dom.rs
- frontend/apps/crates/entry/module/tapping-board/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/video/edit/src/base/sidebar/step_3/play_settings/dom.rs
Part of #3284
- Lays groundwork for enhancements required by #3284, #3285, #3279, etc.
- `new`, `new_none`, `new_value`, `new_click`, `new_value_click` and replaces them with a `SettingsButtonBuilder` struct to make SettingsButton construction more flexible and less messy;
- Updates all activity settings to use the new builder.
> chore(fe/settings): Use a builder to construct instances of SettingsButton

- frontend/apps/crates/components/src/module/_common/edit/settings/button/dom.rs
- frontend/apps/crates/components/src/module/_common/edit/settings/button/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/actions.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/config.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/lib.rs
- frontend/apps/crates/utils/src/unwrap.rs
- frontend/elements/src/module/_common/edit/widgets/settings/bubble-content.ts
- shared/rust/src/domain/module/body/find_answer/play_settings.rs
Part of #3291 
- Removes "Student finishes this activity by...";
- Updates "ask in order" to be default and moves to the first position;
- Updates logic so that we can customize setting bubble labels - for the highlight correct answer setting;
- Setting has been added and hidden until the play logic is updated.
- Moves the timer settings to be on the last row;
- Updates text of the timer settings 
- Hidden until the play logic is updated;
> feat(fe/find-answer): Update settings; Keep attempts setting hidden for now

- frontend/apps/crates/components/src/module/_common/play/entry/dom.rs
- frontend/apps/crates/components/src/module/_common/play/entry/ending/dom.rs
- frontend/apps/crates/components/src/module/_common/play/entry/state.rs
- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- frontend/apps/crates/entry/module/card-quiz/play/src/base/state.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/base/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_4/play_settings/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/state.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
- frontend/apps/crates/entry/module/matching/play/src/base/state.rs
- frontend/apps/crates/entry/module/memory/play/src/base/state.rs
- frontend/apps/crates/utils/src/iframe.rs
- shared/rust/src/domain/jig/player.rs
Part of #3291
- Timer:
- Timer restarts at the start of each question. Default is 10 seconds.
- Stop timer when a question is completed correctly.
- If there are multiple questions, then the NEXT in the player should go to the next question and not the next module.
- If the student is on the last question, the next button goes to the next module; If they're on the first question, the back button goes to the previous module.
> feat(fe/player): Allow modules to opt-in to controlling player navigation; Allow modules to update the timer

- frontend/apps/crates/entry/module/flashcards/play/src/base/game/actions.rs
- frontend/apps/crates/entry/module/flashcards/play/src/base/game/dom.rs
> fix(fe/flashcards): Only play card audio if the activity is in the playing phase

- frontend/apps/crates/components/src/stickers/dom.rs
> fix(fe/stickers): Delete key should only delete a text sticker if it's not being edited

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
- shared/rust/src/domain/module/body.rs
Closes #3333 
- Replaces instructions text/audio with question audio once activity has started so that a student can press the button to replay the question;
- Added a new `InstructionType` variant `InActivity` which allows activities to set new text/audio that can be played.
- Fixes issue where replaying an activity would replay the last instruction audio;
> feat(fe/find-answer): Add ability to replay question audio from instructions button

- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/actions.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/state.rs
> fix(fe/find-answer): Prevent audio playback from overlapping across selections/questions

- backend/api/migrations/20230111223319_translated-flag.sql
- backend/api/sqlx-data.json
- backend/api/src/translate.rs
- capture first two letters of ISO code from detected source language
- new db `name_translate_status` and `description_translate_status` flags to mark status of translations for each asset data id
- trigger to reset statuses to null when updates to description or name have been made
> fix(be/translate): slice detected language and add translation status

- frontend/apps/crates/components/src/stickers/dom.rs
- frontend/apps/crates/components/src/stickers/text/dom.rs
- frontend/apps/crates/components/src/stickers/text/state.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/actions.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/sidebar/step_3/dom.rs
Closes #3085 
- If a teacher adds a new question without selecting a text sticker, one will be added with the text "Your question box";
- They are not able to delete that sticker unless all questions are deleted;
- On step 3, the question sticker will not be editable except to move it around;
- Existing activities that didn't have a text sticker will still work - there is no clean way to update those to include a sticker without potentially ruining the activity layout. 
- I need to check how many activities exist that don't have a sticker selected.
> feat(fe/find-answer): Make question field dynamic

- frontend/elements/src/module/_common/edit/widgets/transform/box.ts
Closes #3594
- Moves resize handles outside of the transform box;
- Makes sure that the rotation handle is always the same size as the kebab menu button;
- Makes the resize handles slightly smaller;
- Updates the pointer so that it uses the correct resize pointers for each resize handle.
> feat(fe/stickers): Move resize handles outside box

- frontend/apps/crates/components/src/page_header/dom.rs
- frontend/elements/src/core/page-header/page-header.ts
https://github.com/ji-devs/ji-cloud/issues/3663
TODO:
> style(fe/home): move help icon closer to user

- backend/api/sqlx-data.json
- backend/api/src/db/jig.rs
- backend/api/src/http/endpoints/jig.rs
- shared/rust/src/api/endpoints/jig.rs
- shared/rust/src/domain/jig.rs
https://github.com/ji-devs/ji-cloud/issues/3687
@MendyBerger 
- Route: `POST /v1/jig/admin/transfer`
- Req fields in JSON: 
>- `from` (`UserId`) - former JIG owner
>- `to` (`UserId`) - target user id
>- `jigIds (`Vec<JigId>`) - list of JIG Ids to transfer ownership from
> feat(be/jig/admin): add endpoint to transfer ownership of JIG

- shared/rust/src/domain.rs
- shared/rust/src/domain/additional_resource.rs
- shared/rust/src/domain/animation.rs
- shared/rust/src/domain/audio.rs
- shared/rust/src/domain/category.rs
- shared/rust/src/domain/circle.rs
- shared/rust/src/domain/course.rs
- shared/rust/src/domain/image.rs
- shared/rust/src/domain/jig.rs
- shared/rust/src/domain/jig/curation.rs
- shared/rust/src/domain/jig/report.rs
- shared/rust/src/domain/meta.rs
- shared/rust/src/domain/module.rs
- shared/rust/src/domain/pdf.rs
- shared/rust/src/domain/pro_dev.rs
- shared/rust/src/domain/pro_dev/unit.rs
- shared/rust/src/domain/resource.rs
- shared/rust/src/domain/resource/curation.rs
- shared/rust/src/domain/resource/report.rs
- shared/rust/src/domain/user.rs
Part of #3697 - Some cleaning up so that Uuid newtypes can be implemented a bit more easily and consistently.
Adds a util macro to generate newtype wrappers around UUIDs:
```rust
wrap_uuid! {
/// Wrapper type around [`Uuid`](Uuid), represents the **unique ID** of a module.
///
/// This uniquely identifies a module. There is no other module that shares this ID.
#[serde(rename_all = "camelCase")]
pub struct ModuleId
}
```
Generates:
```rust
#[derive(Copy, Clone, Debug, Eq, PartialEq, Serialize, Deserialize, PathPart, Hash)]
#[doc = " Wrapper type around [`Uuid`](Uuid), represents the **unique ID** of a module."]
#[doc = ""]
#[doc = " This uniquely identifies a module. There is no other module that shares this ID."]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "backend", …
```
> chore(shared): Add wrap_uuid macro to make it easier to add Uuid newtypes

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/dom.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- frontend/apps/crates/entry/module/drag-drop/play/src/debug.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/game/playing/dom.rs
- frontend/apps/crates/entry/module/find-answer/play/src/base/state.rs
- frontend/apps/crates/entry/module/flashcards/play/src/debug.rs
- shared/rust/src/domain/module/body.rs
> feat(fe/module-assist): Hide popup when audio-only instructions, except for timer and override

- backend/api/Dockerfile
Could shave up to a minute off the build time.
~Will merge once the v1.68.0 base docker image is available.~
> chore(be): Use crates.io sparse protocol for building images

- backend/api/src/http/endpoints/user.rs
- use lowercased email when user wants to resend a verification email
> fix(be/verify-email): lowercase email input when resent

- frontend/apps/crates/entry/asset/play/src/pro_dev/dom.rs
- frontend/elements/src/_bundles/asset/play/imports.ts
- frontend/elements/src/entry/asset/play/pro-dev/pro-dev-player.ts
https://github.com/ji-devs/ji-cloud/issues/3612
- basic styling to center content, title, and navigation tabs
> feat(fe/pro-dev/player): move content to middle of screen

- frontend/apps/crates/entry/asset/play/src/pro_dev/player_popup/action.rs
- frontend/apps/crates/entry/asset/play/src/pro_dev/player_popup/dom.rs
- frontend/apps/crates/entry/module/legacy/play/src/base/activities/talk_type/actions.rs
- forward and back arrow buttons disable when first or last units are active in player
- remove unnecessary `mut` in crates/entry/module/legacy/play/src/base/activities/talk_type/actions.rs:94
> fix(fe/asset/play/pro-dev): disable nav arrows on first and last units

- frontend/apps/crates/entry/asset/play/src/pro_dev/player_main/dom.rs
- frontend/apps/crates/entry/asset/play/src/pro_dev/player_popup/dom.rs
- all active units automatically get inserted into played units in player
> fix(fe/asset/play/pro-dev): mark all active units as played in player

- frontend/apps/crates/entry/asset/edit/src/edit/actions/course_actions.rs
- frontend/apps/crates/entry/asset/edit/src/edit/actions/jig_actions.rs
- frontend/apps/crates/entry/asset/edit/src/edit/pro_dev/unit_editor/actions.rs
- frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/actions.rs
- frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/dom.rs
- frontend/apps/crates/entry/asset/edit/src/edit/sidebar/spot/state.rs
- frontend/apps/crates/entry/asset/edit/src/edit/sidebar/state.rs
- frontend/apps/crates/entry/asset/edit/src/edit/state.rs
https://github.com/ji-devs/ji-cloud/issues/3610
- add new units into specified spots 
- new field `target_index` to `AssetEditState` and `SidebarSpot`
> fix(fe/asset/edit/pro-dev): add unit spot using gear

- frontend/apps/crates/entry/asset/edit/src/edit/sidebar/header/dom.rs
- shared/rust/src/domain/asset.rs
https://github.com/ji-devs/ji-cloud/issues/3832
- Remove "Pro Dev" on preview button
- Change "My Pro Devs" to "My ProDev courses" for gallery return button on sidebar
> style(fe/asset/edit/pro-dev): rm display name from Preview button

- backend/api/sqlx-data.json
- backend/api/src/db/course.rs
- backend/api/src/http/endpoints/course.rs
- shared/rust/src/api/endpoints/course.rs
- shared/rust/src/domain/course.rs
resolves https://github.com/ji-devs/ji-cloud/issues/3924
- play endpoint `PUT /v1/course/{{course_id}}/play`
- Optionally Order browse results by play count
- `orderBy=playCount`
> feat(be/course): browse sort by play count

- frontend/apps/rust-toolchain.toml
`rustup update` on CI has become flakey over the few days.
> fix: Pin rust nightly

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts
- clickable playlist names in the JIG info section
> feat(fe/asset/play/jig): generate playlist names associated with jig

- backend/api/sqlx-data.json
- backend/api/src/db/account.rs
- backend/api/src/http/endpoints/account.rs
- backend/api/src/http/endpoints/admin.rs
- shared/rust/src/domain.rs
- shared/rust/src/domain/billing.rs
Closes #3948
- Adds `UpdateNonNullable` and `UpdateNullable` types for update/PATCH requests where some fields can be omitted so that they aren't updated at all. Will eventually replace the `Option<Option<T>>` types which do the same thing.
> feat(be/billing): Create school account endpoint accepts all school account fields.

- frontend/apps/crates/entry/user/src/register/pages/step_1/state.rs
https://github.com/ji-devs/ji-cloud/issues/3727
- message change from "Already exists!" to "Sorry, this username is taken. Please try another."
> fix(fe/user/signup): change error message for existing username

- backend/api/migrations/20230703205646_public_user_asset_count.sql
- backend/api/sqlx-data.json
- backend/api/src/db/course.rs
- backend/api/src/db/jig.rs
- backend/api/src/db/playlist.rs
- backend/api/src/db/resource.rs
- backend/api/src/db/user/public_user.rs
- backend/api/src/http/endpoints/course.rs
- backend/api/src/http/endpoints/jig.rs
- backend/api/src/http/endpoints/playlist.rs
- backend/api/src/http/endpoints/resource.rs
https://github.com/ji-devs/ji-cloud/issues/3974
TODO:
> feat(be/asset): add count of assets

- frontend/apps/crates/entry/user/src/router.rs
- frontend/apps/crates/entry/user/src/subscribe1/actions.rs
- frontend/apps/crates/entry/user/src/subscribe2/actions.rs
- frontend/apps/crates/entry/user/src/subscribe2/state.rs
- frontend/apps/crates/utils/src/routes.rs
We need to include the setup intent ID in the subscribe request so that we can mark the payment method as the default payment method. Without a default, once a trial expires, Stripe won't be able to successfully charge the customer.
> fix(fe/user): Include Stripe setup intent ID in the subscribe request

- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts
> fix(fe/asset/play/jig): hide resource and playlist sections in JIG info

- backend/api/migrations/20230720090405_update-subscription-table-trial-status.sql
- backend/api/sqlx-data.json
- backend/api/src/db/billing.rs
- backend/api/src/db/user.rs
- backend/api/src/http/endpoints/billing.rs
- backend/api/tests/integration/snapshots/integration__user__browse_user_badges-1.snap
- backend/api/tests/integration/snapshots/integration__user__browse_user_badges-2.snap
- frontend/apps/crates/entry/admin/src/users/editable_user.rs
- shared/rust/src/domain/billing.rs
- shared/rust/src/domain/user.rs
Part of #4021 
- Updates period end date to show just the date;
- Adds a `"(Trial)"` postfix to the date if the subscription is in trial mode;
- Adds a new `is_trial` field to subscription table;
- Sets the `is_trial` field based on the `Trialing` stripe subscription status received in webhook events;
- Removes the `auto_renew` field and instead sets it for display purposes only based on whether a subscription currently `Active`.
> feat(be/billing): Add subscription trial status

- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
- frontend/apps/crates/utils/src/toasts.rs
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts
> fix(fe/asset/play/jig): remove resource display name from info panel

- backend/api/src/error.rs
- backend/api/src/http/endpoints/billing.rs
- shared/rust/src/api/endpoints/billing.rs
- shared/rust/src/domain/billing.rs
- Updates the cancel endpoint to use http `PATCH` request because it doesnt actually delete anything, it updates the sub;
- moves the endpoint to `/v1/subscription/cancel`
- Requires a request object with a `status` field with possible values of `period-end` or `remove` to cancel at period end, or remove cancellation respectively.
> feat(be/billing): Update subscription cancellation endpoint to allow cancel removal

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
- frontend/apps/crates/entry/asset/play/src/jig/state.rs
- frontend/elements/src/_bundles/asset/play/imports.ts
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info-category.ts
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts
- A JIG's categories/keywords are listed on the sidebar info panel
> feat(fe/asset/play/jig): add keywords to info panel

- frontend/apps/crates/entry/asset/edit/src/edit/course/unit_editor/actions.rs
- frontend/apps/crates/entry/asset/edit/src/edit/course/unit_editor/dom.rs
https://github.com/ji-devs/ji-cloud/issues/3998
- Update Unit button stays activated in Unit Editor
> fix(fe/asset/edit/course): keep Update Unit button activated

- frontend/apps/crates/utils/src/init/user.rs
- frontend/apps/crates/utils/src/paywall/checks.rs
- shared/rust/src/domain/billing.rs
Moving PlanTier to the shared crate so that it can be used in the backend too.
> chore: Move PlanTier to shared crate

- backend/api/Cargo.lock
- backend/api/Cargo.toml
- backend/api/src/http/endpoints/billing.rs
- backend/pages/Cargo.lock
- frontend/apps/crates/entry/user/src/settings/actions.rs
- shared/rust/Cargo.toml
Closes #4111
- Suppresses backend warning for missing Stripe webhook event `"billing_portal.session"`
- Should be removed once the crate supports that event.
- Adds a notice-level toast when toggling subscription cancellation state 
- Upgrades async-stripe
- Prevents the call to the cancel endpoint being cancelled by the call to the customer-portal endpoint when toggling
> fix: Prevent subscription cancelation endpoint being canceled immediately

- frontend/apps/crates/entry/asset/play/src/jig/actions.rs
- frontend/apps/crates/utils/src/quick_elements.rs
- Closes #4108 
- Loads the asset so that there is something visible behind the modal;
- Decreases the opacity slightly so that whatever is behind the modal is a little bit more visible.
> chore: Load asset and decrease opacity of backdrop

- frontend/elements/src/entry/home/home/search-results/search-result.ts
- This removes some of the other css code that was added to work around this issue.
> fix: Offset the back of the card by 1px so that safari doesn't render the back of the front when the back of the card should be visible

- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/info.rs
- frontend/apps/crates/entry/asset/play/src/jig/sidebar/dom/share.rs
- frontend/elements/src/core/popups/popup-body.ts
- frontend/elements/src/entry/asset/play/jig/sidebar/jig-info.ts
- Fixes #4087
- Uses the same close button as the Share popup;
- Fixes the header of the info popup so that it resizes cleanly for titles that wrap.
> fix: Prevent jig info popup getting cut off in Safari

- frontend/apps/crates/entry/module/cover/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/drag-drop/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/embed/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/find-answer/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/poster/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/tapping-board/edit/src/base/main/dom.rs
- frontend/apps/crates/entry/module/video/edit/src/base/main/dom.rs
> fix: Ensure that the editing grid is always visible when editing a design module

- frontend/apps/crates/entry/home/src/home/dom/mod.rs
Hide all the extra rows  (Trending and Top Picks)so that a new user gets to see the animation about jigzi first.
I also removed a slight space on the `empty-fragment` element of the wix segment above it.
@johnnynotsolucky @corinnewo
> Remove tips and featured jigs for non logged in users

- frontend/apps/crates/entry/home/src/pricing/dom.rs
- frontend/elements/src/entry/home/pricing/school-pricing.ts
- shared/rust/src/domain/billing.rs
As per: 
@johnnynotsolucky 
This is a bit involved, since it affects price plans. The instruction is to just change the text for the unlimited plan to limit it to 30, and not add a new price plan limiting it to 30.
I've done it so that it should only affect the text instructions and not anything else. This won't stop someone from adding more than 30. Handling whether or not someone can go over 30 will be on a case-by-case basis.
@corinnewo 
The price line is offset and misaligned with the rest of the rows.  This looks deliberate, but I can center it like the other rows if needed: see below
> Limit the unlimited plan (!) to 30 and add text to contact for more

- frontend/apps/crates/entry/home/src/home/search_results/dom.rs
- frontend/apps/crates/entry/home/src/home/search_results/state.rs
- frontend/elements/src/entry/home/home/search-results/search-results.ts
If a user searches and there are no results, a message comes up saying - can't find matches, try selecting 'all' 
But this needs to be changed now, as we changed the default to "All"
Solution: Only have the suggestion showing if the tab is set to 'Top rated'. If the tab is set to 'All', the message should be only the first sentence: "Oh snap! We couldn't find any matches for [string]."
Rated
All
With results works as normal
@johnnynotsolucky @corinnewo
> Make empty search results hint conditional

- frontend/apps/crates/entry/user/src/likes/dom.rs
Move Playlists to above Jigs
Also, there was little space between the header and the first section (Playlists), so I added a 20px gap there
> Tweak: Change order of sections on My Likes
